### ISSUE TITLE
security vulnerability in example code

### ISSUE THREAD

**Issue by blazespinnaker** [expressjs/csurf#100]
The example code doesn't specify a secret for the cookieParser, so it uses csrf token hashing based on rndm which uses Math.random() and is stated not to be cryptographically secure.

**Comment by dougwilson** [comment]
Hi @blazespinnaker, I'm sorry I was not able to get to your report very quickly. Probably not the best forum to report these types of issues. I'm going to get the Express security policy added to this repository, but in the meantime, please if you want to just follow this copy at https://github.com/expressjs/express/blob/master/Security.md#reporting-a-bug
