### ISSUE TITLE
Chrome Canary - ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by infosail** [expressjs/csurf#104]
My node.js using csurf has been working fine for the past two years with the Chrome in publish released channel. Recently someone using a Chrome Canary 64 bit reported a "ForbiddenError: invalid csrf token" error. I also verify using Canary v56.0.2901.0 canary (64-bit). The normal Chrome still works fine. The error still persists even though I upgraded csurf from 1.5.0 to 1.9.0. 

Pls see my JS file in the zip.
[snippet.zip](https://github.com/expressjs/csurf/files/555075/snippet.zip)

I can see the GET /MyPath call succeeds with a CSRF token, e.g. QpFWupct-TC9UxAtFIVqaixGV7RP8t0ewfXQ, passed in the response X-CSRF-Token header. And the POST /MyPath  request is sent with the same token value.

I trace the index.js file.

``` js
   if (!ignoreMethod[req.method] && !tokens.verify(secret, value(req))) {
      return next(createError(403, 'invalid csrf token', {
        code: 'EBADCSRFTOKEN'
      }))
    }
```

The value(req) was exactly the token value. The secret was 6ONFoNkOQa0-kr8hM9Z4ZzWS for that token. Due to the error, the app.post handler is not called.

For normal Chrome, the token and secret were 4HEABAEb-lrMBfOGbuioBfboBSTJOgwecT3M and 8WYg3HfShoVUg8ybufZlF9RS respectively. Why csurf is peculiar with Canary? Thanks.

**Comment by dougwilson** [comment]
> Why csurf is peculiar with Canary?

Weird, and I have no idea. I can't imagine a different Chrome would make any difference unless that Chrome is buggy in some way.

**Comment by gabeio** [comment]
That chrome can be buggy the name Canary literally is used because it's taken from the bird they would take into mines to see if there wasn't enough oxygen, since they need more than humans to live when the bird died it was time to run, same thing here if something breaks well don't ship it lol

https://www.chromium.org/getting-involved/dev-channel#TOC-How-do-I-choose-which-channel-to-use-

> Because there's no guarantee that it will even run in some cases

**Comment by dougwilson** [comment]
I'm going to close this since we haven't heard anything further and there isn't enough information to look into the issue.
