### ISSUE TITLE
Document protection against sibling sub-domain attacks?

### ISSUE THREAD

**Issue by coxd** [expressjs/csurf#106]
Based on the current implementation if you use unsigned cookies and use the default validation (or any validation that relies on query parameters) it appears you are vulnerable to attack via sibling sub-domains. If you're domain is `foo.bar.com` a sibling sub-domain could set a competing cookie with a domain of `.bar.com` with their own secret and salt in it and then submit a form with a matching token. Based on jshttp/cookie's implementation it appears first one wins and in my read of [RFC6265](https://tools.ietf.org/html/rfc6265) it does not appear that any particular order is guaranteed or recommended in regards to specificity of sub-domains.

Assuming my understanding is correct, based on this it seems appropriate to recommend configuring cookie-parser to use signing in the readme to prevent this attack vector.

Caveat: I have not done any research into the real-world state of affairs for cookie ordering when a there are competing cookies between a parent and child sub-domain.

**Comment by dougwilson** [comment]
Please report potential vulnerabilities via email so there is not an email with attack details sitting around when no one is around a computer to address anything
