### ISSUE TITLE
invalid csrf token // cookie secure: true

### ISSUE THREAD

**Issue by tomek121** [expressjs/csurf#107]
Why Csurf is not working for post routes when cookie secure: true is enabled? For the same code when I set secure: false it works correctly. I am using simple example with submit form.

```
   app.use(require("express-session")({
        secret: " Test",
        key: "sessionId",
        resave: false,
        saveUninitialized: false,
          cookie: {
            proxy: true, 
            expires: expiryDate,
            httpOnly: true,  //not allow client side script access to the cookie 
              secure: true //only send this cookie in requests going to HTTPS endpoints
  }
```

```
 app.get('/', function (req, res) {
    res.render("start_page",{loggedUser:req.user, csrfToken: req.csrfToken()});
    });

    app.post("/login", passport.authenticate("local",{
        successRedirect: "/",
        failureRedirect: "/"
        }),function(req,res){
            console.log(req);
        }
    );
```

**Comment by dougwilson** [comment]
There is no way to tell unless you can provide all the following information:

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Exact version of every single other module you are using in your app.
4. The full source code of your app so I can run it.
5. Specific instructions on how to run your app and reproduce the issue.

**Comment by tomek121** [comment]
I am using newest version of all components: 

Server:
```

var express = require('express'),
    bodyParser =    require("body-parser"),
    flash = require('connect-flash'),
    app = express(), 
    User = require("./models/user"),
    mongoose = require("mongoose"),
    passport = require("passport"),
    LocalStrategy = require("passport-local"),
    path = require('path'),
    formidable = require('formidable'),
    fs = require('fs'),
    csrf = require('csurf');
    //cookieParser = require('cookie-parser');

    mongoose.connect("mongodb://localhost/test");
    mongoose.Promise = global.Promise;

    passport.use(new LocalStrategy(User.authenticate()));
    passport.serializeUser(User.serializeUser());
    passport.deserializeUser(User.deserializeUser());
    app.use(bodyParser.json());

    app.use(bodyParser.urlencoded({ extended: true }));

    app.use(flash());
    app.set("view engine","ejs");
    app.use(express.static(__dirname));

    
    var expiryDate = new Date(Date.now() + 30 * 1000);

    //Passport configuration------------------------Start


    app.use(require("express-session")({
        secret: " Test",
        key: "sessionId",
        resave: false,
        saveUninitialized: false,
          cookie: {
            proxy: true, 
            expires: expiryDate,
            httpOnly: true,  //not allow client side script access to the cookie 
              secure: true //only send this cookie in requests going to HTTPS endpoints
  }
        
    }));

    app.use(passport.initialize());
    app.use(passport.session());
    // app.use(function(req,res,next){ //validation if user is logged in
    //     res.locals.loggedUser = req.user;
    //     next();
    // });
    
    app.use(csrf());

    app.use(function(req, res, next) {  //CSURF-------------START
      res.locals._csrf = req.csrfToken(); //csrf token validation
      console.log("csrf:" + req.csrfToken());
      next();
    });
   

    app.get('/', function (req, res) {
    res.render("start_page",{loggedUser:req.user, csrfToken: req.csrfToken()});
    });

    app.post("/login", passport.authenticate("local",{
        successRedirect: "/",
        failureRedirect: "/"
        }),function(req,res){
            console.log(req);
        }
    );

    app.listen(process.env.PORT, process.env.IP, function(){
        console.log("dziala2");
    });

```

Form existing in '/' route (I am using express):

    <form action ="/login" method = "POST" class="navbar-form navbar-left" role="search">
      <input type="hidden" name="_csrf" value = <%= csrfToken %>>
      
      <div style="padding-left:1px !important">
              <button type="submit" style = "background: transparent;" id="navbut" class="btn btn-primary btn-sm">Log in</button>        
    </div>
   </form>

**Comment by dougwilson** [comment]
So the app you provided is running over HTTP and not HTTPS, so if you set secure:true then yea, it wouldn't work since express-session would not even set the cookie on the response.

Even then, it sounds like you are having cookie issue if that setting makes a difference to you, and you are using the express-session module to manage that, so it's possible asking in that module may be a better place? Otherwise I can agree with what you are seeing, which is due to running the server over HTTP instead of HTTPS.

**Comment by tomek121** [comment]
Thank you for your answer. Can you please explain me more what can I do to improve this code?

**Comment by tomek121** [comment]
Which one method is much safer? Storing the token in the session (server) or in cookie (client)?

**Comment by dougwilson** [comment]
Hi @tomek121 sorry I lost track of this issue. I just wrote up an answer to a similar question in #108 which I hope helps :) !
