### ISSUE TITLE
Ajax token

### ISSUE THREAD

**Issue by tomek121** [expressjs/csurf#109]
Hello,

I have a little problem when I am doing AJAX post.

My Ajax configuration: 

```
    $.ajaxSetup({
        headers: {'X-CSRF-Token': $("#_csrf").attr("value")}
    });
```
My ajax functions:

```
function deletefile(x){
$.ajax({
                                          url: '/delete',
                                          type: 'POST',
                                          data: {filenameanddirectory:x1},
                                          success: function(data){....}
       
     });}
```
```
function uploadphotoF(x) {
$.ajax({
                                          url: '/upload',
                                          type: 'POST',
                                          data: {filenameanddirectory:x1},
                                          success: function(data){....}
       
     });}
```

As you see I am using two routes to upload and delete file. When I am uploading files it works correctly as ajax setup has proper token. When I want to delete the file (second route is being called without reloading the page) then I have an error invalid token. 

The question is if there is any solution for that. I know that in callback of ajax I can change the field which stores token value on each ajax call but is it safe?

**Comment by wangchao95** [comment]
Same question here, the token on the server changed after ajax post method fired and the token redered by the templete got expired.

Now I have to change ajax to refresh or redirect to keep it works, any better ideas?

**Comment by wangchao95** [comment]
I guess the "delete" one is a CORS request and the other isn't.If you are not using CSP, you can try add this in your "delete" ajax settings:    
```
xhrFields: {
      withCredentials: true
},
```
This would allow CORS ajax request sending with your cookie.
Then check your server config, make sure ```Access-Control-Allow-Origin``` is not ```'*'``` and ```Access-Control-Allow-Credentials``` is ```'true'```

The reason you get an invalid token is the token is changed by new request which is not sent with cookie.

**Comment by dougwilson** [comment]
Hi @tomek121 without understanding a lot more about the nature of your requests or full client-side and server-side code, it's hard to say what is going on in your app. I'm going to go ahead and close this, though, since there hasn't been any response since @wangchao95 suggestion.

**Comment by george-norris-salesforce** [comment]
why not just add documentation on using this lib with Ajax?
