### ISSUE TITLE
csrfProtection on GET request

### ISSUE THREAD

**Issue by c0debreaker** [expressjs/csurf#114]
Is it possible? Or is it only applicable to POST method?

**Comment by dougwilson** [comment]
Yep, just pass in a different value for the `ignoreMethods` option https://github.com/expressjs/csurf#ignoremethods

**Comment by dougwilson** [comment]
And here is an old issue that has an example that will probably help with how to use: https://github.com/expressjs/csurf/pull/29#issuecomment-55922866

**Comment by c0debreaker** [comment]
Thanks!

**Comment by c0debreaker** [comment]
I just tried adding it to my GET endpoint. It's now failing with ` ForbiddenError: invalid csrf token `

```
router.route('/sessioncount')
  .get(csrf({ ignoreMethods: [] }), (req, res, next) => {
    sess = req.session;
    if (sess.authenticated) {
      if (sess.views) {
        sess.views++;
        res.setHeader('Content-Type', 'text/html');
        res.write('<p>Session views: ' + sess.views + '</p>');
        res.end();
      } else {
        sess.views = 1;
        res.end('Welcome, you are logged in!');
      }
    } else {
      res.setHeader('Content-Type', 'text/html');
      res.write('<p>You are not allowed to view this page. Please <a href="/api/form">log in</a></p>');
      res.end();
    }
  })
```

**Comment by dougwilson** [comment]
Are you passing the CSRF token to the page on the GET? If so, how are you doing it?

**Comment by c0debreaker** [comment]
I see it in the request cookie headers

**Comment by dougwilson** [comment]
Well, the cookie is not the token. The purpose of CSRF is to protect against the attacks where cookies are automatically included. The way CSRF protection works is like two factor auth: you need two pieces of information to validate, the cookie with the secret and the token manually placed in the request itself.

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF) has a lot of detail on how exactly this works.

**Comment by c0debreaker** [comment]
That means, I have to extract the _csrf token from the cookie and pass it back to my api server? Thanks for the link, I'll read it up.

**Comment by dougwilson** [comment]
It depends. This module never sets the token in a cookie; only the secret which is different. The token needs to be included in your response in a way that the 3rd parties cannot read.

**Comment by c0debreaker** [comment]
Ok. Can you please give me one example of how to submit a GET request containing a csrf token?

**Comment by c0debreaker** [comment]
I tried the following GET request but it didn't work, all failed. I got the token from the same login form I got authenticated
```
http://localhost:31337/api/sessioncount?csrf=qudszjrT-mQ5uu4qXrQXI7C_NJYlXXUIdKB0

http://localhost:31337/api/sessioncount?_csrf=qudszjrT-mQ5uu4qXrQXI7C_NJYlXXUIdKB0

http://localhost:31337/api/sessioncount?csrfToken=qudszjrT-mQ5uu4qXrQXI7C_NJYlXXUIdKB0
```

**Comment by dougwilson** [comment]
The `http://localhost:31337/api/sessioncount?_csrf={token}` is the correct format, assuming you didn't pass in a `value` function in the options :) The only reason by default it wouldn't work is that that token is not valid for the secret on that request. I can help, but without being able to debug I'm not sure what exactly is happening. Can you provide all the following:

1. The version of this module you're using.
2. The version of Node.js you're using.
3. Complete code for everything I need to run and reproduce the issue. If this uses other module, please be sure to include all the versions of those you're using so I can install the same ones.
4. Complete instructions on how to run the app and then instructions on how to reproduce the issue.

Thanks!

**Comment by c0debreaker** [comment]
Cool. Will do

**Comment by c0debreaker** [comment]
csurf 1.9.0
Node v6.9.1

**Comment by c0debreaker** [comment]
index.js - https://gist.github.com/c0debreaker/46ce60802cfc80bb20d972035f72e614
auth.js - https://gist.github.com/c0debreaker/85bda8b4538bce28648e11ef21f2b04a

**Comment by c0debreaker** [comment]
I think it's working now after I changed
// const csrfProtection = csrf({ cookie: true });

to

// const csrfProtection = csrf();

**Comment by c0debreaker** [comment]
I've restarted my node app multiple times and it's working great. I'm not sure though what we're missing without `{ cookie: true }`

**Comment by dougwilson** [comment]
You're not missing anything without `{ cookie: true }`. From https://github.com/expressjs/csurf#cookie

> Determines if the token secret for the user should be stored in a cookie or in req.session. Defaults to false.
