### ISSUE TITLE
How to seed the token in the client without forms?

### ISSUE THREAD

**Issue by aflext** [expressjs/csurf#115]
I use text input and ajax with cookie.
My understanding is as belows:
The server will generate a secret and store it each page request in the server(stored where?) and seed a token in the client(seed in cookie?), when the client make a ajax calls, the server checks if the token of the client matched the secret stored before.

So,my question is:
1.  Where does the code
```js
app.use(function(req, res, next) {
    res.cookie('XSRF-TOKEN', req.csrfToken());
    next();
});
```
store the secret ?
2. How do i validate the token and the secret each request or the code above has done it already?
3. What need i do if i don't want to use forms with hidden input ?

**Comment by dougwilson** [comment]
Hi @aflext I think there are a few confusions here. This module only generates a single secret per session. It will be stored in `req.session` or in a cookie if you set `cookie: true` (only needed if you don't use sessions). The _token_ is what would be generated per-request, as the return value of `req.csrfToken()`. The _token_ is what you send with each request for validation.

The code you provided above is not enough information. To answer where the secret is stored, I would need to see the complete app code (remember it defaults to in `req.session`, so maybe that will answer the question for you).

The token is validated automatically for all requests except GET, HEAD, and OPTIONS. The token is validated at the spot where you did the `app.use` of this module.

I don't know what you mean by your last question. You may want to stop by the general Express support forum for help on that: https://gitter.im/expressjs/express

**Comment by aflext** [comment]
@dougwilson Thanks a lot for ur explanation.
I would like to start validation once my app runs for some request apis.If i use `cookie: true`,i need do followings:
1.  `cookie: true`, this will generate a secret for current cookie whose cookie name may like `csrf_secret`.
2.  Generate token for each request of `html`:
```
app.use(function(req, res, next) {
    if (!req.url.match(/addItem|deleteItem|changeItem$/)) {
       next();
       return;
   }
    res.cookie('XSRF-TOKEN', req.csrfToken());
    next();
});
```
The page has two cookies: a `csrf_secret`-named secret and a 'XSRF-TOKEN'-named token at this time.
3. When i do some post request like `delete` in current page, the request header has the two cookies above of current page and will automatically send it  to server for validation ?

**Comment by dougwilson** [comment]
> When i do some post request like  delete  in current page, the request header has the two cookies above of current page and will automatically send it to server for validation ?

No, because that would defeat the entire purpose of CSRF. The token has to be in some aspect of the request in which the browser does not automatically add it, like in the body.
