### ISSUE TITLE
Is this expected, csurf token works on another browser?

### ISSUE THREAD

**Issue by c0debreaker** [expressjs/csurf#116]
I logged in on Chrome. I also logged in on Firefox. I have a /gettoken endpoint that generates and returns a csrf token. I called this endpoint in Chrome but I used the token in Firefox. The csrf token worked. It didn't say Forbidden invalid csrf token. Is this normal?

```js
router.route('/gettoken')
.get(csrfProtection, function(req,res) {
  res.json({ csrfToken: req.csrfToken() });
})
```

**Comment by dougwilson** [comment]
It shouldn't, but would need more information to determine what is happening. If you have a PR to fix, that is the best route forward, otherwise I need enough information to reproduce the issue.

Using the example on the readme does not reproduce for me.

**Comment by dougwilson** [comment]
I'm going to close this issue since I never got a response back.
