### ISSUE TITLE
Socket.io Integration: Checking the token

### ISSUE THREAD

**Issue by dschnare** [expressjs/csurf#122]
Not sure if this is related to #14, but when I call `req.csrfToken()` and send that to my view, it's value is completely different than the value that's in the cookie. If it helps I'm setting `?_csrf=${csrfToken}` as a query param during a Websocket UPGRADE request. Figured this would work with socket.io. Perhaps I'm doing this all wrong/this isn't meant to protect Websocket connections.

Has anyone tried using this module to protect a socket.io connection request?

**Comment by dschnare** [comment]
Also, I've set `cookie: true` for the `csurf` options. And for a high-level overview of what I'm doing:

1) Before rendering a React tree on the server I call `req.csrfToken()` and pass that down into the tree (so it can be used)

2) In the logic within one of my components I'm connecting to my socket.io server and I'm specifying the path for that connection something like this: 
```
io.connect(undefined, { path: '/app/socket.io?_csrf={csrfToken}' })
```

**Comment by dougwilson** [comment]
That's because per the docs, the cookie contains the csrf secret and the  req.csrfToken()  returns a new token derived from that secret. They are supposed to be different.

Hope this helps clarify. No logic in your apps should ever be examining the cookie value.

**Comment by dougwilson** [comment]
I have never used socket.io, so not really familiar with any specifics around how the two modules would integrate together. If you want to contribute some docs around this subject we can add to the readme, that would be awesome!

**Comment by dschnare** [comment]
Ok, that explains why they're different, but why do I get an error when csurf attempts to verify the token? I haven't written any code to do anything, just letting csurf do it's thing, but it's not working as expected (*could* be related to socket.io, but I can confirm the COOKIE header is indeed intact and has the secret).

Section from my app stack:
```
.use(bodyParser.json())
.use(bodyParser.urlencoded({ extended: true }))
.use(cookieParser('254e073'))
.use(csurf({
    ignoreMethods: [ 'GET', 'HEAD', 'OPTIONS' ],
    cookie: { path: '/', key: '_csrf', signed: true, sameSite: true, httpOnly: true }
})
```

With regards to socket.io, as far as I can tell this module *should* just work. csurf is getting invoked when the UPGRADE request is being received and I know the cookie headers are there in the request. If I figure out what's going on I'll report back.

**Comment by dougwilson** [comment]
Weird. I can definitely try to debug it. It would be awesome if you could provide all the following so I can debug:

1. Version of Node.js
2. Version of this module.
3. The full, complete source code that is having issues. I need to run the same thing because you'd be very surprised how many times a slimmed down example works but the full doesn't; debugging something different than what you are running just leads to not being able to reproduce.
4. The complete instructions for how to make the sequence of requests to your code that results in the issue.

Thanks!

**Comment by dschnare** [comment]
I've figured it out. I was specifying the path with query params incorrectly.
```
const socket = io(undefiend, { path: '/app/socket.io?_csrf=' + csrfToken })
```
Should have been:
```
const socket = io(undefiend, { path: '/app/socket.io', query: '_csrf=' + csrfToken })
```
Now it works as expected. I'm adding CSRF protection for the websocket endpoint so that I can protect/make it harder for someone to connect to the server from anywhere else but the app server.

By the way, I ended up getting my React subtree to render:
```
<input type='hidden' value={csrfToken} id='js-csrf' />
```
Then in my logic that connects to the socket server I just do this:
```
const csrfToken = (document.getElementById('js-csrf') || {}).value
const query = csrfToken ? `_csrf=${csrfToken}` : ''
// Establish a Socket.io connection to the server
// (passing params) See: https://stackoverflow.com/a/25085538/908171
const socket = io(undefined, { path: '/app/socket.io', query })
```
@dougwilson thanks for you quick feedback. I would have likely been chasing a yak not knowing that the cookie actually contained the secret and not the token.

**Comment by dschnare** [comment]
Actually inspecting this further, socket.io appears to listen for connections at a lower level so it circumvents any express middleware entirely. Too bad, thought I had it solved.

**Comment by dougwilson** [comment]
Ah, so I assume that means it was working because the token was just not being validated at all?

**Comment by dschnare** [comment]
Yeah, so I added custom logic for socket.io to make it work when csurf is using cookies to save the secret. For now this will due.

**Comment by dougwilson** [comment]
Makes sense, thanks for the follow up!

**Comment by DataTables** [comment]
This is an old one, so apologies for necro-ing this issue, but it's the first hit on ddg for "express csrf socket", so in case anyone else finds this useful: this is how I've implemented it using this module (note that it won't work for cookie's just session storage):

```
const csrf = csurf();
...

	let ret = false;

	// This is a bit of a hack, but want to use the same csurf module as the http server and it
	// has its own way of storing the secret and token. So we need to implement objects that look like:
	// 1. Express request object (bits that are needed)
	// 2. Express response object (not used)
	// 3. Callback function to check for errors
	csrf({
			headers: {},
			query: socket.handshake.query,
			session: socket.handshake.session
		} as any,
		{} as any,
		(err: any) => {
			if (err) {
				socket.send('Failed CSRF');
				socket.disconnect();

				log.warn(err.code === 'EBADCSRFTOKEN'
					? 'Failed CSRF check - invalid token'
					: 'Failed CSRF check'
				);
			}
			else {
				ret = true;
			}
		}
	);

	return ret;
```
