### ISSUE TITLE
Handle Errors Using Simple Example

### ISSUE THREAD

**Issue by rcosgrave** [expressjs/csurf#125]
Hello I am using csurf to protect a couple of forms on my Node App. I noticed you have 

```
app.use(function (err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err)

  // handle CSRF token errors here
  res.status(403)
  res.send('form tampered with')
})
```

For an example of catching errors with the `app.use` implementation but I have yet to find a way to catch these errors using your simple example. The page dies with `ForbiddenError: invalid csrf token` and shows the call stack (not ideal).

Here is how I am processing my form submission

`app.route('/login').post(csrfProtection, (request, response, next) => UserController.handleLogin(request, response, next));`

I apologize if this is simple to catch; kinda new to Node :)

Thanks in Advance!

**Comment by dougwilson** [comment]
Hi @rcosgrave I double-checked using the example app and it caught the error just fine. There may very well be something wrong in your app, and would love to help, but would need a copy of your source code.

**Comment by rcosgrave** [comment]
I would rather not give the source code if possible? It is a fairly big app file but if needed I could prune it and send it on over.

Here is the stack trace?

```
ForbiddenError: invalid csrf token
    at csrf (/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at next (/node_modules/express/lib/router/route.js:131:14)
    at next (/node_modules/express/lib/router/route.js:131:14)
    at next (/node_modules/express/lib/router/route.js:131:14)
    at next (/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at session (/node_modules/express-session/index.js:454:7)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:317:13)
    at /node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/node_modules/body-parser/lib/types/json.js:94:7)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:317:13)
    at /node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at /node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/node_modules/raw-body/index.js:262:16)
    at done (/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/node_modules/raw-body/index.js:307:7)
```

**Comment by dougwilson** [comment]
Absolutely feel free to prune it, as long as pruning it keep it runnable (so I can run it with a debugger) and that is still has the issue. Unfortunately the stack trace is meaningless in this case, as it simply shows were the error was created, not why you are unable to customize it after it was made.

**Comment by rcosgrave** [comment]
Gotcha ok, doubt I'll be able to get to it today though FYI.
Thanks again!


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Douglas Wilson <notifications@github.com> Date: 7/14/17  4:11 PM  (GMT-05:00) To: expressjs/csurf <csurf@noreply.github.com> Cc: Raymond Cosgrave <racosgrave@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [expressjs/csurf] Handle Errors Using Simple Example (#125) 
Absolutely feel free to prune it, as long as pruning it keep it runnable (so I can run it with a debugger) and that is still has the issue. Unfortunately the stack trace is meaningless in this case, as it simply shows were the error was created, not why you are unable to customize it after it was made.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/expressjs/csurf","title":"expressjs/csurf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/expressjs/csurf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dougwilson in #125: Absolutely feel free to prune it, as long as pruning it keep it runnable (so I can run it with a debugger) and that is still has the issue. Unfortunately the stack trace is meaningless in this case, as it simply shows were the error was created, not why you are unable to customize it after it was made."}],"action":{"name":"View Issue","url":"https://github.com/expressjs/csurf/issues/125#issuecomment-315455850"}}}

**Comment by dougwilson** [comment]
Sounds good, take as long as you need :) Usually I don't even close an issue until over 1-2 months of inactivity, and even then can always re-open, haha.

**Comment by rcosgrave** [comment]
Just wanted to follow up on this; I was able to get `app.use` to work correctly while having csrfProtection as middleware for certain routes.

I noticed that if I placed the code near the end of my `app.js` _after all the routes are declared_ then it works as intended.

So as you suggested...something in the middle of my `app.js` must be messing with it.

```
var csrf = require('csurf');
var csrfProtection = csrf();
//... APP CODE AKA ROUTES
 
// Catch invalid CSRF or pass along
app.use(function(err, req, res, next) {
  if (err && err.code == "EBADCSRFTOKEN") {
    let params = {
      err: "InvalidCSRF"
    };

    if (req.query.redirect) {
      params.redirect = req.query.redirect
    }

    return safeBrowserRedirect(req.url, params, res);
  }
  else if (err){
    next(err);
  }
  else {
    next(req, res);
  }
});

var port = 5000;
app.listen(port, function () {
	debug('Node app listening on port ' + port);
});
// EOF
```
