### ISSUE TITLE
Should the _csrf cookie have the HttpOnly attribute set to true?

### ISSUE THREAD

**Issue by tranpeter** [expressjs/csurf#128]
Shouldn't we set the HttpOnly attribute when creating the _csrf token?

**Comment by dougwilson** [comment]
You can set that yourself for now; the next major version will likely have it set out of the box fot defence in depth, but not having it set does not affect the security of csrf in any way.

I hope this helps!

**Comment by tranpeter** [comment]
Thanks! Let me know how I can help.
