### ISSUE TITLE
Using cookie-parser requires setting cookie option to non-false value?

### ISSUE THREAD

**Issue by tranpeter** [expressjs/csurf#129]
You wrote: 

> If you are setting the "cookie" option to a non-false value, then you must use cookie-parser before this module.

Is the reverse also true? Is this statement also true:

> If you are using a cookie-parser, you must set the "cookie" option to a non-values value.

**Comment by dougwilson** [comment]
No, feel free to use cookie-parser all you want; this module only needs it when you are setting the "cookie" option to a non-false value.

The typical reading of that kind of sentence is that if you don't meet the leading conditional, then the rest of the sentence applies, i.e. you jist axt like tgere was never any mention of that module.

I hope that helps!

**Comment by tranpeter** [comment]
Thanks!
