### ISSUE TITLE
Shouldn't the token be invalid after usage?

### ISSUE THREAD

**Issue by bydga** [expressjs/csurf#130]
Hi,

this is more of a question than a bugrequest. I'm looking into how this module exactly works and I just discovered, that the token (generated by `req.csrfToken()`) can be used multiple times (not even on more pages/forms. Since this module implies a "per-session-based" tokens, I think its fine, that token generated for form A can be used on form B.

However I think the token should be invalidated after a successfull "usage" so it couldnt be used again. Now it seems like all tokens generated by the same (session-stored) secret are always valid.

What do you think? :)

**Comment by dougwilson** [comment]
Hi @bydga expiring on use is not necessary for CSRF protection, which is all this module does.
