### ISSUE TITLE
Random misconfigured csrf and invalid csrf token errors during consecutive requests to the route

### ISSUE THREAD

**Issue by abhyuditbinbill** [expressjs/csurf#131]
I have a weird issue happening.

The code: https://gist.github.com/abhyuditbinbill/d5eaecd02f7cbfd7492cc56612eb531f

When I request logout route or users route multiple times, I always get misconfigured csrf for first couple requests, then I get invalid csrf token. And then the request succeeds.

**Comment by dougwilson** [comment]
Hi! Sorry I didn't see your issue come in. It looks like the code you linked to no longer exists. Do you still need help / what is the code?

**Comment by dougwilson** [comment]
Closing due to no response.
