### ISSUE TITLE
How to ignore CSRF token validation for specific header in req

### ISSUE THREAD

**Issue by senthil5053** [expressjs/csurf#134]
I'm using csurf for CSRF attack prevention in my application. I would need to ignore CSRF check on some request based on the header in the request. 

Tried the following with no luck, 

```
var conditionalCSRF = function (req, res, next) {
  //compute needCSRF here as appropriate based on req.path or whatever
  if (req.headers['my-key']) {
    csrf(req, res, next);
  } else {
    next();
  }
}

app.use(conditionalCSRF);
```
Could someone help here ?

**Comment by dougwilson** [comment]
That should work and a quick app let me send in a request with the header "my-key" without error. Maybe there is something else happening in your app not reflected in the code above? Would you be  able to share the following so I can reproduce your issue to try and help?

1. Version of Node.js
2. Version of this module
3. Complete app code that has the issue you are describing. Should be able to paste it into a file and run without modification
4. An example request that you are expecting to work and what your expecting the result of the request to be

Thanks!

**Comment by senthil5053** [comment]
@dougwilson Thanks. I'm able to resolve this with the following:
`// CSRF error handler
app.use(function (err, req, res, next) {    
    if (err.code !== 'EBADCSRFTOKEN') return next(err);

    // Ignore CSRF check
    if (req.headers['my-key']) return next();

    // Handle CSRF token error
    global.log.error('CSRF Token Validation error', JSON.stringify(err));
    res.status(403).send('form tampered with');
});`

Hope this is Okay. Please let me know if this is not a correct solution

**Comment by dougwilson** [comment]
I assume it's correct if it resolves your issue 👍 Without the information above, I don't understand what the issue is to say one way or the other.
