### ISSUE TITLE
AWS Lambda does not startup with csurf included

### ISSUE THREAD

**Issue by veeaarr** [expressjs/csurf#136]
Lambda node-js application does not startup with csurf included. Is there a pre-compiled binary that can be included to make it work, or if there are scripts to build the binary for Node v6 (Lambda supported) on Linux platform that would be helpful.

If there's any other alternative please let know.

Thanks in advance.

**Comment by dougwilson** [comment]
As far as I know there are no binary components in this module, so not sure what you're looking for.

**Comment by dougwilson** [comment]
Closing due to no response.
