### ISSUE TITLE
Invalid CSRF Token when using API call from VUE.JS

### ISSUE THREAD

**Issue by Quadriphobs1** [expressjs/csurf#141]
I have an app with which the server and the client app is been seperated, the client is based on vue.js and the server is based on express.js

I have set up csurf on the server using the following configuration
`app.js` which is the app entry point
```
const express = require('express')
const cookieParser = require('cookie-parser')
const bodyParser = require('body-parser')
const cors = require('cors')
const app = express()
app.use(morgan('combined'))
app.use(bodyParser.json())
app.use(cors())
app.use(cookieParser())

require('./routes')(app)

app.listen(process.env.PORT || config.port)

```

and in my `routes.js` which contains all the defined route

```
const csrf = require('csurf')
const auth = require('./routes/patient/Authentication')

const csrfProtection = csrf({ cookie: true })

module.exports = (app) => {
  // Send CSRF token for session
  app.get('/api/getcsrftoken', csrfProtection, function (req, res) {
    return res.json({ csrfToken: req.csrfToken() })
  })

  app.use('/auth', auth)
}

```

In the `authentication.js` 

```
const csrf = require('csurf')
const express = require('express')
const router = express.Router()
const csrfProtection = csrf({ cookie: true })

router.post('/register',
  csrfProtection,
  AuthenticationControlerPolicy.register,
  AuthenticationControler.register)
router.post('/email',
  csrfProtection,
  AuthenticationControler.email)

module.exports = router

```

So i can easily get the csrf in the client(vue.js) app using vuex and store it. In my form i passed the value of the csrf token to the form filed with the name `_csrf` from what i can see the csrf token is been set successfully but each time i make a request its getting the invalid csrf token.

What could i be doing wrong.

> Note, i run this in postman on the server, i try to get the csrf and then i include it in my request and it works.

**Comment by dougwilson** [comment]
Hi @Quadriphobs1 the most common issue when everything is going right there (nothing looks wrong in the code) is that your client code is not including the cookie in the POST request back to the server.

**Comment by Quadriphobs1** [comment]
I just note that as well but in my request i have 
```
return Api().post('/auth/email', { email: value, _csrf: value }).then((response) => {
        return {
          valid: response.data.valid,
          data: {
            message: response.data.message
          }
        }
      })
```

**Comment by dougwilson** [comment]
So I don't see anything in that code sending the cookie anywhere, but maybe it's implied? Do you see the `Cookie` header in the POST request?

**Comment by Quadriphobs1** [comment]
I think i might be getting things wrong here, sorry may i ask what you mean by `Cookie` header because i dont seems to think the request is having it in the `Cookie` header.

**Comment by dougwilson** [comment]
When you make a request to the server with this module, the module will send back a `Set-Cookie` header in the response your browser needs to store. When you make future requests back, your browser needs to send back the name and value of that cookie in the `Cookie` header. You can learn more about cookies here: https://en.wikipedia.org/wiki/HTTP_cookie

**Comment by Quadriphobs1** [comment]
So if i am t9 set a cookie in header of the axios request what would be name of the cookie, can i set it to _csrf or do i need an explocit name, i guess it should work if i could set the header in the axios.

**Comment by dougwilson** [comment]
I'm not sure what you mean by t9. The name of the cookie and value needs to be what the server sent back in the `Set-Cookie` response header to your `/api/getcsrftoken` request.

**Comment by Quadriphobs1** [comment]
But since i already have `_csrf` in my request, which when i console.log() in the server i get the values, i dont think i need to set it as header any longer and perhaps its also what i did using postman on that route

```
{
	"email": "john.doe@email.coms",
	"_csrf": "zGLWL844-oSNxoBVLo1BEyL7ybV_OHDmPC2Q"
}
```

**Comment by dougwilson** [comment]
Hi @Quadriphobs1 sorry, I'm not getting emails from GitHub, so I have to check back here periodically to see if you responded. The `_csrf` value you have there is the token, yes, but the server doesn't know who you are without the addition cookie, which is the secret to the token. Without both of those, you cannot authenticate. You're using `cookie: true` in your configuration, which means you need to include the cookies in your requests.

**Comment by dougwilson** [comment]
From documentation (https://github.com/expressjs/csurf#cookie):

> cookie determines if the token secret for the user should be stored in a cookie or in req.session.

Since you have `cookie: true` you need to include the cookie too because it contains the secret to validate the token you are providing in `_csrf`.

**Comment by Quadriphobs1** [comment]
hmmm okay i have been trying to add that to my axios request but the store function is not just giving me the csrf token

```
import axios from 'axios'
import store from '@/store'
export default() => {
  const token = store.state.getters.csrftoken
  return axios.create({
    baseURL: URL',
    timeout: 1000,
    headers: {'X-CSRF-TOKEN': token}
  })
}

```

I guess if i set this for the headers in axios it should work, but if i tried to get the values through vue component, it gets the value and i guess that is because the value is been check using `this.$store.dispatch('getCsrfToken')` so i have been trying to see a way i can dispact store in the axios function to get the token

**Comment by dougwilson** [comment]
So the header `X-CSRF-TOKEN` is just the token, not the cookie with the secret. The name of the header needs to be `Cookie`, with the name value pair you received from the server in the `Set-Cookie` response header. I'm not familiar with axios so have no idea how to accomplish this in axios, unfortunately :(

**Comment by Quadriphobs1** [comment]
And if i am to set the name of the header to cookie that should be :( , can u try to  illustrate how the header should be set for the cookie

**Comment by dougwilson** [comment]
So it's just a standard thing, way more involved than I can write up here. The gist is that you get a `Set-Cookie` header from the server that contains the cookie data (see https://en.wikipedia.org/wiki/HTTP_cookie#Setting_a_cookie on Wikipedia) and then when you make requests back to the server, you need to take that data and construct a `Cookie` header back to the server (see https://en.wikipedia.org/wiki/HTTP_cookie#Setting_a_cookie on Wikipedia).

**Comment by Quadriphobs1** [comment]
@dougwilson if i set the `const csrfProtection = csrf({ cookie: false })` and i have only csrf in my form in vue, i am guessing that should work, what could be the repercussion

**Comment by dougwilson** [comment]
Without doing a full source audit, I cannot comment on the repercussions of some security-related.
