### ISSUE TITLE
using req.headers['csrf-token'] instead of req.body._csrf

### ISSUE THREAD

**Issue by kingleuther** [expressjs/csurf#144]
Hello, 

I would like to ask for an example on how exactly we will be able to use headers instead of req.body.

Here's my code 
GET 

```js
app.get('/view', csrfProtection, function(req, res){
    res.set('csrf-token', req.csrfToken());
    res.render('view.ejs');
});
```
```html
VIEW/FORM
<body>
  <form action="/success" method="POST">
      Favorite color: <input type="text" name="favoriteColor">
      <button type="submit">Submit</button>
  </form>
</body>
```
POST
```js
app.post('/success',csrfProtection,function(req, res){
    res.send( 'Hello there the angel from nightmare');
});
```
Instead of using 
```
<input type="hidden" name="_csrf" value="<%= csrfToken %>"> 
```

can we instead make use of checking the headers? If possible, can you show us how. 

Thank you

**Comment by dougwilson** [comment]
You just need to send the header on the form. How to do this exactly I'm not sure since I don't really do front end, but if you can show me, I can add it to the README :+1:

**Comment by kingleuther** [comment]
That was quick,
I will work on it, I thought it was easy as using get and post. I will check on how to submit headers on the front end. Thanks @dougwilson. I' ll get back to you as soon as I'm done researching on this.

**Comment by dougwilson** [comment]
Great! I have personally just used the body and query since as far as I know currently those are the only two possibilities with HTML forms.

**Comment by kingleuther** [comment]
I see, anyway let me try some possibilities. Maybe we could come up with other way. I am thinking of metadata or ajax. Thank you very much @dougwilson. I'll give you feedback on this later or tomorrow. Godbless.

**Comment by knoxcard** [comment]
FYI, you can also use headers doing this...

$.ajax({
	        url: '/agree-terms-conditions',
	        cached: 'false',
	        data: $(this).serialize(),
	        **headers: {
	           'X-CSRF-Token': jQuery.former['_csrf']
	        },**
	        type: 'POST',
	        dataType: 'json'
		}).done(function(json) {
			if(json.success) {
				jQuery.email = json.email
				login()
			}
		})

**Comment by dougwilson** [comment]
Hi @knoxcard yes, if you use JavaScript to send a HTTP request, you can of course add any header you want like normal. My understanding is how to do this with HTML form, not JavaScript.

**Comment by knoxcard** [comment]
I am sure you cannot just use plain HTML.  If there is, please share it here.

**Comment by dougwilson** [comment]
Right, I'm also pretty sure there is no way as well.
