### ISSUE TITLE
ForbiddenError: invalid csrf token, express js

### ISSUE THREAD

**Issue by chemitaxis** [expressjs/csurf#147]
Hi, I have detected that this error is happening randomly. I thought that the problem was in the load balancer and cookie signed with two web servers, but I have change to one server and the problem persist.

```
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

// Cookie Parser
app.use(cookieParser());

// Make Express use i18n :)
app.use(i18n.init);

// CSRF Protecttion
app.use(csrf({ cookie: true }));
```

Using in my controllers:

```
/**
 * GET /contact
 */
const contactGet = function (req, res) {
  res.render('contact', {
    title: req.__('CONTACT_SLIDE.TITLE'),
    description: res.__('PRICING.DESCRIPTION'),
    csrfToken: req.csrfToken(),
    captcha: req.recaptcha,
    language_selected: req.getLocale(),
    menu_style: 'black'
  });
};
```

And of course, in the form:

`<input type="hidden" name="_csrf" value="{{csrfToken}}" />`

Any ideas? I'm using PM2, and I have two process running in the same machine... it could be this the origin of the problem? I can't reproduce the error, because in my case, always work fine.

Thanks.

**Comment by pauldariye** [comment]
I'm also having this issue.

**Comment by carocad** [comment]
this seems to be related to the iOS 11 update. See [forum entry](https://forums.developer.apple.com/thread/89050). We used their mentioned workarounds to solve it.

Hope it helps

**Comment by Gisleburt** [comment]
Possibly related, I have a different value in the cookie to whats in the form.

**Comment by dougwilson** [comment]
Please open a new issue with full code to reproduce so we can take a look. There isn't enough information that we can act on in this issue.
