### ISSUE TITLE
How token validation works

### ISSUE THREAD

**Issue by motss** [expressjs/csurf#148]
Not sure how the CSRF token validation works. The problem here is the `_csrf` tokens from the cookie and the form are not the same but no error has been thrown. I thought the `_csrf` tokens must match in order to pass the test or something like that.

_Why the `_csrf` token from the browser is different?_

I tried to manipulate the value of the `_csrf` cookie directly in the browser to see if `csurf` checks if the `_csrf` match. Is that something the developer needs to validate the tokens separately?

**index.js**
```ts
// @ts-check

export interface ExtendedRequesst extends Request {
  csrfToken: () => string;
}

import cookieParser from 'cookie-parser';
import csurf from 'csurf';
import express, { Request } from 'express';

const PORT = process.env.PORT || 5353;
const app = express();

app.enable('trust proxy');
app.use(cookieParser());
app.use(express.urlencoded({ extended: true }));
app.use(csurf({ cookie: true }));

app.get('/', async (req: ExtendedRequesst, res, next) => {
  try {
    return res.send(`<!doctype html><html>
      <body>
        <style>
          fieldset {
            margin: 0;
            padding: 0;
            border: none;
          }
        </style>

        <main>
          <form method="POST"
            action="/"
            enctype="application/x-www-urlencoded">
            <div>
              <input type="hidden"
                name="_csrf"
                value="${req.csrfToken()}">
            </div>

            <fieldset>
              <label for="name">
                <span>Name<span>
                <input id="name"
                  type="text"
                  name="name"
                  placeholder="Type your full name">
              </label>
            </fieldset>

            <div>
              <button type="submit">Submit</button>
            </div>
          </form>
        </main>
      </body>
    </html>`);
  } catch (e) {
    return next(e);
  }
});
app.post('/', async (req, res, next) => {
  try {
    return res.send({
      query: req.query,
      headers: req.headers,
      body: req.body,
      params: req.params,
      cookies: req.cookies,
    });
  } catch (e) {
    return next(e);
  }
});

app.use((err, req, res, next) => {
  if (err.code !== 'EBADCSRFTOKEN') {
    return next(err);
  }

  return res.status(403).send({
    type: 'bad_csrf_token',
    message: 'Bad CSRF token',
  });
});

app.listen(PORT, () => {
  console.info(`Express running at port ${PORT}...`);
});
```

**request received from POST / after submitting the form**
```json
{
  "query": {},
  "headers": {
    "host": "localhost:5353",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate",
    "referer": "http://localhost:5353/",
    "content-type": "application/x-www-form-urlencoded",
    "content-length": "56",
    "cookie": "_csrf=haha",
    "dnt": "1",
    "connection": "keep-alive",
    "upgrade-insecure-requests": "1",
    "cache-control": "max-age=0"
  },
  "body": {
    "_csrf": "XRej6FVB-GBu2qyq122P9bzJ5FXfJmwfst_c",
    "name": "John Doe"
  },
  "params": {},
  "cookies": {
    "_csrf": "haha"
  }
}
```

**Comment by dougwilson** [comment]
Hi @motss I assume that the `_csrf` cookie you're referring to is the one that is set when you enable the `cookie` option (https://github.com/expressjs/csurf#cookie). The value of this cookie is _not_ the CSRF token, instead it's the token secret. The cookie option:

> Determines if the token secret for the user should be stored in a cookie or in req.session. Defaults to false.

The actual token you need to submit back comes from the `req.csrfToken()` method and you need to pass the value of that method to the page and then have your page pass it back. This token is validated against the token secret, which you can choose to store either in the client in the `_csrf` cookie or server-side (recommended) in the `req.session` object.

I hope this helps!

**Comment by motss** [comment]
@dougwilson Nice. Got it working for both the session-based and cookie-based token secret. The main difference between the two is that session-based requires the server to manage the token secret whereas cooke-based requires token secret to be stored on the user's browser and uses that to validate the csrf token.

**Comment by dougwilson** [comment]
Right. The cookie-based one is easier to setup, since you don't have to setup server-side session storage.
