### ISSUE TITLE
How to use _csrf token in REST api?

### ISSUE THREAD

**Issue by omurbekjk** [expressjs/csurf#151]

**Comment by dougwilson** [comment]
I have never done so since REST API is not typically susceptible to cross origin request forgery attacks. I can definitely add docs if you want to make a PR :+1:

**Comment by omurbekjk** [comment]
Lets say I have an API, when I send post request I will get `csrf invalid token`. Because `body` does not contain `_csrf` token. How should one handle it?

**Comment by dougwilson** [comment]
https://github.com/expressjs/csurf/blob/master/README.md#using-ajax

**Comment by omurbekjk** [comment]
Is it possible to use API without using ajax?

**Comment by dougwilson** [comment]
How do you call your REST API currently?

**Comment by omurbekjk** [comment]
Post request to http://localhost:3000/login 
``` 
body{
username: 'username',
password: 'password'
}
```
If I send post request with `_csrf` token included in `body` it works. I parsed `csrf` token from login page before sending post request.

**Comment by dougwilson** [comment]
Ok. That sounds right. :+1:
