### ISSUE TITLE
_csrf cookie doesn't expire

### ISSUE THREAD

**Issue by ramsundark5** [expressjs/csurf#152]
I'm using cookie-session middleware and csurf. The secret added in _csrf cookie doesn't expire. is this the expected behavior?

**Comment by dougwilson** [comment]
Yes, that is the current design.

**Comment by dougwilson** [comment]
You can read more about how double submit cookies work on the OWASP wiki https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie :+1:
