### ISSUE TITLE
Simple use with cookie fails verify - salt missing

### ISSUE THREAD

**Issue by workin-bob** [expressjs/csurf#153]
**ver:** 1.9.0
A simple use with a cookie fails to verify, as the cookie is set with a raw secret and prior to the salt being prepended to the secret.  The verify then fails, when no dash '-' is detected.
  - note:  I'm using Angular for the GUI, hence the cookie name, but I don't think that matters for this problem.

I would expect the following to work with express.js, and it _almost_ does.
```
const csrf = require('csurf');
app.use(csrf({ cookie: {key: 'XSRF-TOKEN'} }));
```
#### BUG LOCATION
The problem is that setSecret( ) (line 92), which sets the raw secret into a cookie, is called about 7 lines before the salt is added (line 99 - token = tokens.create(secret) ).  This results in the cookie value not having the salt and thus failing to verify.

#### WORKAROUND
Note:  A workaround is to do a bit more in the express.js config.  It works around the bug by expressly setting the cookie in the express config, instead of having csurf do it. I think it'd be best to fix the bug.

Bare bones code snippet of workaround:
```
const csrf = require('csurf');
app.use(csrf());
app.use(function (req, res, next) {
    const cookieName = 'XSRF-TOKEN';
    if ( !req.cookies[cookieName] ) {
        res.cookie(cookieName,req.csrfToken());
    }
    return next();
});
```

**Comment by dougwilson** [comment]
The work-around is not a work-around; that is not you do it. The cookie is supposed to be the salt, not the token. when `cookie` is set, you're using the double-submit cookie pattern for CSRF protection and the client needs to send _both_ the salt and token. The salt is set in the cookie name by this module, and what you need to manage in Angular (as the `XSRF-TOKEN`) is the _token_, not the salt. The token you get from the `req.csrfToken()` method.
