### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by Gracian1** [expressjs/csurf#154]
I am getting invalid csrf token when i assign multipart/form-data on form? how can i solve this issue?

**Comment by dougwilson** [comment]
Hi! Sorry for your troubles. There isn't enough information here for me to determine the issue and suggest a next step.

**Comment by caminhounico** [comment]
@dougwilson  I have the same issue.
When I send a form-data return 403 invalid csrf token error, but if I change to x-www-form-urlencoded the request sounds good.

**Comment by dougwilson** [comment]
I'd love to help, but need additional information. If there was something I could debug and step through I can try to figure out what is happening.

**Comment by dougwilson** [comment]
Closing since I never heard back.
