### ISSUE TITLE
BREACH Attack. What's the status? Cookie token doesn't change at any request?

### ISSUE THREAD

**Issue by frederikhors** [expressjs/csurf#157]
Hi all.

Reading here: https://github.com/pillarjs/understanding-csrf#breach-attack

> BREACH attack
> This is where the salt comes along. The BREACH attack is pretty simple: if the server sends the same or very similar response over HTTPS+gzip multiple times, an attacker could guess the contents of response body (making HTTPS utterly useless). Solution? Make each response a tiny bit different.
> 
> Thus, CSRF tokens are generated on a per-request basis and different every time. But the server needs to know that any token included with a request is valid. Thus:
> 
> Crytographically secure CSRF tokens are now the CSRF "secret", (supposedly) only known by the server.
> CSRF tokens are now a hash of the secret and a salt.
> 
> Defending against the BREACH Attack
> Note that CSRF doesn't solve the BREACH attack, but the module simply randomizes requests to mitigate the BREACH attack for you.
> 
> The salt doesn't have to be cryptographically secure
> Because the client knows the salt!!! The server will send <salt>;<token> and the client will return the same value to the server on a request. The server will then check to make sure <secret>+<salt>=<token>. The salt must be sent with the token, otherwise the server can't verify the authenticity of the token.
> 
> This is the simplest cryptographic method. There are more methods, but they are more complex and not worth the trouble.
> 
> Creating tokens must be fast
> Because they are created on every request! Doing something as simple as Math.random().toString(36).slice(2) is sufficient as well as extremely performant! You don't need OpenSSL to create cryptographically secure tokens on every request.
> 
> The secret doesn't have to be secret
> But it is. If you're using a database-backed session store, the client will never know the secret as it's stored on your DB. If you're using cookie sessions, the secret will be stored as a cookie and sent to the client. Thus, make sure cookie sessions use httpOnly so the client can't read the secret via client-side JavaScript!

Is there any progress on this?

I installed `csurf` and it doesn't change. Maybe because I'm in localhost?

Am I wrong?

**Comment by dougwilson** [comment]
Make security reports privately not publicly.
