### ISSUE TITLE
Is expose CSRF token via an API endpoint secure?

### ISSUE THREAD

**Issue by superbull** [expressjs/csurf#158]
I build an application which contains two parts:
1. REST API server on domain1
2. SPA frontend on domain2

I am going to use cookie to store the access token, so I also want to protect this application against CSRF attack.

Since the frontend is hosted on another domain, I cannot  get the CSRF token in the frontend by print to the html with the value `req.csrfToken()`.

What I can think about is expose an endpoint in the API server like `/csrf-token`, which will return a CSRF token. So that I can get it from the frontend and attach to the header `X-XSRF-TOKEN`.

Is this approach secure?

Or does anyone already has an better solution?

Thanks in advance.

**Comment by dougwilson** [comment]
Sorry I did not respond becaue I don't know the answer to your question. This issue has been open for two months and no one else as responded. A general question may do better on something like Stackoverflow.
