### ISSUE TITLE
How to handle express rest routes with empty path param with csurf returning 404 instead of 403?

### ISSUE THREAD

**Issue by Ks89** [expressjs/csurf#161]
Hello @dougwilson 

I have some apis in express (post, put, get and delete) also with path params.
Some examples:
DELETE /api/users/2376213786213
POST /api/users .   (with a body)
and so on

**I want to use csurf, but I also want to catch when someone call an api with an empty path param and return a 404.
In short, If you call DELETE /api/users/ (with an empty id as path param) I want to return 404, otherwise if you call DELETE /api/users/12121 I want to handle the csrf token and return 403 if not valid.
Is it possible? How?**

I created a middleware to handle csrf like in your example:

```
// error handler
app.use(function (err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err)

  // handle CSRF token errors here
  res.status(403)
  res.send('form tampered with')
})
```
And after this middleware I created another one to handle 404, nothing special.

However, **this api DELETE /api/users/ (with an empty id as path param) is trapped by the first middleware and return 403, instead of 404.**

Thank u

**Comment by Ks89** [comment]
Do you have any suggestions? I'm really the only one with this issue?

**Comment by dougwilson** [comment]
I don't know off hand and it doesn't seem anyone else does. Suggestions are welcome!

**Comment by Ks89** [comment]
Ahaha ok. Please let me know if you have updates about this topic or something to share. Im trying to respect status codes and testing they with super test. So I'm trying to implement all standards. Thank u.

**Comment by dougwilson** [comment]
Gotcha. Yea, I have no ideas. If you have any suggestion for how I can get you an answer, let me know what action I should take and I can reopen, otherwise, if there is no action to take I'm going to close this issue. A site like Stackoverflow may be a good place to ask a question, as here it's pretty much just myself looking at the issues.

**Comment by Ks89** [comment]
Ok thank u.
I created a [new question of stackoverflow](https://stackoverflow.com/questions/52910391/how-to-handle-expressjs-rest-routes-with-empty-path-param-with-csurf-returning-4)
