### ISSUE TITLE
Token validation uses only the request data?

### ISSUE THREAD

**Issue by mihristov** [expressjs/csurf#165]
Hi,

I have a general question about the token validation in this module. Let's say I chose to store the secret in a cookie. As far as I can see you verify the secret that is in the request's cookie against the token that's in the hidden field (which also comes with the request.. E.g. `req.body._csrf`). So if a hacker enters my site and copies both the cookie secret and the token, then uses them in a malicious JS executed anonymously.. these are going to work every time, right?
Am I right, or am I missing something?

Thanks

**Comment by mihristov** [comment]
I guess this is expected and these not much I can do about it, except disable CORS so the hacker is not allowed to execute JS?

**Comment by dougwilson** [comment]
You are correct. This is because CSRF protection is based on the premise that the following is not possible: 

> So if a hacker enters my site and copies both the cookie secret and the token

You can read more about CSRF on the OWASP wiki https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)
