### ISSUE TITLE
CSRF validation fails depending on computer making the request

### ISSUE THREAD

**Issue by takinola** [expressjs/csurf#166]
I created a site that makes an Ajax request to a path with CSRF protection.  However, the request is always successful when I access it from my laptop but always fails when accessed by my client's laptop.  In both cases, we are using the same OS (Mac OS X 10.13.6) and browser (Chrome incognito mode) and the requests are similar 

`body{
 param1: val,
 param2: val,
_csrf: <token>
}`

The server side code is reproduced below

`

      app.use(compression()); // gzips responses
      const defaultPort = 2000;
      app.set('port', process.env.PORT || defaultPort);
      app.set('views', [path.join(__dirname, '..', 'views')]);
      app.set('view engine', 'pug');
      app.use(morgan('dev'));
      app.use(cookieParser(secretStrings.cookieSecret));

      // custom middleware to  make req.rawBody available
      app.use(function(req, res, next){
        req.rawBody = '';
        req.on('data', function(chunk){
            req.rawBody += chunk;
        });

        next();
      });

      // enable access to form content via req.body
      app.use(bodyParser.urlencoded({extended: false, limit: '50mb'}));
      app.use(bodyParser.json({limit: '50mb'}));

      // needs to be before any module that needs to know the method of a request e.g. csurf
      app.use(methodOverride());

      // disable "x-powered-by" header for security
      app.disable("x-powered-by");

      const csrfExcludedRoutes = ['/excluded-routes'];
      app.use((req, res, next)=>{
        let pathMatch = false;  // assume path requires CSRF
        csrfExcludedRoutes.forEach((route)=>{

          if(route === req.path.substr(0, route.length)){
            pathMatch = true;
          }
        })

        pathMatch ? next() : csrf()(req, res, next);
      })

      // middleware to set csrf token to be used in forms
      app.use((req, res, next)=>{
        let pathMatch = false;  // assume path requires CSRF
        csrfExcludedRoutes.forEach((route)=>{
          if(route === req.path.substr(0, route.length)){
            pathMatch = true;
          }
        })

        if(pathMatch){
          next()
        } else {
          res.locals.token = req.csrfToken();
          next();
        }
      })
`

What could be the causes of CSRF validation failing when running the exact same script calling the exact same backend from one computer but not another?  Any clues would be very helpful in helping me troubleshoot the problem.  Thanks

**Comment by dougwilson** [comment]
I have never heard of that issue and have no idea. Perhaps if you can provide complete source code and instructions that reproduces it on the client machine I can try on my machine and see if it's also broken, which would give me something to debug and look at. I don't have Mac OS X so it's dependent on that I'll have to method to reproduce.

**Comment by takinola** [comment]
Not sure how to provide the complete source code as it is a pretty extensive project.  I'll try to reproduce the relevant sections.  Here is the code that generates the Ajax request to the backend


```
  function postSettingsChange(newSettings){
    return new Promise((resolve, reject)=>{
      let payload = [];
      const _csrf = document.getElementById('_csrf').value;
      payload.push('_csrf=' + _csrf);

      const state = displayState.get();
      payload.push('state=' + encodeURIComponent(JSON.stringify(state)));

      payload.push('settings=' + encodeURIComponent(JSON.stringify(newSettings)));
      payload = payload.join('&');

      let request = new XMLHttpRequest();
      const method = 'POST';
      const destination = '/settings';
      request.open(method, destination, true);
      request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
      request.send(payload);

      request.onreadystatechange = function(){
        let message;
        let error = new Error();
        if(request.readyState === XMLHttpRequest.DONE){
          try {
            let response = JSON.parse(request.responseText);
            if(response.error){
              message = {error: 'error saving settings to backend - ' + response.error};
              error.message = message
              return reject(error); 
            }
            return resolve();
          }
          catch(err){
            message = {error: 'error saving settings to backend - ' + err.message};
            error.message = message;
            return reject(error)
          }
        }
      }
    })
  }
```

My initial post contains the server-side code.  I understand this may be very little to go on but I'm just trying to get pointers to potential places to go look at.  Can this be a session issue, corrupt cookies (we're using incognito mode so should not be a problem but idk)?  Any clues just so I can narrow down my search would be helpful.  The client is remote and not technical so I am trying to minimize the "round-trips" in troubleshooting communication.

**Comment by dougwilson** [comment]
A quick tip is to check that the token submitted in the request matches the secret stored in their session.

To debug, I don't need your real source code, just source code that is runnable as-is and will reproduce the issue. If I have to write a bunch of code that is not included, how do I know if it's anywhere close to yours and if my version works, that the issue just isn't in another part of the code that wasn't included?

**Comment by takinola** [comment]
I have checked that the CSRF token being sent back from their machine is the same generated from 
`req.csrfToken()`

How can I check the secret stored in their session?

**Comment by dougwilson** [comment]
How are you storing sessions? I don't see that anywhere is the code provided so far.

**Comment by dougwilson** [comment]
From a high level this is how this module stores the secret if you can translate into however you're doing session storage: https://github.com/expressjs/csurf/blob/master/README.md#sessionkey

**Comment by takinola** [comment]
```
_configureExpressSession(app)

function _configureExpressSession(app, secretStrings){
  return new Promise((resolve, reject)=>{
    
    // redis settings
    const defaultRedisDb = 1  // redis db will be modified by environment variables as needed
    , defaultRedisPort = 6379
    , defaultRedisHost = 'localhost'
    , redisOptions = {
      host: process.env.REDIS_HOST || defaultRedisHost,
      port: parseInt(process.env.REDIS_PORT || defaultRedisPort),
      db: parseInt(process.env.REDIS_DB || defaultRedisDb),
      prefix: secretStrings.redisPrefix
    };

    const sessionStore = new RedisStore(redisOptions);
    
    sessionStore.on('disconnect', function(){
console.log('Redis connection lost...');
    });

    sessionStore.on('connect', function(){
console.log('Redis connection established...');
    });

    // store session data in redis
    app.use(session({
      resave: false,
      saveUninitialized: true,
      store: sessionStore,
      secret: secretStrings.sessionSecret,
    }));

    return resolve({app, secretStrings});
  })
}
```

**Comment by dougwilson** [comment]
So it looks like some module is storing it in Redis. Can you connect to that Redis and look up the value of the csrfSecret property on the client's session?

**Comment by takinola** [comment]
If I changed the line

`pathMatch ? next() : csrf()(req, res, next);`

to 

 `pathMatch ? next() : csrf({cookie: true})(req, res, next);`

this would stop using sessions and use cookies instead, correct?

**Comment by dougwilson** [comment]
That's correct: it changes to store the secret in a separate cookie instead of server-side in the user's session (following the double-submit cookie pattern for CSRF protection).
