### ISSUE TITLE
Is it secure to ignore CSRF validation if no cookies are sent in the request?

### ISSUE THREAD

**Issue by Igor-Lopes** [expressjs/csurf#168]
I use the same API for web and mobile clients. All Mobile clients authenticate with JWT (passport-jwt), while Web clients with cookies (Express Session / passport-local). Since CSRF is a vulnerability related to cookies only, is it secure to ignore CSRF validation if no cookies are sent in the request ?

For example:

```
// Use CSRF Protection
routers.v1.use(csrf({ cookie: true }))

  routers.v1.use((err, req, res, next) => {
   // If no cookies sent, ignore CSRF validation.
    if (!req.cookies['cookie_name.sid']) return next()

  // Other errors 
    if (err.code !== 'EBADCSRFTOKEN') return next(err)

    // handle CSRF token errors here
    res.status(403)
    res.send('form tampered with')
  })
```

**Comment by dougwilson** [comment]
Without fully understanding your app and being able to test it, I really cannot say. Does the OWASP article on CSRF help at all? https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by Igor-Lopes** [comment]
Thanks, I agree with you, without testing the app it's difficult to others to tell either this is secure or not. However, I can briefly explain how it works: I have a hybrid authentication middleware, which checks either for a  Cookie or JWT to authenticate requests. If a client doesn't send a cookie, the middleware will try to validate JWT, and if it fails, returns 401. 

After further reading, I can't see how ignoring such requests can be a security flaw in my app, since CSRF vulnerability only relies on cookies, by gaining access and making unwanted actions. If a client is not sending cookies, it means that it cannot gain access through cookies, and other strategies such as JWTs, are not vulnerable to CSRF, so an attacker could not do the same as it was a cookie. And if it does send a cookie, the CSRF validation will not be ignored, and the cookie will be validated along with it.

I don't know if I could explain better this time. Thank you very much for your time.

**Comment by Igor-Lopes** [comment]
Thanks @dougwilson, also thank you for your amazing work maintaining express  :)

**Comment by dougwilson** [comment]
Np. And yea, forgot to add to the comment above that as long as the session cookie is what you're guarding against and it's not there, then you could let the cross site request come through. If you are doing that additional JWT validation and it is a bearer type of auth (i.e. I bear this token so this is who I am) a different site wouldn't have that token to bear. That's basically with the csrf token is, a bearer type of token.

**Comment by Igor-Lopes** [comment]
I think it's still fine to ignore CSRF Validation for requests without the session cookie, because the JWT validation is not an additional check, but other authentication strategy. So, what actually happens in my app is the first scenario you said.

**Comment by Igor-Lopes** [comment]
I've reproduced the same test from [https://www.twilio.com/blog/2018/01/protect-your-node-js-app-from-cross-site-request-forgery.html](url) , and this approach works as expected for protected routes that uses session cookie or JWT for authentication. However, if there is any action from an unprotected route, the request will still be accepted, since my approach is focused on protected routes that accepts session cookie or JWT for authentication. Assuming that all important actions are protected by authentication middleware, this might not be a problem. So, for my case, I'll validate CSRF only for protected routes using cookies for authentication.
