### ISSUE TITLE
Multipart issue in readme

### ISSUE THREAD

**Issue by ToshKoevoets** [expressjs/csurf#170]
Hi there,

Took me some time to figure out why my form kept getting token invalid. The body is not parsed for multipart request, which makes sense, but it might help to add a small section in the readme: "When validating a multipart request, make sure your csrf middleware is called after parsing the request. + example with Multer"

Might help some people in the future!

Thank you for your work on this module.

**Comment by dougwilson** [comment]
Pull requests welcome!

**Comment by sawyerh** [comment]
Note, if you're sending the request with the token in a header (`X-CSRF-Token`), the ordering of the `csurf` and `multer` middleware doesn't seem to matter.

**Comment by ToshKoevoets** [comment]
That make sense, since it's about the parsing of the body.

Op di 6 nov. 2018 om 15:56 schreef Sawyer Hollenshead <
notifications@github.com>:

**Comment by dougwilson** [comment]
I'm going to close this as it seems no one is interested in helping, and keeping issues open makes people think the module is abandoned, so I'm trying to clean then up. Anyone is still welcome to make a pr with their knowledge to help out future people with similar questions. I have never used multer and don't know how it should be set up to make an example.
