### ISSUE TITLE
How to use csurf when all routes are in separate files?

### ISSUE THREAD

**Issue by Romicusblr** [expressjs/csurf#172]
hello, I want to use csurf protection only in route "/register" and generate token in route "/"

```//server.js
const express = require("express");
const app = express();
const session = require("express-session");
const bodyParser = require("body-parser");
const csrfProtection = require("csurf")();

app.use("/", csrfProtection, require("./routes/landing"));
app.use("/login", require("./routes/login"));
app.use("/forgot", require("./routes/forgot"));
app.use("/register", csrfProtection, require("./routes/register"));
```

this code doesn't work correctly, because checking is performing on all paths instead only "/register". When I use csrfProtection in separate files "./routes/landing" and "./routes/register" it works good. Is there the way to use csrfProtection in only one file server.js? I do not want to duplicate code in routers

**Comment by dougwilson** [comment]
This is because `app.use("/", ...)` will apply that middleware to every request, but every request's URL beings with `/`.
