### ISSUE TITLE
Need docs and examples for working with single page application.

### ISSUE THREAD

**Issue by mrdulin** [expressjs/csurf#174]
For now, the docs give two examples. Both of them are based on server-side render.

The key point is: how to send `csrf` token to front-end domain. 

back-end server will not render a `<form>` or `index.html` page so you can attach `csrf-token` to hidden form field or `<meta>` tag.

We also can't provide a `api` to grab the `csrf-token`.

back-end: http://localhost:3000
front-end: http://localhost:4200 

I search a lot, but still do not find a solution for this case.

**Comment by dougwilson** [comment]
Thanks for the suggestion! I don't have any experience with what you mean, so no idea how to write docs on it. If you could contribute docs on this subject, it would certainly be welcome!

**Comment by mrdulin** [comment]
@dougwilson I got `ForbiddenError: invalid csrf token` on server-side.

This is my front-end request headers:

![image](https://user-images.githubusercontent.com/17866683/48823988-cd9bfa80-ed9d-11e8-8b98-79ce59e0a048.png)

**Comment by Vasanthkesavan** [comment]
I'm also dealing with something similar with angular as frontend. One tool which angular provides is HttpClientXSRF module.

[](https://angular.io/api/common/http/HttpClientXsrfModule)

Your imports should look like:

```javascript 
imports: [
    MaterialModule,
    CommonModule,
    OnboardModule,
    HttpClientModule,
    **HttpClientXsrfModule.withOptions({
      cookieName: 'x-csrf-token',
      headerName: 'x-csrf-token'
    }),**
    FormsModule,
    ReactiveFormsModule,
    RouterModule.forChild(routes),
    StoreModule.forFeature('core', reducers),
    EffectsModule.forFeature(effects)
  ],
```
