### ISSUE TITLE
Invalid csrf token with POST request

### ISSUE THREAD

**Issue by Vasanthkesavan** [expressjs/csurf#176]
```javascript
require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const session = require('express-session');
const csrf = require('csurf');
const jwtDecode = require('jwt-decode');
const cookieParser = require('cookie-parser');
const jwt = require('jsonwebtoken');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const path = require('path');
const cors = require('cors');
const app = express();

app.use(cors());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '../public')));

const limiter = new rateLimit({
  windowMs: 15 * 60 * 1000, // set window to 15 minutes
  max: 100,
  delayMs: 0 // don't require a delay disabled
});

app.use(limiter);
app.use(helmet());

app.use(
  session({
    secret: 'testsecret',
    resave: false,
    saveUninitialized: false,
    cookie: { secure: false, httpOnly: true, maxAge: 3600000 }
  })
);

app.use(cookieParser());

const attachUser = (req, res, next) => {
  const token = req.cookies.token;
  if (!token) {
    return res.status(401).json({ message: 'Authentication invalid' });
  }
  const decodedToken = jwtDecode(token);

  if (!decodedToken) {
    return res
      .status(401)
      .json({ message: 'There was a problem authorizing the request' });
  } else {
    req.user = decodedToken;
    next();
  }
};

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, '../public/index.html'));
});

const checkSession = (req, res, next) => {
  if (req.session.user && req.session.isAuthenticated) {
    next();
  } else {
    res.status(403).json({ message: 'Unauthorized' });
  }
};

// const checkJwt = expressJwt({ secret: process.env.JWT_SECRET });

const checkJwt = (req, res, next) => {
  const token = req.cookies.token;
  if (!token) {
    return res.status(403).json({ message: 'Access denied' });
  }
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET, {
      audience: 'api.spacedust.com',
      issuer: 'api.spacedust.com'
    });

    next();
  } catch (err) {
    return res.status(403).json({ message: 'Access denied' });
  }
};

const makeCsrfToken = (req, res, next) => {
  res.cookie('csrf-token', req.csrfToken());
  next();
};
// ----- Routes Not Requring Auth ------ //
app.use('/api/users', require('./api/users'));
app.use('/api/authenticate', require('./api/authenticate'));
app.use('/api/logout', require('./api/logout'));

// ----- Routes Requring Auth ------ //
app.use(csrf({ cookie: true }));
app.use(makeCsrfToken);
app.use(attachUser);
app.use(checkJwt);

app.get('/api/testget', function (req, res) {
    console.log(req.user);
    res.json({"message": "test get"});
});

app.post('/api/test', function (req, res) {
    console.log(req.user);
    res.json({"message": "test post"});
});

async function connect() {
  try {
    mongoose.Promise = global.Promise;
    await mongoose.connect("process.env.mlab", { useNewUrlParser: true });
  } catch (err) {
    console.log('Mongoose error', err);
  }
  app.listen(process.env.PORT || 3000);
  console.log(`API listening on localhost:3000`);
}

connect();
```
There are three routes which don't require the checks(auth, register, logout). There are two routes which require checks (GET /api/testget and POST /api/test), the get request works as expected but not the post request.

I have been trying to get the POST request working but it fails everytime with the error "Invalid CSRF token".

**Comment by zelongc** [comment]
Hi, The reason you get the error 'Invalid CSRF token' is, the csurf middleware tried to get the csrf token in the header of request but failed. so you will need to send your csrf token through html/cookie (maybe you need to use the header in your case). 

To get a csrf token : ```const token = req.csrfToken()``` Then to put it in the cookie: ```res.cookie('csrf-token', token)```

Then your client side will be able to catch this token (you need to code this function) and send back to the server through the header or in a request body.

**Comment by Vasanthkesavan** [comment]
Hi, the header is set in the request. Please take a look at the screenshot.

<img width="1439" alt="screen shot 2018-12-09 at 7 17 52 pm" src="https://user-images.githubusercontent.com/24874918/49704939-48ab4080-fbe7-11e8-932c-f93999382943.png">

Also, after I authenticate the user everything is detected by the browser and set in the storage properly.

<img width="1204" alt="screen shot 2018-12-09 at 7 17 03 pm" src="https://user-images.githubusercontent.com/24874918/49704945-5fea2e00-fbe7-11e8-8ccb-9198a78216ab.png">

**Comment by zelongc** [comment]
@Vasanthkesavan Oh sorry my bad, I missed that line.

Just looked through your code above again, though not 100% sure, based on what I observed in your routing config, **Only the request falls in the routes after ```app.use(csurf({cookie: true}))``` can be assigned a csrf-token, however, you are checking csrf token here. So there is a chance that you haven't assign the csrfToken but the middleware is doing the csrf check...**

I think this is what's happening to you now:

First, you open the website: http://localhost:3000 -> server doesn't give you csrf-token.
Then you access /api/authenticate endpoint -> server say you login, but still doesn't have a chance to assign the csrftoken header( because of your routing /middleware order)
After this, you trye POST the /api/test -> csurf now has a chance to check the header but you don't have it. It gives you 'Invalid CSRF token'.

Did you try to GET /api/testget and do the POST after this?

Hope this could help you.

**Comment by Vasanthkesavan** [comment]
The GET /api/testget endpoint works correctly and infact any GET request works(after the middleware) except for the POST requests.

I appreciate your quick responses. Thanks @zelongc !

**Comment by dougwilson** [comment]
Hi @Vasanthkesavan GET requests are not checked for the token by default, so by default GET requests will always work.

Is it possible you can provide all the following so we can run your app and try and debug what the issue is here?

1. Version of Node.js
2. Version of this module and all other modules needed to run your code above
3. Instructions for how to run your code above if it's more than copy and paste into `app.js` and run `node app.js`
4. Instructions for how to reproduce the issue with the running app form (3). For example "open web browser to ... click ... etc."

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by Ahsanbaloch** [comment]
can you help me to sort the issue. I have tried your solution but still getting error of { "message": "invalid csrf token" }

Here is the code of serve.js of express
```
require('rootpath')();
const express = require('express');
const app = express();
const helmet = require("helmet");
const bodyParser = require('body-parser');
const csrf = require('csurf')
const cookieParser = require('cookie-parser')

const cors = require('cors');
const errorHandler = require('_middleware/error-handler');

app.use(helmet({ dnsPrefetchControl: { allow: true }}));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use(cookieParser());

app.use(csrf({cookie: {key: 'XSRF-TOKEN'}}))

// app.use('/',  function (req, res) {
//     res.cookie('XSRF-TOKEN', req.csrfToken());
//     // res.render('server')
//   })


app.use(cors({ origin: (origin, callback) => callback(null, true), credentials: true }));



// api routes
app.use('/accounts', require('./accounts/accounts.controller'));

// swagger docs route
app.use('/api-docs', require('_helpers/swagger'));

// global error handler
app.use(errorHandler);

// start server
const port = process.env.NODE_ENV === 'production' ? (process.env.PORT || 80) : 4000;
app.listen(port, () => console.log('Server listening on port ' + port));

```

and the angular code of module.ts is

```
HttpClientXsrfModule.withOptions({
          cookieName: 'XSRF-TOKEN',
          headerName: 'X-XSRF-TOKEN'
        })
```

Currently I am checking output on postman and also on angular but still get no expected output.
