### ISSUE TITLE
about csurf

### ISSUE THREAD

**Issue by xulayen** [expressjs/csurf#177]
My api is request upload a img . so content-type is 'multipart/form-data', then the csurf middleware tips me err.code === 'EBADCSRFTOKEN' , i want to kown,how can i do? @dougwilson

**Comment by dougwilson** [comment]
Hi @xulayen I hope you're aware if if you edit a comment and add an at mention it does not actually notify the person in any way. I just happened upon your issue when looking over the repo.

That said, you need to either send the token in an HTTP header, add a middleware that will extract the multipart/form-data contents into `req.body` like https://github.com/expressjs/multer or provide your own custom function to the `value` option (https://github.com/expressjs/csurf#value) to get the value from the request however you want.
