### ISSUE TITLE
Vue & ExpressJS Csrf Token forbidden 403

### ISSUE THREAD

**Issue by webspecialist** [expressjs/csurf#181]
- axios version: v0.18.0*
- Environment: node v8.9.1, chrome 71.0.3578.98 (Official version) (64-bit), windows 8.1*

I use VueJS (cli 3) & axios, and NodeJS - ExpressJS in the back-end. I am trying to secure my post user edit using CSRF token.

Vue View (edit user - focus to mySubmitEd):

````
<template>
  <div class="one-user">
    <h1>this user</h1>
    <h2>{{name}} - {{surname}} - {{ perm }}</h2>
    <h2>Edit</h2>
    <input type="text" v-model="name">
    <input type="text" v-model="surname">
    <input type="text" v-model="perm">
    <button @click="mySubmitEd">Edit</button>
    <button @click="mySubmit">Delete</button>
  </div>
</template>

<script>
import axios from 'axios'
import io from 'socket.io-client'
export default {
  name: 'one-user',
  data () {
    return {
      name: '',
      surname: '',
      perm: '',
      csrf: '',
      id: this.$route.params.id,
      socket: io('localhost:7000')
    }
  },
  mounted () {
    axios.get('http://localhost:7000/api/get-user/' + this.id)
      .then(res => {
        const data = res.data.user
        this.name = data.name
        this.surname = data.last_name
        this.perm = data.permalink
        this.csrf = res.data.csrfToken
        axios.defaults.headers.common['X-CSRF-TOKEN'] = this.csrf
      })
      .catch(error => console.log(error))
  },
  methods: {
    mySubmit () {
      const formData = {
        _id: this.id
      }
      axios.post('http://localhost:7000/api/delete-user', formData)
        .then(this.$router.push({ name: 'get-user' }))
        .catch(error => console.log(error))
    },
    mySubmitEd () {
      const formData = {
        _id: this.id,
        name: this.name,
        last_name: this.surname,
        permalink: this.perm,
        _csrf: this.csrf
      }
      console.log(formData._csrf)
      axios.post('http://localhost:7000/api/update-user', formData)
        .catch(error => console.log(error))
    }
  }
}
</script>
````

server.js file:

`...
const cookieParser  = require('cookie-parser');
const csurf         = require('csurf');
...
app.use(cookieParser());
const csrfProtection = csurf({ cookie: true });
app.use(csrfProtection);
...`

back-end controller which get the user:

`controller.getOneUser = function(req, res) {
  User.findOne({ _id: req.params.userId }).exec(function(err, user) {
    res.json({user, csrfToken: req.csrfToken()});
  });
};`

My errors in NodeJS-exress console:
`ForbiddenError: invalid csrf token`

My errors in browser:
`POST http://localhost:7000/api/update-user 403 (Forbidden)`

I don't know what is happened because I see in network tab(chrome) the csrf token is the same in the headers and what I send (example):

![csrf](https://user-images.githubusercontent.com/16546251/50763139-a6c75400-1277-11e9-8d10-ba65ca0085cb.jpg)

X-CSRF-TOKEN: PddyOZrf-AdHppP3lMuWA2n7AuD8QWFG3ta0
_csrf: "PddyOZrf-AdHppP3lMuWA2n7AuD8QWFG3ta0"

I don't know what I have miss here. I can't find where is the problem.

If you want more information please asked me to help you. What do you think (what do to for debugging)?

**Comment by spiritson** [comment]
I have the same issue in Chrome, not reproducible in  Safari/Firefox

**Comment by HugoGiraudel** [comment]
We also have a similar problem on our side with Chrome  71.0.3578.98 (Official version) (64-bit). Was not a thing in Chrome 70, and cannot be reproduced in Firefox or Safari.

I have been looking at the changelog of Chrome 71 but could not find anything too obvious.

**Comment by HugoGiraudel** [comment]
We found the problem: when the Chrome DevTools is open, we have CSS/JS sourcemaps enabled. For some reason, one of our dependencies ship their sourcemap (`zenObservable.js.map`) which causes a regeneration of our CSRF token on the server, hence the 403.

**Comment by Tom-Bonnike** [comment]
We fixed by using the `fallthrough` option set to `false` when we call `express.static(…)`.

```js
server.use('/build', express.static('build', { fallthrough: false })
```

If this doesn’t work, you could also simply short-circuit all source map requests if you don’t use them:
```js
const middleware = (request, response, next) => {
  if (request.url.endsWith('.map')) {
    return response.end()
  }

  return next()
}
```

But then maybe you should simply disable the option to use CSS/JS sourcemaps in the Chrome Devtools 😄

**Comment by webspecialist** [comment]
I tried with developer tools close and I get the same error. I think I am not sending the cookie to the server.
When I put **`withcredetials: true`** then I got cors error. 

I don't know what is the `fallthrough` but I will try this tomorrow.

**Comment by Tom-Bonnike** [comment]
You should probably try adding this middleware:

```js
// first middleware
const checkURLMiddleware = (request, response, next) => {
  console.log(request.url);

  return next()
}
```

Just to make sure there’s no superfluous request that goes through the CSRF middleware.

**Comment by webspecialist** [comment]
Those middlwares didn't helped me.

My problem remains

**Comment by webspecialist** [comment]
Finally after a week I solved this issue!

I had to pass in the headers the cookie correctly, so I did 2 corrections:

First in Vue view:

I passed credentials:

`axios.create({withCredentials: true}).get(...)`
and

`axios.create({withCredentials: true}).post(...)`
and secondly in server.js file before routes I put this:

```
...
const corsOptions = {
    origin: 'http://localhost:8080',
    credentials: true,
}
app.use(cors(corsOptions));

app.use(bodyParser.json());
app.use(cookieParser());
const csrfProtection = csurf({ cookie: true });
app.use(csrfProtection);

app.use(function (req, res, next) {
    res.cookie('XSRF-TOKEN', req.csrfToken());     
    res.locals._csrf = req.csrfToken();
    next();
});
...
```

**Comment by dougwilson** [comment]
Hi @webspecialist sorry I have been away. I'm glad you were able to solve your issue 👍
