### ISSUE TITLE
 why app set additional cookie? invalid csrf token

### ISSUE THREAD

**Issue by J4si3k** [expressjs/csurf#182]
I am trying to configure csurf in my express + nuxt.js app. however I get error "ForbiddenError: invalid csrf token" every time
my configuration looks like:
index.js:

```
import express from 'express';
import helmet from 'helmet';
import bodyParser from 'body-parser';
import winston from 'winston';
import logger from './libs/logger';
import responseTime from 'response-time';
import apiRouter from './apiRouter';
import cors from './middlewares/cors';
import { routeError, serverError } from './middlewares/error';
import passport from './libs/passport';
import cookieParser from 'cookie-parser';

const config = require('../config');
const app = express();
passport();

app.use(cookieParser());
app.use(helmet());
app.all('*', cors);
app.use(responseTime());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use('/api', apiRouter);
app.use(logger.sendResponse);
app.use(routeError);
app.use(serverError);

const server = app.listen(8080, () => {
    const serverAddress = server.address();
    winston.info(`Web server listening at port ${serverAddress.port}`);
});
```
apiRouter.js
```
import express from 'express';
import UsersRoute from './routes/users';

const apiRouter = express.Router();

const csrf = require('csurf');
const csrfProtection = csrf({ cookie: true })

apiRouter.get('/v1/token', csrfProtection, async (req, res, next) => {
    
    let csurf = req.csrfToken();
    res.json({
        token: csurf,
    })
})

apiRouter.post('/v1/users/test', csrfProtection, async (req, res, next) => {
            
    res.json({
        success: 'success',
        token: req.body._csrf
    })
})

new UsersRoute(apiRouter);
export default apiRouter;
```
api call:

```
 //.....      
  let response = await this.$axios.get(`/api/v1/token`)
            .then(response => {
                console.log(response);
            })
        
        user._csrf = response.data.token;
        let config = {
            headers: {
                'CSRF-Token': response.data.token
            }
        }

        let { data } = await this.$axios.post(`/api/v1/users/test`, user, config)
```
I think there is a problem with an automatically set cookie that is different from what it generates req.csrfToken (). I do not set it anywhere. How to improve it?

I'm getting token:
<img width="345" alt="req1" src="https://user-images.githubusercontent.com/17933890/52521652-a35e2880-2c7a-11e9-8202-8e32e3aa7fac.png">
and use token
<img width="443" alt="req2" src="https://user-images.githubusercontent.com/17933890/52521653-ac4efa00-2c7a-11e9-8615-d93020de7c2a.png">
of course login data is fake ;-)

Why does the cookie attach automatically? I tested csurf on a different project and there the cookie is not included, and the token passed improvement and everything works. What is going on here???

**Comment by JanuszOsica** [comment]
I was wondering if I did not make a mistake somewhere in my project, that's why I quickly made a new project from scratch, which is available here: https://github.com/JanuszOsica/express-nuxt-csurf

The server implementation is based on another [working project](https://github.com/pwright08/node-express-csurf-example), but unfortunately it did not bring the expected results. Is it not able to operate between different domains? The application frontend works here on the 3000 port, and the backend on 8080.

**Comment by slidenerd** [comment]
I have this exact same issue! Can someone explain why the csrf token is read even before the middleware can execute where you set the token

**Comment by abijotgupta** [comment]
I'm also facing this same issue! Can anyone explain why the csrf token is read from cookies  even before the middleware execute where I set the token using req.csrfToken();
