### ISSUE TITLE
Invalid csrf token with cookies

### ISSUE THREAD

**Issue by adrianpopa97** [expressjs/csurf#184]
I am setting up CSRF prevention on my web app and I have been sitting on this error for a while

I've read a lot of the other questions asking something similar and my code should do the same thing as the solution, but it doesn't work for some reason unknown to me.

This is the way I set up csurf in my router:
```
const bodyParser = require('body-parser');

router.use(bodyParser.urlencoded({ extended: false }));

const cookieParser = require('cookie-parser');

router.use(cookieParser());

const csrf = require('csurf');

router.use(csrf({ cookie: true }));
```

This is the part of the render function which sends the token to the view:
```
csrfToken: req.csrfToken()
```

And this is where the token is used in my form:
```
<input type="hidden" name="_csrf" value="<%= csrfToken %>">
```

The value in the cookie is different than the one in the input, so I get the invalid token error.

UPDATE:
I added the following:
```
router.use(function (req, res, next){
  res.cookie('_csrf', req.csrfToken());
  next();
});
```
And the cookie is equal to the input value, but I still get the same error.

**Comment by dougwilson** [comment]
The cookie should not be the same as your token; the cookie contains the secret, not the token. The token and the secret are two different value that both need to be submitted with the page. See OWAP on double-submit cookies for CSRF: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#double-submit-cookie

**Comment by adrianpopa97** [comment]
I ended up making my own CSRF middleware which works on the same principle as this module. 

I still have no idea why I was getting errors using this one, but I have tested mine and it works well.
