### ISSUE TITLE
BREACH attack mitigation

### ISSUE THREAD

**Issue by techsin** [expressjs/csurf#186]
I don't see any issues regarding lack of support for prevention against BREACH attack. Is it supported?

https://github.com/rails/rails/pull/16570

An implementation that supposedly is a work around that.

**Comment by dougwilson** [comment]
BREACH is already mitigated in this module https://github.com/pillarjs/understanding-csrf/blob/master/README.md#breach-attack

**Comment by techsin** [comment]
Thanks
