### ISSUE TITLE
multer fileFilter error, and csurf

### ISSUE THREAD

**Issue by trogne** [expressjs/csurf#190]
My csrf protection middleware, using "csurf", is configured after multer, as it should (I guess).

If I have an error, for example, in the fileFilter function :
`app.use(multer({ storage: fileStorage, fileFilter: fileFilter }).single('image'));`

Then, it goes straight to the express error-handling middleware :

```
app.use((error, req, res, next) => {
  res.status(500).render('500', {
    pageTitle: 'Error!',
    path: '/500',
    isAuthenticated: req.session.isLoggedIn
  });
});
```

But in the page I render, I use the csrf token defined in a previous middleware, so it's undefined ('invalid csrf token').

How can I then use multer with csurf, for those errors ?

Here's the fileFilter function :

```
const fileFilter = (req, file, cb) => {
  if (
    file.mimetype === 'image/png' ||
    file.mimetype === 'image/jpg' ||
    file.mimetype === 'image/jpeg'
  ) {
    cb(null, true);
  } else {
    cb('INVALID FILE!!!!', false);
  }
};
```

As I said, it is triggered before the request is handled by the csrf middleware, hence the issue.

**Comment by trogne** [comment]
See my answer here : 
https://github.com/expressjs/multer/issues/755

**Comment by trogne** [comment]
See my answer here : 
https://github.com/expressjs/multer/issues/755

**Comment by dougwilson** [comment]
Thanks for the follow up link. I'm not familiar with multer and looks like it is a multer specific solution.
