### ISSUE TITLE
ForbiddenError: invalid csrf token post node js handlebars

### ISSUE THREAD

**Issue by JigneshPatel04** [expressjs/csurf#191]
Hello,
I am using nodejs with handlebars. When I have post the login page then error occurs  **ForbiddenError: invalid csrf token** . I have install package and used in app,js 
```js
const csrfProtection = csrf();
const adminRoutes = require('./routes/admin');

app.use(express.static(path.join(__dirname, 'public')))
app.use(session({
    secret: 'my secret',
    resave: false,
    saveUninitialized: false,
    store: store
}));

app.use(csrfProtection);

app.engine('handlebars', expressHbs({
    defaultLayout: 'main-layout',
}));
app.set('view engine', 'handlebars');

app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(express.static(path.join(__dirname, 'public')));
app.use(
    session({
        secret: 'my secret',
        resave: false,
        saveUninitialized: false,
        store: store
    })
);

app.use((req, res, next) => {
    if (!req.session.user) {
        return next();
    }
    User.findById(req.session.user._id)
        .then(user => {
            req.user = user;
            next();
        })
        .catch(err => console.log(err));
});

app.use(csrfProtection);
app.use((req, res, next) => {
    res.locals.isAuthenticate = req.session.isLogged;
    res.locals.csrfToken = req.csrfToken();
    next();
});

app.use('/admin', adminRoutes);
```

**Comment by owen-m1** [comment]
+1

**Comment by owen-m1** [comment]
My app is passing the exact same token as it received using `req.csrfToken()`  back to the server in the `_csrf` field of the body. I am logging out the token after it's creation and in the API call when it is received in req.body._csrf. They look the exact same, and pasting them into the JS console as strings and checking for equality also shows that they are equal. But every time this API call is made, csurf throws `ForbiddenError: invalid csrf token`.

**Comment by dougwilson** [comment]
Sorry you are having trouble. Would it be possible for either of you to provide a way to reproduce the issue so we can debug though it and figure out what is happening? Otherwise you're always welcome to make a pull request to fix the issue you are seeing.

**Comment by oneso** [comment]
I solved the issue by ordering the middlewares like this:
```
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(csurf({ cookie: true }));
```

**Comment by jonchurch** [comment]
Closing as discussion seems to have fizzled out 👍

**Comment by Darren120** [comment]
OPEN SESEME
