### ISSUE TITLE
Recommendation when ignoring routes

### ISSUE THREAD

**Issue by adam-beck** [expressjs/csurf#192]
In the section describing how to ignore routes it's mentioned (emphasis mine)

> **CSRF checks should only be disabled for requests that you expect to come from outside of your website**. Do not disable CSRF checks for requests that you expect to only come from your website.

Why is that? I'm assuming the rationale is that CORS would prevent an attack. But, from my understanding, that is not enough protection. Taken from SO: https://stackoverflow.com/questions/19793695/does-a-proper-cors-setup-prevent-xsrf

**Comment by dougwilson** [comment]
I'm not sure I understand your question, I'm sorry. This module is just CSRF and nothing to do with CORS, nor does it mention CORS at all anywhere... ?

An example of a "request that you expect to come from outside your website" would be, for example, maybe you have a page that you expect a `<form` to be on an external web site and it would POST directly to yours. Thus it would be something you expect to come from outside in that specific case.

CSRF and CORS are different protection mechanisms.

**Comment by adam-beck** [comment]
Sorry. I'm having a hard time wrapping my head around some of these scenarios. But isn't the whole point of CSRF protection _because_ you don't want external sites to make requests?

If **evil.com** makes a POST request to **mysite.com** is that an "external request"? I would assume yes, but since it isn't _expected_ csurf should be enabled.

> CSRF checks should only be disabled for requests that you **expect** to come from outside of your website.

If you _do_ expect external requests, there isn't really much you can do (from this library's perspective) to filter a request from **friendlysite.com** vs **evil.com**.

**Comment by dougwilson** [comment]
> But isn't the whole point of CSRF protection because you don't want external sites to make requests?

That's correct, which is why that warning is there. There were lots of issues opened for how to ignore it for certain requests, and so it was added, with a warning, to the README to just cut down on the issues opened for how to ignore a route, haha.

> If evil.com makes a POST request to mysite.com is that an "external request"?

Correct.

> but since it isn't expected csurf should be enabled. 

Yep

> If you do expect external requests, there isn't really much you can do (from this library's perspective) to filter a request from friendlysite.com vs evil.com.

That's right, it is outside the scope of the CSRF pattern.

> Also, thank you for the quick help! I truly appreciate all of your work

It's no problem at all. I hope the above helps clarify things!
