### ISSUE TITLE
Forbidden: Invalid CSRF Token error

### ISSUE THREAD

**Issue by kryptonian41** [expressjs/csurf#193]
Even though the tokens are exactly the same, I have made this sure by setting breakpoints and comparing the values.
Even when I use my middleware logic and return the token as string on match, the library throws Forbidden: Invalid CSRF Token

**Comment by BintLopez** [comment]
I'm also experiencing this behavior. For some of my routes the tokens work, but for others, I keep getting `ForbiddenError: invalid csrf token`. I have also sanity checked this by outputting the tokens and inspecting. For some of my POSTs it appears that the _csrf token is never making it into the body? Did you find a workaround?

**Comment by dougwilson** [comment]
Would it be possible for either of you to provide a way to reproduce the issue so we can debug though it and figure out what is happening? Otherwise you're always welcome to make a pull request to fix the issue you are seeing.

**Comment by BintLopez** [comment]
Sure thing! Below are relevant excepts from my app...

## What's happening
I can access and update one resource but not another due to a CSRF ForbiddenError. The following code from `server.js` (more context in 'Code' section below) shows which routes work and which don't.
```javascript
// THE BELOW WORKS
app.get('/account', csrfMiddleware, authHelper.ensureAuth, userController.accountGet);
app.put('/account', parseForm, csrfMiddleware, authHelper.ensureAuth, userController.accountPut);

// THE BELOW THROWS THE <ForbiddenError: invalid csrf token> ERROR
app.get('/orgs/:id', csrfMiddleware, authHelper.ensureAuth, orgController.editOrg);
app.post('/orgs/:id', parseForm, csrfMiddleware, authHelper.ensureAuth, orgController.updateOrg);
```
Note -- the working example here is a put, but there's another post that's working as well.


## Code
- node version 10.15.0

### `package.json`
```JSON"
{
  dependencies": {
    "cookie-parser": "^1.4.3",
    "csurf": "^1.10.0",
    "csv": "^5.1.1",
    "deps": "^0.1.2",
    "dotenv": "^2.0.0",
    "express": "^4.16.4",
    "express-fileupload": "^1.1.1-alpha.1",
    "express-flash": "0.0.2",
    "express-handlebars": "^3.0.0",
    "express-session": "^1.2.1",
    "express-validator": "^5.3.1"
  }
}  
```

### `server.js`
```javascript
// abbreved list of relevant app dependencies
const session = require('express-session');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const csurf = require('csurf');

// controllers
const userController = require('./controllers/user');
const orgController = require('./controllers/org');


app.use(cookieParser(process.env.SESSION_SECRET));
app.use(bodyParser.json());

const parseForm = bodyParser.urlencoded({ extended: false });
app.use(parseForm);

const csrfMiddleware = csurf({ cookie: true });
app.use(csrfMiddleware);

app.use(expressValidator());
app.use(methodOverride('_method'));
app.use(function(req, res, next) {
  res.header('Access-Control-Allow-Credentials', true);
  res.header('Access-Control-Allow-Origin', req.headers.origin);
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
  res.header('Access-Control-Allow-Headers', 'X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept');
    next();
});

app.use(session({
  secret: process.env.SESSION_SECRET,
  resave: false,
  saveUninitialized: true,
  store: new MongoStore({mongooseConnection: mongoose.connection}),
  cookie: {
    domain: '.' + (config.cookieDomain ? config.cookieDomain : config.domain)
  }
}));

// routing
// THE BELOW WORKS
app.get('/account', csrfMiddleware, authHelper.ensureAuth, userController.accountGet);
app.put('/account', parseForm, csrfMiddleware, authHelper.ensureAuth, userController.accountPut);

// THE BELOW THROWS THE <ForbiddenError: invalid csrf token> ERROR
app.get('/orgs/:id', csrfMiddleware, authHelper.ensureAuth, orgController.editOrg);
app.post('/orgs/:id', parseForm, csrfMiddleware, authHelper.ensureAuth, orgController.updateOrg);
```

### `controllers/user.js`
```javascript
/**
 * GET /account
 */
exports.accountGet = function(req, res) {
  console.log('GET THAT ACCOUNT')
  let tokey = req.csrfToken()
  console.log('TOKENNNN', tokey)
  console.log('REQ COOKIES', req.cookies)

  res.render('account/profile', {
    title: 'My Account',
    csrfToken: tokey
  });
};

/**
 * PUT /account
 * Update profile information OR change password.
 */
exports.accountPut = function(req, res, next) {
  console.log('EDIT THAT ACCOUNT')
  console.log('SEA SURF IN BODY?', req.body)
  console.log('REQ COOKIES', req.cookies)  
  // validate and update account
  // this works
};


```

### `controllers/org.js`
```javascript
/**
 * GET /orgs/:id
 */
exports.editOrg = function(req, res) {
  console.log('GET THAT ORG')
  User.findById(req.user.id, function(err, theUser) {
    if(theUser.org == req.params.id) {
      Org.findById(req.params.id, function(err, org) {
        if(!err) {
          let token = req.csrfToken();
          console.log('TOKEN!!!', token)
          // res.cookie('csrf-token', token)
          console.log('REQ COOKIES', req.cookies)
          res.render('org/edit-org', {
            title: 'Organization Settings',
            org: org,
            csrfToken: token
          });
        } else {
          res.status(500);
          res.render('500.handlebars', {title: '500: Server Error'});
        }
      });
    } else {
      res.redirect("/");
    }
  });
};

/**
 * POST /orgs/:id
 */
exports.updateOrg = function(req, res) {
  console.log('DO WE MAKE IT HERE?') // <-- NOPE, the answer is nope.
  console.log('POST TO THAT ORG')
  console.log('SEA SURF IN BODY?', req.body)
  console.log('REQ COOKIES', req.cookies)
  User.findById(req.user.id, function(err, theUser) {
    if(theUser.org == req.params.id) {
      Org.findById(req.params.id, function(err, org) {
        if(!err) {
          // update org
          org.save(function(err) {
            if(!err) {
              res.redirect(`/orgs/${org._id}`);
            } else {
              console.log(err);
              res.status(500);
              res.render('500.handlebars', {title: '500: Server Error'});
            }
          });
        } else {
          console.log(err);
          res.status(500);
          res.render('500.handlebars', {title: '500: Server Error'});
        }
      });
    } else {
      res.redirect("/");
    }
  });
};

```

### `views/org/edit-org.handlebars`
```html
<div id="org-header">
    <div class="container">
        <small>Dashboard</small>
        <h2>{{org.name}}</h2>
        {{>org-nav}}
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="card-body card-padding">
            {{>logo-form}}
            <div class="float-right">{{>org-form}}</div>
        </div>
    </div>
</div>
```

### `views/partials/org-form.handlebars`
```html
<div class="form-wrapper org-mgmt">
    <form role="form" method="POST" encType="multipart/form-data">
        <p>SEA SURF!!!! {{csrfToken}}</p>
        <input type="hidden" name="_csrf" value="{{csrfToken}}">
        <!-- ALL THE ORG ATTRIBUTES -->
        <button type="submit" class="btn btn-primary btn-lg">{{#if org.createdAt}}Save{{else}}Next{{/if}}</button>
    </form>
</div>
```


### `views/account/profile.handlebars`
```html
<form method="POST" action="/account?_method=PUT">
    <input type="hidden" name="_csrf" value="{{csrfToken}}">
    <button type="submit" class="btn btn-success">Update Profile</button>
</form>
```


## Server Logs

### Failed attempt to update Org
```
GET THAT ORG
TOKEN!!! o91cpbuC-zjpNHomFjIkm4bljKkHTAMsODak
REQ COOKIES { _csrf: 'ZLl48Rjvb3pmUWHHNU2v5aRW',
 'csrf-token': 'UaKLMR9R-VCARaNG5I3xO4qVixjMSBxZDwII' }
GET /orgs/5d6474cca67450b1216c9014 200 81.017 ms - -
GET /orgs/5d6474cca67450b1216c9014/logo 200 10.043 ms - 12991
ForbiddenError: invalid csrf token
   at csrf (project/node_modules/csurf/index.js:112:19)
   at Layer.handle [as handle_request] (project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (project/node_modules/express/lib/router/index.js:317:13)
   at project/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (project/node_modules/express/lib/router/index.js:335:12)
   at next (project/node_modules/express/lib/router/index.js:275:10)
   at urlencodedParser (project/node_modules/body-parser/lib/types/urlencoded.js:100:7)
   at Layer.handle [as handle_request] (project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (project/node_modules/express/lib/router/index.js:317:13)
   at project/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (project/node_modules/express/lib/router/index.js:335:12)
   at next (project/node_modules/express/lib/router/index.js:275:10)
   at jsonParser (project/node_modules/body-parser/lib/types/json.js:119:7)
   at Layer.handle [as handle_request] (project/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (project/node_modules/express/lib/router/index.js:317:13)
   at project/node_modules/express/lib/router/index.js:284:7
POST /orgs/5d6474cca67450b1216c9014 500 17.277 ms - -
```


### Successful account details update
```
GET /accounts 302 8.613 ms - 46
GET / 302 3.857 ms - 130
GET /orgs/5d6474cca67450b1216c9014/applications 304 18.986 ms - -
GET THAT ACCOUNT
TOKENNNN 2KdD4n8T-pvCsBalU_adsg93jVy9ljtWhRHE
REQ COOKIES { _csrf: 'ZLl48Rjvb3pmUWHHNU2v5aRW',
 'csrf-token': 'UaKLMR9R-VCARaNG5I3xO4qVixjMSBxZDwII' }
GET /account 200 15.788 ms - -
EDIT THAT ACCOUNT
SEA SURF IN BODY? [Object: null prototype] {
 _csrf: '2KdD4n8T-pvCsBalU_adsg93jVy9ljtWhRHE',
 email: 'stinky@cheesegurus.com',
 name: 'Wheezy? Whee?' }
REQ COOKIES { _csrf: 'ZLl48Rjvb3pmUWHHNU2v5aRW',
 'csrf-token': 'UaKLMR9R-VCARaNG5I3xO4qVixjMSBxZDwII' }
(node:41612) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
PUT /account?_method=PUT 302 108.332 ms - 60
GET THAT ACCOUNT
TOKENNNN dqY6in0V-Jsdpwf9xpqvCPFgLjtOcIrnQ0Ps
REQ COOKIES { _csrf: 'ZLl48Rjvb3pmUWHHNU2v5aRW',
 'csrf-token': 'UaKLMR9R-VCARaNG5I3xO4qVixjMSBxZDwII' }
GET /account 200 13.377 ms - -
```

**Comment by curtiskeisler** [comment]
@BintLopez , I see this line

```
app.use(csrfMiddleware);
```
in `Server.js`.

But, when I look at the documentation:

https://github.com/expressjs/csurf#simple-express-example

I don't see a similar line. In only see the csrfMiddleware being passed in the routes; which you are also doing. Could it be that this line is causing something odd to be happening? Maybe comment it out and see if things work.

Just a guess . . .

**Comment by souzajr** [comment]
I have the exact same error. The problem is with the NodeJS version. Works perfectly on version <10.x, but fails on current stable version 12.13.0

**Comment by BintLopez** [comment]
I figured out what was happening for mine... the forms where the token would not work were `encType="multipart/form-data"`. For multipart forms to work with this package, I needed to ensure that my file parser was loading before the csurf module...

```javascript
// from server.js
app.use(cookieParser(process.env.SESSION_SECRET));
app.use(bodyParser.json());
app.use(fileUpload({
  useTempFiles : true,
  tempFileDir : '/tmp/',
  abortOnLimit: true
}));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(csurf({ cookie: true }));
```

**Comment by gregbown** [comment]
Figured out [how to do this using csurf and multipart/form-data](https://gist.github.com/gregbown/040521b2ab6d549e8ab59184ef942a10)

**Comment by na-n** [comment]
> I have the exact same error. The problem is with the NodeJS version. Works perfectly on version <10.x, but fails on current stable version 12.13.0

Can you back this up? I'm in quite the pickle of Heroku not letting me choose a node version.. 

Has every csrf-depending nodejs website in Heroku just been hit by this??!

**Comment by souzajr** [comment]
Apparently this library looks abandoned. Is there any alternative library?

**Comment by dougwilson** [comment]
@na-n your example request is missing the session cookie, which is why the validation does not work. Since in your set up you have it using the session you set up, there should be a session id in yor cookie, but it is only the xsrf token. Without the session id this module cannot load the secret that belongs to the user. If you don't want to bother with sessions, this module provides the double submit cookie pattern, which is what is used in the examples with `cookie: true`

**Comment by mojodebad** [comment]
hello everyone i was facing the same issue with csurf package  everything in code was right but i was getting forbidden error : invalid csrf token
the thing worked  for me was rearraing the middleware in my app.js file and putting body parser middleware in starting  like this

 `const path = require('path');
const express = require('express');
const bodyParser = require('body-parser');
const session = require("express-session");
const User = require("./models/user");
const csurf = require("csurf");

const mongodbstore = require("connect-mongodb-session")(session);
const store = new mongodbstore({
    uri: "mongodb+srv://Mohit_Jain:Mojodebad133%23@cluster0-bfliw.mongodb.net/test?",
    collection: "sessions",
    connectionOptions: { useUnifiedTopology: true }
});

const errorController = require('./controllers/error');
const mongoConnect = require("./util/database").mongoConnect;


const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');
const authRoutes = require("./routes/auth");
const app = express();


app.use(bodyParser.urlencoded({ extended: false }));
app.use(session({ store: store, secret: "akimichi", cookie: { maxAge: 100000 * 600 }, saveUninitialized: true, resave: false }));
app.use(csurf());

app.set('view engine', 'ejs');
app.set('views', 'views');

app.use(express.static(path.join(__dirname, 'public')));
app.use(async (req, res, next) => {
    if (req.session.user) {
        User.findById(req.session.user._id.toString()).then(user => {
            req.user = new User(user.name, user.email, user.cart, user._id);
            next();
        }).catch(err => { console.log(err) })
    }
    else {
         next();
    }

});

app.use((req,res,next)=>{
    res.locals.authenticated=(req.session.isLoggedIn)?req.session.isLoggedIn:false;
    res.locals.csrfToken=req.csrfToken();
    next();
})
app.use('/admin', adminRoutes);
app.use(shopRoutes);
app.use(authRoutes);
app.use(errorController.get404);


mongoConnect(() => {
    app.listen(3000);
});

`


previously my code was..

`const path = require('path');
const express = require('express');
const bodyParser = require('body-parser');
const session = require("express-session");
const User = require("./models/user");
const csurf = require("csurf");

const mongodbstore = require("connect-mongodb-session")(session);
const store = new mongodbstore({
    uri: "mongodb+srv://Mohit_Jain:Mojodebad133%23@cluster0-bfliw.mongodb.net/test?",
    collection: "sessions",
    connectionOptions: { useUnifiedTopology: true }
});

const errorController = require('./controllers/error');
const mongoConnect = require("./util/database").mongoConnect;


const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');
const authRoutes = require("./routes/auth");
const app = express();
app.use(session({ store: store, secret: "akimichi", cookie: { maxAge: 100000 * 600 }, saveUninitialized: true, resave: false }));
app.use(csurf());

app.set('view engine', 'ejs');
app.set('views', 'views');
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));
app.use(async (req, res, next) => {
    if (req.session.user) {
        User.findById(req.session.user._id.toString()).then(user => {
            req.user = new User(user.name, user.email, user.cart, user._id);
            next();
        }).catch(err => { console.log(err) })
    }
    else {
         next();
    }

});

app.use((req,res,next)=>{
    res.locals.authenticated=(req.session.isLoggedIn)?req.session.isLoggedIn:false;
     res.locals.csrfToken=req.csrfToken();
    next();
})
app.use('/admin', adminRoutes);
app.use(shopRoutes);
app.use(authRoutes);
app.use(errorController.get404);


mongoConnect(() => {
    app.listen(3000);
});

`

**Comment by brianpunzalan** [comment]
this error was showing even though the implementation is correct. This error shows occassionally and failing the client api request. I am using the double submit cookie pattern and it works fine. But there are times that this error was showing.

**Comment by Ahsanbaloch** [comment]
Hi
I am getting error in postman 
{
    "message": "invalid csrf token"
}
but in header it shows cookie like

cookie      _csrf=MMPB8hZxCJmp7KCPmMKJLD_s

Here is my code of express.js
```
require('rootpath')();
const express = require('express');
const app = express();
const helmet = require("helmet");
const bodyParser = require('body-parser');
const csrf = require('csurf')
const cookieParser = require('cookie-parser')

const cors = require('cors');
const errorHandler = require('_middleware/error-handler');

app.use(helmet({ dnsPrefetchControl: { allow: true }}));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());




app.use(cookieParser());
app.use(csrf({ cookie: true }))

app.use(cors({ origin: (origin, callback) => callback(null, true), credentials: true }));

app.all('*', function (req, res) {
    res.cookie('XSRF-TOKEN', req.csrfToken());
    // res.render('server')
  })

// api routes
app.use('/accounts', require('./accounts/accounts.controller'));

// swagger docs route
app.use('/api-docs', require('_helpers/swagger'));

// global error handler
app.use(errorHandler);

// start server
const port = process.env.NODE_ENV === 'production' ? (process.env.PORT || 80) : 4000;
app.listen(port, () => console.log('Server listening on port ' + port));
```

In app.module.ts file of angular I have also added

```
HttpClientXsrfModule.withOptions({
          cookieName: 'XSRF-TOKEN',
          headerName: 'X-XSRF-TOKEN'
        })
```

Kindly help me to sort the issue
