### ISSUE TITLE
cookies are disable

### ISSUE THREAD

**Issue by paragkulkarni** [expressjs/csurf#199]
If cookies are disable in the browser, it is possible to implement csrf. Is it necessary to make cookies are enable for csrf? When cookies are disable in the browser, it gives back invalid csrf token forbidden error. Please suggest me.

**Comment by dougwilson** [comment]
This module does not implement a method that doesn't require a cookie, and I'm not familiar with a method to prevent csrf without one. If you know of one, please let us know :)
