### ISSUE TITLE
Invalid token error in client

### ISSUE THREAD

**Issue by YoungJInzz** [expressjs/csurf#203]
```
router.get("/getCSRF", csrfProtection, function(req, res) {
  res.cookie("XSRF-TOKEN", req.csrfToken());
  res.json({ "XSRF-TOKEN": req.csrfToken() });
});

router.post("/process", parseForm, csrfProtection, function(req, res) {
  res.send("data is being processed");
});
```
This is my server code

```
const token = await fetch(`http://${process.env.url}:3000/getCSRF`, {
      method: "GET",
      credentials: "include",
      headers: {
        "Content-Type": "application/json"
      }
    });
    let x = await token.json()
```
This is my client code

When I tried to get a csrf-token using Postman, I got a valid token("data is being processed")).
But When I tried using client and tested,I got a error message("Invalid csrf token")

What should I do for this issue?

**Comment by dougwilson** [comment]
Postman worked because it is properly saving and remitting cookies set by the server. If your other client is not working,  you'll want to consult with the user manuals for it to determine how to enable cookies on it.
