### ISSUE TITLE
`Invalid CSRF Token` error for some browsers, mostly for iOS Safari

### ISSUE THREAD

**Issue by just4fun** [expressjs/csurf#207]
Hi there,

My node app (express) has been integrated with `csurf` library for a long time, since our app has no login feature, while we want to protect our forms from spam.

We used cookie for `csurf`.

However, from our monitoring tools and logs, we noticed there are some 403 errors raised from `csurf`, then I tried to add some logs, finally I got some clues.

These are logs I added into `csurf` source code.

![image](https://user-images.githubusercontent.com/7512625/75432433-5cc49480-5989-11ea-9ce6-dc4702428eb0.png)

These are logs I added before we reach API.

![image](https://user-images.githubusercontent.com/7512625/75432668-b9c04a80-5989-11ea-9875-e07b1caf0f69.png)

These are logs I added into custom error handling method.

![image](https://user-images.githubusercontent.com/7512625/75432816-f8ee9b80-5989-11ea-8e94-f507229083c5.png)

In short words, the purpose of the logs above is that when there is 403 error, 

1. Screenshot one: I'd like to know what is the `token` and `secret` generated by `csurf` library.
2. Screenshot two: I'd like to know what is the `token` and `secret` passed from UI request. (`token` comes from meta tag I injected from `req.csrfToken()`, `secret` comes from cookie which `csurf` injected)
3. Screenshot three: I'd like to know whether there is `secret`, and what's the browser users using.

So, if there is no 403 error, the logs should be

![image](https://user-images.githubusercontent.com/7512625/75437291-f6437480-5990-11ea-9f51-f8b7ad11b44a.png)

![image](https://user-images.githubusercontent.com/7512625/75437492-3c98d380-5991-11ea-9bc0-32b6aa876fd4.png)

But I saw there were less 403 errors, the logs are

![image](https://user-images.githubusercontent.com/7512625/75438133-6acae300-5992-11ea-92d4-9743051f501c.png)

I checked all 403 error cases, all of them came from iPhone Safari.

![image](https://user-images.githubusercontent.com/7512625/75439034-03159780-5994-11ea-816c-f3d68ea3c902.png)

So I think the root cause is, when create new `secret`, we will store it into cookie with `res.setHeader('set-cookie', header)`. Maybe it has browser compatibility issue? from https://caniuse.com/#search=set-cookie, the compatibility to iOS Safari is only available > 13.2. But from screenshot above, the first error case is from iOS 13.3.1.

For code example, please check https://github.com/just4fun/cra-node-boilerplate/tree/invalid-csrf-token-issue
For online demo, please check https://cra-node-boilerplate.herokuapp.com/

BTW, with my own iOS devices, the online demo above never face 403 error.

Any ideas? maybe change `cookie` to `express-session`?

Thanks.

**Comment by ymaz** [comment]
hey @just4fun, can you please provide little bit more details how do you setup initial `XSRF-TOKEN` cookie and with which params (domain, secure, etc) when you're serving `index.html`?

Also, are you running your app on some subdomain?

Thanks,

**Comment by just4fun** [comment]
Hi @ymaz , you can find all my code [here](https://github.com/just4fun/cra-node-boilerplate/blob/invalid-csrf-token-issue/index.js), just a demo which is same with my real project. In that file, you can see I only set cookie to true like `const csrfProtection = csrf({ cookie: true });`, didn't pass any other options.

BTW, in our prod, yes, our app is running in sub domain. `www.mycompanyname.com` is our company's official website, while our app is serving at `subdomain.mycompanyname.com`. Moveover, we have reverse proxy, it will redirect users from subdomain to a heroku app. Thanks.

**Comment by ymaz** [comment]
@just4fun can you try to do
```
app.use(csrf({ cookie: true }))
```
after 

```
app.use(cookieParser());
```

**Comment by just4fun** [comment]
@ymaz I didn't use `app.use(csrf({ cookie: true }))` directly, you can check my [code](https://github.com/just4fun/cra-node-boilerplate/blob/invalid-csrf-token-issue/index.js#L10-L13), first I declare `const csrfProtection = csrf({ cookie: true });`, then I call `app.use(cookieParser());`, finally I do `app.get('/', csrfProtection, getRenderedIndexFile);` and `app.post('/', csrfProtection, ...)`.

**Comment by jonchurch** [comment]
Just checking in @just4fun  :wave: , was this ever resolved?

**Comment by just4fun** [comment]
Hi @jonchurch - I will check logs for last two months this weekend, and let you know result then, thanks for your understanding.

**Comment by just4fun** [comment]
@jonchurch - the issue is still existing, from logs, I can also see there are some failed requests every day due to invalid CSRF token in last two months. Currently when this kind of issue happens, I displayed a popup to notice users to refresh browser (to get new token) then try again. From my investigation in first post of this thread, I'm thinking in some cases `set-cookie` is not working.

**Comment by dougwilson** [comment]
I am just following up here on this older issue. I haven't seen any offer for a fix, if there is indeed something to fix in this module. I don't have access to any Apple devices to help test, either, so I'm not sure if there is anything further that can be done from the POV of the module's authors. If there is, indeed, something we can help with, the specific next steps should be provided and we can re-open.

**Comment by weirdyang** [comment]
I'm facing the same issue with iOS devices. Let me know what info I can provide to help troubleshoot.
