### ISSUE TITLE
NextJS, React and express js: invalid csrf token

### ISSUE THREAD

**Issue by th3edo** [expressjs/csurf#208]
Hello!
I'm new in ExpressJS world, so I don't know it very well.
So, I have a frontend built with **NextJS** and a backend built with **expressjs**. Now, I understood that the `csrf({cookie: true})` (the cookie) is referred to the secret key.
I need the "real" **csrfToken** in the client-side and to do that I created a GET request like this:

```javascript
app.get('/csrf', (req, res, next) => {
    return res.json({_csrf: req.csrfToken()});
});
```

This simple /csrf returns the csrfToken generated for the client-side. 
In NextJS I can create the [_app.js](https://nextjs.org/docs/advanced-features/custom-app) file that "works" for all pages. 

In this file I've the request to the _/csrf_ page:
```javascript
await axios.get(`${API_URL}csrf`).then((res) => {
    nookies.set(ctx, "csrftoken", res.data._csrf);
 });
```
My client has a cookie called "csrftoken" with the value returned from /csrf call.

I've a _LoginPage_, and in the `componentDidMount()` ([doc](https://it.reactjs.org/docs/react-component.html#componentdidmount)) method I do a POST request to my API.

This is the request:
```javascript
axios.defaults.headers['xsrf-token'] = cookies.csrftoken;
const t = await axios.post(`${API_URL}test`, {}, {
    withCredentials: true,
});
```
This is the result in the developer console
![image](https://i.gyazo.com/fd2ae76fbaaa94cd566ad48e5814019b.png)

When I do that in the backend I've "_invalid csrf token_" and so a 403 as response.
Actually my backend is this:
```javascript
let express = require("express");
let helmet = require('helmet');
let csrf = require('csurf'); //  csrf injection https://www.npmjs.com/package/csurf
let qs = require('qs');
let bodyParser = require('body-parser');
let cookieParser = require('cookie-parser');
let app = express();


app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost:3000"); // update to match the domain you will make the request from
    res.header("Access-Control-Allow-Headers", "content-type, xsrf-token");
    res.header("Access-Control-Allow-Credentials", true);
    next();
});

app.use(bodyParser.urlencoded({extended: true}));
app.use(cookieParser());
app.use(helmet());
app.disable('x-powered-by'); //
app.use(csrf({ cookie: true }));


app.use((req, res, next) => {
    console.log(req.headers, req.cookies, req.path, req.method, req.headers.cookies);
    res.cookie('XSRF-TOKEN', req.csrfToken());
    next();
});

app.get('/csrf', (req, res, next) => {
    //return res.json({_csrf: req.csrfToken()});
    return res.json({_csrf: req.csrfToken()});
});


app.post('/test', (req, res, next) => {
    console.log("test");
    return res.json('hello');
})

//app.use(require("./app/routes"));

let server = app.listen(3001, () => {
    console.log("Server startato.");
});
```

And the output of the `console.log(...)` in the middleware is:
![image2](https://i.gyazo.com/659e5a157d1ad56e1127ae240e9806e3.png)

Some idea on how to fix this? 
Thank you!

P.s: node version 13.11.0

**Comment by LucaNerlich** [comment]
@aedoardo you closed this issue. Did you find a solution? Ive got the same problem.

**Comment by rossPatton** [comment]
just adding to this. all of a sudden my app is throwing csrf errors, even after reverting. it's driving me nuts!

**Comment by prem-io** [comment]
Any solution for this issue??

**Comment by Jscripter-pk** [comment]
> just adding to this. all of a sudden my app is throwing csrf errors, even after reverting. it's driving me nuts!

Hi @rossPatton I am facing the same issue like you have faced all of a sudden I started seeing this error in my app. If you were able to solve the issue can you tell us how?

**Comment by tirmey** [comment]
I found this issue too, all of  a suden, around 2 months ago.

The weird thing: 

Same appication, cloned from github repository: in my laltop I can´t login (code 403 - EBADCSRFTOKEN), in my desktop, the expected behaviour, with absolutely no problems.
