### ISSUE TITLE
Protect route which exposes the credentials via ajax

### ISSUE THREAD

**Issue by alex-w0** [expressjs/csurf#209]
I've two applications (server/client) that are running on different domains.
The server has two different endpoints /csrfToken and /register like the following:

```
router.get('/csrfToken', csrfProtection, async (req, res, next) => {
  res.json({ token: req.csrfToken() });
});
 
router.post(
  '/register',
  csrfProtection,
  async (req, res, next) => {
    return res.send('user registered');
  }
);
```
At the beginning the client has to send a request to /csrfToken, which will return the relevant token and cookie. After that he can send another request to /register with the previously received credentials, which will finally register the user.

Is there a way to protect the endpoint /csrfToken from unauthorized access? At the moment everyone can make a request to it to get the relevant credentials.

**Comment by dougwilson** [comment]
This question seems beyond the scope of this module, as it sounds like you have set it up in a way where you want to use something other than csrf to protect a route you created. Perhaps username and password, not sure.

I would suggest posting this general question on something like Stackoverflow :+1:

**Comment by alex-w0** [comment]
Ok, alright. The problem is that this is a public route where no user is logged in, so I can't authenticate it that way.

**Comment by dougwilson** [comment]
Right. So then how would it be possible to protect such a route?

**Comment by alex-w0** [comment]
I think i will use this middleware plugin to protect the route against overuse https://www.npmjs.com/package/express-rate-limit

Do you recommend to use csurf and express-rate-limit together to protect my route or should be express-rate-limit sufficient?

**Comment by dougwilson** [comment]
Well, I don't know enough about your router to understand which is better. They seem to be pretty different types of protections: this module protects against cross-site request forgery while the rate limit module protects you against too frequent requests.

**Comment by alex-w0** [comment]
Well, the better option would be of course to protect my route directly against unauthorized access with this module. But as soon as I'm creating a own endpoint for getting the token, everyone else will have access to, which most likely cannot be avoided.
I will think about it and let you know if I came up with a better solution.
