### ISSUE TITLE
Do I need to set the header with the token?

### ISSUE THREAD

**Issue by mrkchang** [expressjs/csurf#210]
Hi,

Is it possible for the csrf middleware to parse the header cookie automatically instead of me having to manually change the header?

Thanks,

**Comment by dougwilson** [comment]
By default, this module will automatically parse the header if set to one of the default names: https://github.com/expressjs/csurf/blob/master/README.md#value

**Comment by mrkchang** [comment]
Doug, I know that I can set it as a header for parsing. But why not have the module automatically parse the cookie without me having to set the header?

**Comment by dougwilson** [comment]
I'm not sure I understand your question... if the token is in a cookie value, that defeats csrf, as web browser automatically send cookies, which is the issue csrf is trying to prevent from occurring.
