### ISSUE TITLE
How to do cross-origin requests

### ISSUE THREAD

**Issue by nicholaswmin** [expressjs/csurf#216]
## Our setup.

We have a UI server which runs on `foo.com` which only servers the static assets of the UI.
The UI includes forms which send `POST` requests via Ajax to a REST API running at `bar.com`.

We have control of both `foo.com` and `bar.com`. It's such the architecture of our app that we split the application in 2 servers, a UI server and a "DB/API" server.

Is it possible to use this module in such a setup? If yes, how?

This is what I currently do, but it's not working, throwing a `ForbiddenError: invalid csrf token`.

## `ui-server.js`

```js
'use strict'

const express = require('express')
const ejs = require('ejs')

const app = express()

app.set('view engine', 'ejs')

app.get('/form', (req, res) => {
  res.render('form')
})

app.listen(5000, e => {
  console.log('Listening 5000')
})
```

### `api-server.js`

```js
'use strict'

const cookieParser = require('cookie-parser')
const csrf = require('csurf')
const cors = require('cors')
const express = require('express')

const csrfProtection = csrf({ cookie: true })
const app = express()

app.use(cookieParser())
app.use(cors({
  credentials: true,
  origin: 'http://localhost:5000'
}))

app.get('/csrf-token', csrfProtection, (req, res) => {
  res.json({
    csrfToken: req.csrfToken()
  })
})

app.post('/process', csrfProtection, (req, res) => {
  console.log('submitted')
  res.json({
    result: 'data is being processed'
  })
})

app.listen(5010, e => {
  console.log('Listening 5010')
})
```

**Comment by dougwilson** [comment]
The purpose of CSRF protection is to _prevent_ cross-site requests. This module has no use in your set up, as you _want_ to make cross-site requests :)
