### ISSUE TITLE
Usage with native mobile app?

### ISSUE THREAD

**Issue by abcd-ca** [expressjs/csurf#218]
1. Do I need csurf protection in my express REST API when a native mobile app is accessing it? 
2. If yes to #1, what is a secure way to provide the native client with the token? I can't do it via the page meta tag because the native app doesn't load a page or hit the `/` route. I am using `express-session` and the default csurf config which sets `cookie: false`. I could create a GET route that returns the token in the body but is that secure? Would it be secure if the GET route were guarded by needing user to have logged in first and so a session holding the userid would need to exist before it would be allowed to send the token in the response?

Thank you!

**Comment by davidmashe** [comment]
This seems more like an http / APi design question, not an issue with `csurf`. Closing for now, can re-open if a `csruf` defect can be demonstrated
