### ISSUE TITLE
New token secret with every request

### ISSUE THREAD

**Issue by Elliot128** [expressjs/csurf#220]
I'm running this in a lambda access through api gateway. Every request is producing a new token secret on the _csrf cookie. As a result, every request is giving me an invalid csrf token error.

```
import { Router } from 'express';

import csurf from 'csurf';

const router = Router();

router.route('/callback').get(
  (req, res, next) => {
    return csurf({
      cookie: { secure: true, httpOnly: true, sameSite: 'strict' },
      ignoreMethods: [],
    })(req, res, next);
  },
);

```

**Comment by dougwilson** [comment]
Hm, strange. It should only be providing back a new value if the client is not sending the `_csrf` cookie to the server with the request. Can you check if your request contains a `Cookie` HTTP header and that is has a `_csrf=` in there?

**Comment by Elliot128** [comment]
Thanks for the quick response. I checked the cookies and you were correct, the browser is not sending any cookie headers for some reason. 

Will comment back when I get find my issue in case others run into this as well.

**Comment by Elliot128** [comment]
So my issue was using the `strict` `sameSite` policy for the cookie. This route was being hit by a ouath redirect. As a result, the browser recognized the request as coming from a different domain. Relaxing the `sameSite` policy to `lax` resolved the issue. Thanks again for the quick response.
