### ISSUE TITLE
cookie options for HttpOnly & Secure

### ISSUE THREAD

**Issue by jmalkan** [expressjs/csurf#221]
I would like to set _csrf & 'XSRF-TOKEN' cookies HttpOnly & Secure conditionally based on the request.protocol.
I can do that easily for 'XSRF-TOKEN' as it is done as follows

`
app.use(function(req, res, next) {
  const secureFlag = req.protocol === 'https' ? true : false;
  res.cookie('XSRF-TOKEN', req.csrfToken(), {httpOnly: secureFlag, secure: secureFlag});
  ....
}
`
however I am not sure how to do this for _csrf as
`app.use(csrf({cookie: {httpOnly: secureFlag, secure: secureFlag}}));`

I'd appreciate If anyone can point me to how to do this.

**Comment by dougwilson** [comment]
Options to middleware constructors are meant to be static, and your use-case is perhaps not fully described. If the reason you are doing that is for development vs production, the recommendation is to alter your settings based on that, for example:
```js
if (isDev()) {
  app.use(csrf({cookie: {httpOnly: false, secure: flase}}))
} else {
  app.use(csrf({cookie: {httpOnly: true, secure: true}}))
}
```

If you actually want to switch configs for a middleware based on an aspect of the request, the method can look many different ways, perhaps for your use-case the following (I believe there are modules on npm that makes this easier as well):
```js
const csrfMiddleware = {
  http: csrf({cookie: {httpOnly: false, secure: flase}}),
  https: csrf({cookie: {httpOnly: true, secure: true}})
}
app.use((req, res, next) => csrfMiddleware[req.protocol](req, res, next))
```

**Comment by jmalkan** [comment]
thanks for the solutions. My apologies for the confusion for not clearly static my use case.
My use case is I need to configure csrf Middleware based on the protocol (HTTP vs HTTPS)
So in this case option 2 above would work better.

**Comment by davidmashe** [comment]
it seems like the question is answered, so closing issue. Can re-open if more is needed.
