### ISSUE TITLE
Cookie value is not set properly.

### ISSUE THREAD

**Issue by mgallion** [expressjs/csurf#223]
Testing csrf value generation & protection - the session with express model seems to work as expected (values contain both salt/value from token.create from csrf lib) but the cookie generation (using token.secretSync from csrf lib) does not properly create a csrf value.  I see a proper csrf value from the /form route, but the cookie set is a malformed value.

Did something change with the csrf, token or uid library that is keeping the cookie from salting and being verified properly?  I'll continue digging and look for a PR that will fix the cookie methodology.  

*Server*
```
 const cookieParser = require('cookie-parser')
 var csrf = require('csurf')
 var bodyParser = require('body-parser')
 const express = require('express')
 const path = require('path')

 // setup route middlewares
 var csrfProtection = csrf({ cookie: true })
 var parseForm = bodyParser.urlencoded({ extended: false })

 // create express app
 var app = express()

 app.listen('3000', () => console.log('app running on 3000.'));

 // parse cookies
 // we need this because "cookie" is true in csrfProtection
 app.use(cookieParser())

 app.get('/', (req, res) => res.sendFile(path.join(__dirname + '/index.html')));

 app.get('/form', csrfProtection, function (req, res) {
   // pass the csrfToken to the view
   res.send({ csrfToken: req.csrfToken() })
 })

 app.post('/process', parseForm, csrfProtection, function (req, res) {
   res.send('data is being processed')
 })
```

*Front End*

```
 <html>
     <head>
     <script>
         fetch('/form').then(response => response.json()).then(data => window.csrfToken = data.csrfToken);
     </script>
     </head>
     <body>
         <form action="/process" method="POST">
         <input type="hidden" name="_csrf" value="window.csrfToken">

         Favorite color: <input type="text" name="favoriteColor">
         <button type="submit">Submit</button>
         </form>
     </body>
 </html>
```

**Comment by dougwilson** [comment]
> I see a proper csrf value from the /form route, but the cookie set is a malformed value.

The value in the cookie is not the CSRF token, it is the token secret:

> Determines if the token secret for the user should be stored in a cookie or in req.session. Storing the token secret in a cookie implements the double submit cookie pattern.

The value from `req.csrfToken()` is the actual CSRF token.

The reason your above code does not work is because `<input type="hidden" name="_csrf" value="window.csrfToken">` is setting the submitted value to the literal `window.csrfToken`, which is not a valid token:

![image](https://user-images.githubusercontent.com/67512/92246487-d1760f80-ee93-11ea-9b8a-51010a5ed91b.png)
