### ISSUE TITLE
Which mitigation pattern does this module use?

### ISSUE THREAD

**Issue by antonsamper** [expressjs/csurf#224]
There is a link on the README to the [Cross-Site Request Forgery Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html) page.

This is really useful but  it describes 4 token based mitigation techniques:
- Use Built-In Or Existing CSRF Implementations for CSRF Protection
- Synchronizer Token Pattern
- Encryption based Token Pattern
- HMAC Based Token Pattern

What pattern does this module use?

**Comment by dougwilson** [comment]
That doc is written from the perspective of what you, as a user, would do. Thus it would qualify as the first one on that list, as you would thus be using the built in feature we are providing as part of Express.
