### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by SorinGFS** [expressjs/csurf#225]
I lost a lot of time trying to get this middleware working. I had to go through the issues that others had faced before, until I reached the #118 where @dougwilson says: "**_csrf cookie is the token secret, not the token**"

Then I analyzed the reason of this confusion:

the readme file says:
The default value is a function that reads the token from the following locations, in order:
    req.body.**_csrf** - typically generated by the body-parser module.
    req.query.**_csrf** - a built-in from Express.js to read from the URL query string

That `_csrf` has exactly the same name as the cookie sent with default settings! Since those two variables are built in they cannot be changed, but the default cookie name can! For now, I will use 

    csrfProtection = csurf({ cookie: { key: '_csrs' } }

since the `csrf` name itself is wrong! The `f` stands for `forgery`! I think we try to avoid it! So, `csrs` can be remembered as `cross site request signature`, or `cross site request secret`. Anyway, I think the default cookie name should be changed!

**Comment by dougwilson** [comment]
This would of course be itself a large breaking change. If you can propose better wording in the readme, that would be better. The cookie name is just to indicate that it has to do with csrf functionality, same with the incoming form fields. Perhaps in a future version or even a fork someone can add "token" after the csrf fields that represent tokens and "secret" after those that tepresent secrets.

The names of all of those can be freely changed today using the module's options if you would like to add the work token to the tokens and the word secrer to the secrets of course :)

Perhaps if I had written this module I would have done differently, but I don't think the churn with the massive number of projects dependent on this module is worth changing the name.

**Comment by SorinGFS** [comment]
@dougwilson For this particular case I don't see a problem for changing the cookie name. Maybe I'm wrong, but I don't see how dependent libraries can be affected, I imagine that cookie name is used only by this middleware!

**Comment by dougwilson** [comment]
The cookie would already be set in folk's web browsers with the previous name. The very first sentence under the "cookie" option makes it clear the value is the token secret, not the token itself.

As far as the naming, csrf stands for cross site request forgery, which is the name of the attack. The cookie contains the csrf token secret, but what is submitted via the form is the csrf token. Neither if the values are a "csrf".

**Comment by SorinGFS** [comment]
You're right, but you start from the assumption that those who came here already know how the middleware works. For example, in the original library `csrf` was not implemented like this. There are several types of implementations! If you read readme file you see everywhere: you have to do this, you have to do that, if you don't do that it is required that, but nowhere is the mechanism described!

**Comment by SorinGFS** [comment]
Quote: "Neither of the values are a "csrf"."

`req.body._csrf` and `req.query._csrf` are values, right? Especially `req.body._csrf`` is the variable used by `express` after parsing the body forms!
