### ISSUE TITLE
Is it possible to set CSURF up with Postman?

### ISSUE THREAD

**Issue by jrd656** [expressjs/csurf#233]
I've followed the documentation example and have got things running to some extent. I've got the ```_csrf``` token being sent back and forth as a cookie. I've tried sending ```xsrf-token``` back as a header but I keep getting the error:
```ForbiddenError: invalid csrf token postman ```

I'm not sure it's possible and I've been trying for a day or so to figure out a solution.

**EDIT - This issue must take up so much time for other incompetents, like myself, that I've made a couple of video tutorials and walkthroughs:**

https://stackoverflow.com/a/65828688/11664580
https://youtu.be/VrFNbqSUVP0 
(set up with Postman). 

https://stackoverflow.com/a/65733895/11664580
https://youtu.be/N5U7KtxvVto 
(set up with React)

I know they're a bit crummy (I've never done it before) but they'd have helped me out if I'd seen them sooner.

**Comment by dougwilson** [comment]
Thanks for the info, @jrd656 . The examples from your first stackoverflow link are just the examples that is in our readme already. Please let me know if I'm missing something with your issue and I can re-open.
