### ISSUE TITLE
Intermittent issue - "ForbiddenError: invalid csrf token". 

### ISSUE THREAD

**Issue by Bala-Sutherson** [expressjs/csurf#236]
We are using a node js server with the express framework and it's running in the google app engine. Please find the package version which we are using in the application : 
```
"csurf": "^1.11.0",
"passport": "^0.4.1"
"express": "^4.17.1",
"node": ">=12.0.0"
```
We are randomly facing the "**invalid csrf token**" issue. We are using session configuration, not a cookie mode. Hereby, We have enclosed some configuration code.
```js
// Cookie configuration
const CookieOptions = {
  expires: new Date(Date.now() + 1800000),
  maxAge: 1800000,
  httpOnly: true,
  secure: true,
}

var csrfProtection = csrf({
  cookie: CookieOptions,
  ignoreMethods: ['HEAD', 'OPTIONS', 'GET'],
})

// middleware configuration
server.post('/api/*', csrfProtection)
server.set('csrfProtection', csrfProtection)

// CSRF token creation 
req.session.csrfToken = req.csrfToken()
```

Some of the express endpoints we have enabled the cookie and not for the entire application.  Please find the attached log screenshot.

![6392035-1a5c6b997edcd4bb934cee0be8352a7f](https://user-images.githubusercontent.com/78847530/109775160-29b18280-7c27-11eb-91f6-1a1dc3b55f69.png)

**Comment by dougwilson** [comment]
Closing due to no response.
