### ISSUE TITLE
Just to add ->  App Error: ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by Daxcor69** [expressjs/csurf#238]
75% of my testers get this error, the other 25% it works fine.  Has there been any progress on this issue?  I can't replicate the error on my computer but others can.  I am sorry not sure how to help other than to chime in that I am having the same.. I will have to remove the package.. and cobble something together,  however I will watch this issue closely.

**Comment by dougwilson** [comment]
Anyone is welcome to contribute a fix if they can figure it out, of course. I have not made any progress as I have yet to get a reproducable test case and it doesn't just happen on the sites I have built with this module...

**Comment by Daxcor69** [comment]
This is the same for me.. it works awesome for me every time!!! but for others no so much. I will do more testing to see what I can think of. the last thing is to move to cookie away from session and see if that helps. I will post more if I find a smoking gun.

**Comment by rachellerathbone** [comment]
I get the same `ForbiddenError: invalid csrf token` as well **but** only if a request is made from Safari. Any other browser is fine.

**Comment by Daxcor69** [comment]
I have tried both csurf and csrf packages and both are having the same issues for me. I believe it has to do with the seed/secret not consistently working correctly. I don't have the time or skill to prove it, but after rolling my own token creation everything works just fine.  I hope this observation is helpfull.

**Comment by dougwilson** [comment]
Hi @Daxcor69 that is indeed helpful. Unfortunately it just isn't enough information for us to actually do anything to help further along, as we have not observed the issue still. I appreciate the follow up you provided, but I guess I'll jsut close this as it sounds like you have moved on and there is no further information (like, perhaps, a reproduction case) for us to act on.
