### ISSUE TITLE
Invalid csrf token - however it is set in headers

### ISSUE THREAD

**Issue by weirdyang** [expressjs/csurf#239]
I keep getting this error; `invalid csrf token`, but it is set in the headers:

![image](https://user-images.githubusercontent.com/25576022/118126808-6b328b00-b42b-11eb-977b-d89e78a15d75.png)

here is my backend code

```
const corsOptions = {
  origin: process.env.CLIENT_URL,
  credentials: true,
  optionsSuccessStatus: 200, // some legacy browsers (IE11, various SmartTVs) choke on 204
};
const csrfProtection = csrf({ cookie: true });
app.use(cors(corsOptions));
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use(csrfProtection);
app.use('/users', usersRouter);
app.use('/auth', authRouter);
app.use('/journals', journalRouter);
```
front end:

```
export const setHeaders = () => {
    return axios.get('/auth/crsftoken').then((response) => {
        axios.defaults.headers.common['x-csrf-token'] = response.data.token
        console.log(response.data.token);
    }, (err) => {
        console.log(err);
    })
}

await setHeaders();
const { data } = await axios.post('/auth/login', userLogin);
```

**Comment by dougwilson** [comment]
Hi @weirdyang sorry you are having issues. Yes, I do see in your screen shot the token is in the header. I also see that you have `cookie: true` for your configuration for this module. Can you show a screenshot that shows the `Cookie` header is also being sent and what the value is for that as well?

**Comment by weirdyang** [comment]
> Hi @weirdyang sorry you are having issues. Yes, I do see in your screen shot the token is in the header. I also see that you have `cookie: true` for your configuration for this module. Can you show a screenshot that shows the `Cookie` header is also being sent and what the value is for that as well?


Hi @dougwilson

Thanks for the hint, I checked and the cookie is present but ignored. And this was because it is a cross domain request and the cookie was ignored as I didn't set sameSite to 'none'. It has been resolved and I appreciate the help! Thanks again.

**Comment by dougwilson** [comment]
No problem!
