### ISSUE TITLE
Hi. how is safe to save csrf?

### ISSUE THREAD

**Issue by jensysantana** [expressjs/csurf#243]
Hi. how is safe to save csrf? 
i thinking if i have to use redux.
or fowarared from my App page to my child. components as props in react my csrf to all my component and then use it. but i don't know if this is secure way to do it?

so I asking because after set a cookie as httpOnly i can't access it with javascript, I'm really using Nextjs and i know i can take the token using server side method but I don't want to do it in every pages.

**Comment by dougwilson** [comment]
Hi @jensysantana it is difficult for various reasons to give to a concrete answer, as there are many moving parts and we don't understand your application's design and attack vectors. This library facilitates basic CSRF attack mitigation by providing either the Synchronizer Token Pattern or the Double Submit Cookie pattern depending on the options you choose in the module. You can find in-depth information about CSRF prevention at https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html
