### ISSUE TITLE
How to create a csrf token against a user

### ISSUE THREAD

**Issue by riyadh-dev** [expressjs/csurf#246]
using cookie-parser how can i generate csrfTokens against authenticated user.
if a use a get route to get the csrfToken then the an attacking site can get it too.
if i protect said get route with an auth middleware that checks for an auth cookie. an attacker can use CSRF to get the csrfToken then use it for csurf protected routes

**Comment by dougwilson** [comment]
Hello, if you are using this module where is gives the token on a ,route, you should be be enabling Cors on that route, which is how other sites would be able to get the token.

The best method to tie it to your users is to use the default mode (`cookie: false`) so the token is bound to the user session and not an independent cookie.

I hope that helps.

**Comment by riyadh-dev** [comment]
> 
> 
> Hello, if you are using this module where is gives the token on a ,route, you should be be enabling Cors on that route, which is how other sites would be able to get the token.
> 
> The best method to tie it to your users is to use the default mode (`cookie: false`) so the token is bound to the user session and not an independent cookie.
> 
> I hope that helps.

i think the cors methods can be bypassed by feigning the origin header
i was thinking about issuing csrfToken only after a successful login. but a post login route can not access req.csrfToken unless it uses csurf middleware which will block the request without a valid csrfToken 

so is there is a way to access req.csrfToken on post route without validating the post request csrfToken

**Comment by dougwilson** [comment]
> so is there is a way to access req.csrfToken on post route without validating the post request csrfToken ?

Yes, add this middleware to your POST route with `ignoreMethods` set to include `POST`.
