### ISSUE TITLE
_csrf error: didn't specify a "samaSite" attribute ...

### ISSUE THREAD

**Issue by ahuvia** [expressjs/csurf#250]
![image](https://user-images.githubusercontent.com/62541894/150784740-09357961-3711-4cc5-83cf-049af2e13165.png)

i add option to cookie:
![image](https://user-images.githubusercontent.com/62541894/150761496-58834df2-c596-4549-b040-1e84b212158f.png)
and get error:
![image](https://user-images.githubusercontent.com/62541894/150761348-bd28a639-c58d-40fd-a097-f7da5960887b.png)

What I set for cssrf-token, does not help to "_csrf"

**Comment by dougwilson** [comment]
To change attributes for the `_csrf` cookie, you need to specify them in the `cookie` option for this module: https://github.com/expressjs/csurf#cookie
