### ISSUE TITLE
ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by efhan-the-unorthodox** [expressjs/csurf#251]
Problem
---
I have a Express App with Typescript. I installed Express CSURF just as instructed as said in the documentation.
However, whenever I make a request to the express app, I will get the error saying "ForbiddenError: invalid csrf token".
There are similar issues that have been lodged so I believe that I am not the only one.

Also, when I call `req.csrfToken`, it returns undefined. Thus I believe that this library could be broken or something. 

Likewise, if I cannot use this library for CSRF tokens, is there an alternative

**Comment by dougwilson** [comment]
Hi, sorry you are having trouble. Have you tried the example app in the readme to see if that works? We can try to help with your situation, but you will need to post your app.

**Comment by efhan-the-unorthodox** [comment]
The following is my app.ts. The root file of my application.
As you can see from the code below, I have followed according to the documentation and I initialized the csurf middleware before the `session`.  Running the app will have no problem but when I send POST or GET request, or any request, the app will log an error saying `ForbiddenError: invalid csrf token`

```ts
import express, { request, Request, Response } from 'express'
import 'dotenv/config'
import passport from 'passport';
import session from 'express-session';
import clientController from './client/client';
import authController from './auth/auth.controller';
import saController from './superadmin/superadmin';
import cors from 'cors';
import csurf from 'csurf';
import cookieParser from 'cookie-parser';
import bodyParser from 'body-parser';

const app = express();
app.use(cookieParser())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(express.json())
app.use(cors({
    credentials: true,
    origin: ['http://localhost:3000']
}));

const csrfMiddleware = csurf({ cookie: true })

const port = process.env.PORT
const sessionSecret = process.env.SESSION_SECRET

app.use(session({
    secret: sessionSecret!.toString(),
    resave: true,
    saveUninitialized: false,
    cookie: {
        httpOnly: true
    }
}))
app.use(csrfMiddleware)

app.use(passport.initialize());
app.use(passport.session());

passport.serializeUser((user: Object, done) => {
    console.log(user)
    done(null, user)
})

passport.deserializeUser((user: Object, done) => {
    done(null, user);
})

//Authentication route
const authRoute = authController
app.use('/auth', authRoute);
```

**Comment by dougwilson** [comment]
Thanks for posting that! So since you are using `cookie: true` configuration, it doesn't matter where this module goes in relation to your session middleware, since that uses a cookie instead of a session to store the secret. So what I don't see, though, is where you are calling `req.csrfToken()` and how, exactly, you are using that value to actually pass it to the server. If you're not, that would be why you are getting that error, as you are not actually providing the token with your POST request.

**Comment by efhan-the-unorthodox** [comment]
Okay first off, if what you're saying is that the method of using cookies is different from what was stated in the usage documentation, then the documentation is somewhat misleading because it is going to make people think that this library will allow people to have CSRF working out of the box. 

Another thing I need to ask is how exactly do I use `req.csrfToken()` in this case to verify the tokens for every request? Because I was supposing that if put the `cookie: true` option, the library would get the token from the cookie and all I had to do was to let the middleware handle the verification. I looked up on `req.csrfToken()` and when I tried it , it said that it wasn't a function.

**Comment by dougwilson** [comment]
I think you are accidentally confusing the csrf _secret_ and the csrf _token_. You are welcome to stop by the express Gitter channel if you are looking for support. Unless there is a clear issue, then I can re-open this. I tried both of the examples in the README and they work without issue. If you also think there is unclear docs, please feel free to open a pull request, or even a pull request if you think there is a bug.

**Comment by efhan-the-unorthodox** [comment]
Apparently I tried the example myself and it works. However, after adding express-session and passportjs, it seemed to return the same 403 error again

**Comment by efhan-the-unorthodox** [comment]
Also, i've just noticed that it will only have this error on POST requests
