### ISSUE TITLE
Generate multiple cookie in cookie mode.

### ISSUE THREAD

**Issue by FreeLancerPT** [expressjs/csurf#253]
Hello, i am using csurf with express as an API serving to a Vue 3 frontend using axios.

In my router.js i have: 

var csrf = require('csurf')
var csrfProtect = csrf({
                        cookie: {
                            httpOnly: true
                        } 
                    });

// Generate a token and send cookie
router.get('/csrfToken', csrfProtect, function(req, res) {
        res.cookie('XSRF-TOKEN', req.csrfToken());
        res.send({
            success: true,                   
        });   
});

//Login route
router.post('/login', csrfProtect, loginValidate, (req, res, next) => AuthController.login(req, res, next));

It is working! 

But i saw that is setting two cookies :
_csrf and XSRF-TOKEN

Can't use just one of the two? 
Is this normal?

Appreciate any guidance and help, thanks.

**Comment by dougwilson** [comment]
Hello! You do need two places to store the two pieces of information: the csrf token and the csrf secret. You can always store the secret in a session if you like instead of a cookie, or embed the token on the html response instead of a cookie.

**Comment by FreeLancerPT** [comment]
@dougwilson Thanks! 
Just to clarify is there any inconvenience in staying in cookies?
the _csrf is set as httpOnly

**Comment by dougwilson** [comment]
I'm not really sure what you mean by "is there any inconvenience in staying in cookies".

**Comment by FreeLancerPT** [comment]
As you have said before : "You do need two places to store the two pieces of information", my question was if it is Ok be stored in cookies. But it seems ok!

Thanks for your clarification!
