### ISSUE TITLE
Should the the token be stored in cookies

### ISSUE THREAD

**Issue by abissens** [expressjs/csurf#254]
To my understanding of the [Double Submit Cookie](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie ) technique, the verification key should not be placed on browser (i.e cookies) since its purpose is to prevent sub domains compromise threats : 

> This works because a sub domain has no way to over-write an properly crafted encrypted cookie without the necessary information such as encryption key.

Plus, the [csrf ](https://github.com/pillarjs/csrf) library states that the secret should be kept on server side session : 

> tokens.secret(callback)
... The secret is to be kept on the server, typically stored in a server-side session for the user. The secret should be at least per user.

If I am not mistaken, I wonder how does the token hashing / verification by placing the secret value in cookie provide more protection over simply generating cryptographically random token and checking for cookie/request parameter equality ?

**Comment by dougwilson** [comment]
Hi @abissens ! As far as I am aware there isn't an issue with this. If there is indeed some sort of issue security wise, please feel free to report the specifics according to the express project policy at http://expressjs.com/en/resources/contributing.html#security-policies-and-procedures

As for your laat question, I am not sure off my head, as I didn't write the initial implementation and the authors who did are no longer active maintainers.

I hope that helps!
