### ISSUE TITLE
Shouldn't CSRF check be allowed to be disabled depending on method of auth?

### ISSUE THREAD

**Issue by KieronWiltshire** [expressjs/csurf#256]
For example, if sessions aren't used and the user is authenticated via `Authorization` header?

**Comment by dougwilson** [comment]
Hi @KieronWiltshire you can configur your CSRF middleware in any way you like, to apply to just the requests you want it to like you would any other middleware; that's the beauty of the middleware pattern :) Here is an example:
```js
function onlyIf (mw, fn) {
  if (fn(req, res)) mw(req, res, next)
  else next()
}
```

then you can make the middleware conditional on if auth'd (however your particular thing works:
```js
app.use(onlyIf(csurf(/* csurf options */), function (req, res) {
  return isValidAuth(req.headers.authorization)
}))
```

I hope that helps!

**Comment by KieronWiltshire** [comment]
Yes, I apply this already, just seems like something that should be native to this package.
