### ISSUE TITLE
Problem with tokens.verify function

### ISSUE THREAD

**Issue by pstachula-dev** [expressjs/csurf#258]
I have Nes.js backend
```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe());
  app.use(helmet());
  app.use(cookieParser());
  app.enableCors({
    credentials: true,
    origin: 'http://localhost:3000',
    methods: ['POST'],
  });

  app.use(
    csrf({ cookie: true  }),
  );
  await app.listen(4000);
}
```

And simple Axios interceptor on Frontend:
```
apiClient.interceptors.request.use((config) => {    
  return {
    ...config,
    headers: {
      ...config.headers,
      Authorization: `Bearer ${accessToken}`,
      'XSRF-TOKEN': Cookies.get('_csrf')
    }
  }
}, (error) => {
  console.error(error);
  return Promise.reject(error);
});
```

I logged values of cookie and secret and there is problems with compare function:

// node_modules/csurf/index.js
```
   console.log('MY_FLAG', secret, value(req));

    // verify the incoming token
    if (!ignoreMethod[req.method] && !tokens.verify(secret, value(req))) {
      return next(createError(403, 'invalid csrf token', {
        code: 'EBADCSRFTOKEN'
      }))
    }
```

Values: `MYFLAG jRgzvS7hEW9u6cFd7w470ZH7 jRgzvS7hEW9u6cFd7w470ZH7`

But tokens are invalid, what is the problem?

**Comment by dougwilson** [comment]
You are passing the secret value as the token. You need to pass the token back as the token. Check out our SPA example: https://github.com/expressjs/csurf#single-page-application-spa

**Comment by pstachula-dev** [comment]
I am passing `Cookies.get('_csrf')` from  cookies... this is not secret.

**Comment by dougwilson** [comment]
https://www.npmjs.com/package/csurf#cookie

> Determines if the token secret for the user should be stored in a cookie or in req.session. Storing the token secret in a cookie implements the [double submit cookie pattern](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie).

https://www.npmjs.com/package/csurf#csurfoptions

> This middleware adds a req.csrfToken() function to make a token which should be added to requests

**Comment by pstachula-dev** [comment]
Omg I didin't have a `@types/csurf` package... that was a problem because on TS this methods are missing.

There was 0 info about this in nestjs docs and here. :)
Big thanks for help.
