### ISSUE TITLE
Make _csrf cookie available on subdomain

### ISSUE THREAD

**Issue by GeorgianStan** [expressjs/csurf#260]
Hello!

I have a use case where my back-end URL is something like  `https://api.sub.domain.com`  and the front-end application is on `https://sub.domain.com`. 
When setting the token I used the `domain` property like it follows:

```js
res.cookie('XSRF-TOKEN', req.csrfToken(), {
  domain: '.sub.domain.com',
 });
```

This will make the `XSRF-Token` available, but not the cookie `_csrf`.

It's there any solution for this use case?

**Comment by dougwilson** [comment]
```js
app.use(csurf({ cookie: { domain: '.sub.domain.com' } }))
```
