### ISSUE TITLE
ForbiddenError: invalid csrf token, possibly invalid token formatting

### ISSUE THREAD

**Issue by ahoys** [expressjs/csurf#261]
Hey, I've been struggling to implement csurf into a rather big isomorphic web application for some time now. After investigating why the cookie _csrf is being rejected, I found that a bizarre if-statement in csrf library is looking for a "-" character, which doesn't exist in the key, generated by csurf.

Here you can see a failed request that holds the key:
![image](https://user-images.githubusercontent.com/14974945/176179495-8b4320bb-c138-4cf8-ae2b-a2c78deb65a2.png)

My code with some parts taken out:
```
import express from 'express';
import csurf from 'csurf';
import cookieParser from 'cookie-parser';
import config from 'config';
import { urlencoded, json } from 'body-parser';
import { setBackend0Services, setBackend1Services, setBackend2Services } from 'external-library-x';

...

const bootstrap = async () => {
  ...
  const server = express();
  ...
  server.use(cookieParser(config.cookies.secret));
  server.use(
    urlencoded({
      extended: true,
      limit: '10mb',
    })
  );
  server.use(
    json({
        limit: '10mb',
    })
  );
  server.use(
    csurf({
      cookie: {
        path: config.express.publicPath,
        domain: config.cookies.domain,
        maxAge: 86400000,
        secure: false,
        sameSite: false,
      },
      value: (req) => {
        return req.cookies._csrf ?? '';
      },
    })
  );
  // Services (routes) are set here, for multiple different backends.
  // No changes made for csurf.
  setBackend0Services(server, config);
  setBackend1Services(server, config);
  setBackend2Services(server, config, (req, res, next) => {
    next();
  });
  ...
};

bootstrap();

```

And here is the verification function that calls out my key being malformed or otherwise invalid. Notice the indexOf test looking for "-", while my key (img above) has no such char.

node_modules/csrf/index.js:
```
Tokens.prototype.verify = function verify (secret, token) {
  if (!secret || typeof secret !== 'string') {
    return false
  }

  if (!token || typeof token !== 'string') {
    return false
  }

  var index = token.indexOf('-')

  if (index === -1) {
    return false
  }

  var salt = token.substr(0, index)
  var expected = this._tokenize(secret, salt)

  return compare(token, expected)
}
```

node_modules/csurf/index.js
```
// verify the incoming token
if (!ignoreMethod[req.method] && !tokens.verify(secret, value(req))) {
  console.log({ secret, value: value(req)})
  return next(createError(403, 'invalid csrf token', {
    code: 'EBADCSRFTOKEN'
  }))
}
```
![image](https://user-images.githubusercontent.com/14974945/176183808-e749e355-f033-4781-8592-b0ac5845e8fe.png)

I also tried not having a value func and instead using request body._csrf.

Does my cookie value look OK? I'm using security libraries like cors and helmet, if relevant. The services I use are from an external library (we got multiple web applications utilizing the same services).

Any insight on what's going on here?

**Comment by dougwilson** [comment]
The value in the `_csrf` function is the secret, not the token to aubmit back. You have to call `req.csrfToken()` to get the token and that is what your page needs to submit back to the server. I don't see your code calling `req.csrfToken()` anywhere to get the token to use.

**Comment by dougwilson** [comment]
Check out our docs specifically around using a SPA as well: https://github.com/expressjs/csurf#single-page-application-spa

**Comment by ahoys** [comment]
Ah, so I had just misunderstood how to configure/use csurf.

I now generate & pass the csrfToken with the initial server render into one of the application's redux reducers, from which it is then read (client-side) to requests by placing it into a "csrf-token" header.

**Thank you!**

Some snippets for anyone else trying to figure this out:

Server.tsx (server-side renderer)
```
...
session.csrfToken = req.csrfToken();
...
const store: Store<t.CombinedStore> = configureStore(
  Map({
    session,
    ...
  })
);
...
```
Client-side requests:
```
...
const res = await superagent
    .post(some-api)
    ...
    .set('csrf-token', <token from the reducer>)
   ...
    .send(...);
...
```
