### ISSUE TITLE
Invalid csrf token

### ISSUE THREAD

**Issue by geolyth** [expressjs/csurf#44]
Hi,
I have a problem with csurf and I don't understand If it is a problem or not...
 I have a single app page with a nodejs in the backend and angularjs in the frontend.
When HTML starts to load data, there are many cookies generated (and not only one).

In backend I have:
```js
app.use(csrf({cookie: true}));
app.use(function(req, res, next) {
  var csrfToken = req.csrfToken();
  res.cookie('XSRF-TOKEN', csrfToken);
  next();
});
```
In frontend I read successfully the token, but I have a receive always the same error: "invalid csrf token". Why this happens?

Thanks you

**Comment by dougwilson** [comment]
Unfortunately some angular questions like this have come up before, but the posters never ended up responding, so I don't know what to tell you. If you provide me the source to the full app, I can try to help you, though.

**Comment by dougwilson** [comment]
> If you provide me the source to the full app, I can try to help you, though.

Oh, and it doesn't have to be _your_ app, just _a_ full app that reproduces the issue that I can investigate. Mainly because I have no knowledge about anything with Angular.

**Comment by geolyth** [comment]
Try to replicate the error is strong enough...I would fix it and then send you.
I have understand maybe what is the problem...

First time I do a GET call, secret is generated fine and it creates a cookie, when I try to do a POST call secret is undefined and csurf creates a new one.

**Comment by dougwilson** [comment]
Ok. Make sure you are using the cookie-parser middleware in your server code above csurf, as stated in the readme :)

**Comment by geolyth** [comment]
Yes I have, in backend I have these lines:
app.use(cookieParser());
app.use(session({secret:'mommaighkeoljiop', key:'session_cookie', saveUninitialized: false, resave: true}));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var corsOptions = {
  allowedHeaders: 'X-Requested-With, content-type, Authorization, X-API-KEY, X-XSRF-TOKEN'
};
app.use(cors(corsOptions));

app.use(csrf({cookie: true}));
app.use(function(req, res, next) {
  var csrfToken = req.csrfToken();
  res.cookie('XSRF-TOKEN', csrfToken);
  next();
});

**Comment by dougwilson** [comment]
Gotcha. But yea, if you're not getting the secret on later calls, it should be pretty easy to debug. The line https://github.com/expressjs/csurf/blob/master/index.js#L159 just looks in `req.cookies._csrf`, which is populated from `cookie-parser` module, which ultimately looks for the `_csrf=` cookie in `req.headers.cookie`.

**Comment by geolyth** [comment]
I know this is the problem but I don't know why it happens...I have the cookie also in POST call (I generate one token only in the first GET call and I don't delete it) but doesn't work.

**Comment by dougwilson** [comment]
Gotcha. Yea, I'm not sure. To really be able to tell you anything concrete, I need you to provide me with a full Angular app that has this issue that I can run on my machine to debug it.

**Comment by geolyth** [comment]
Ok I'll try to provide the code for testing...as soon as...

**Comment by geolyth** [comment]
I'm apologize but I can't replicate situation...I could give you further information about it...
I found this problem occurs because I have to enable CORS to allow cross request. Also I have used correct credentials parameter in cors but cookie in OPTIONS isn't generated.

**Comment by dougwilson** [comment]
Gotcha. I've never tried to use this module with CORS and don't have any information to help you, I'm sorry. Perhaps someone will see this open question on this repo and drop by with an answer? You can also try asking for help on stackoverflow.com

**Comment by dougwilson** [comment]
And of course, just as a note, this module's purpose (and CSRF in general) is to _prevent cross-site requests_ (which seems to be what's happening to you), so I'm not sure how well it mixes with what you are even trying to do (to _make cross-site requests_).

**Comment by geolyth** [comment]
I would use CORS to provide access to my API from every origin but in the same time I would be sure POST. PUT, DELETE (OPTIONS) should be executed only by browser.

Thanks you so much

**Comment by dougwilson** [comment]
Yea, I'm not sure. Really, no one else is going to be able to help you here and without code and a way to run your stuff to determine your problem, I won't be able to help you either, I'm sorry. I suggest posting your question to some IRC channel or a service like stackoverflow.com
