### ISSUE TITLE
RFC 6648: SHOULD NOT prefix their parameter names with "X-"

### ISSUE THREAD

**Issue by arty-name** [expressjs/csurf#49]
When reading values from headers, csurf looks at `x-xsrf-token` and `x-csrf-token`. [RFC 6648 recommends against using `X-` prefix for non-standard HTTP headers](http://www.ietf.org/rfc/rfc6648.txt). Would be nice if csurf added support for headers `xsrf-token` and `csrf-token`, recommended their use in the documentation and linked to RFC 6648.

**Comment by gabeio** [comment]
I would have to agree that looking at xsrf-token and csrf-token headers for the tokens also would be nice. or give the option to give your own header so it can be whatever the user wishes.

**Comment by gabeio** [comment]
@arty-name though that only recommends against using x- therefore it's up to the expressjs team.

**Comment by arty-name** [comment]
@gabeio could you also update readme in your PR?

**Comment by gabeio** [comment]
added

**Comment by arty-name** [comment]
thanks! :+1:

**Comment by gabeio** [comment]
also added tests

**Comment by dougwilson** [comment]
In the meantime, you can pass in your own function for the `value` option if you need non-x-headers.

**Comment by arty-name** [comment]
Yes, but I'm striving for reasonable defaults too :)

**Comment by dougwilson** [comment]
Ok, this sounds fine to me, especially with RFC 6648

**Comment by dougwilson** [comment]
@arty-name published as 1.7.0

**Comment by arty-name** [comment]
Thank you @dougwilson!
