### ISSUE TITLE
When csrfToken() method is called?

### ISSUE THREAD

**Issue by efkan** [expressjs/csurf#56]
Hello,

I had arranged a middleware to allow a certain route to pass without csrf examine like the below. Now, I've been trying to get rid of this error message: `[TypeError: Object #<incomingMessage> has no method 'csrfToken']` . Because of this error my response status is set as 500 (internal server error). 

I was wondering how can I obstruct being called csrfToken() ?

    var csrf = csurf()
    app.use(function (req, res, next) {
        if (req.path == '/test') return next()        
        csrf(req, res, next)          
    })

**Comment by dougwilson** [comment]
Hi! That method is never called by this module, rather it is called by your own code. If you can print out the stack trace for that error, it will point to the line number and which one of your files is calling it.

**Comment by efkan** [comment]
Oh my bad!
I didn't know but I learned how to print out stack trace. 
And I had forgotten that I called the method in another middleware.
Thank you!
