### ISSUE TITLE
Image Upload form with enctype="multipart/form-data" Issue

### ISSUE THREAD

**Issue by NullArgument** [expressjs/csurf#58]
`<form action="/upload_avatar" method="post" enctype="multipart/form-data" >`
....
....
`<input type="hidden" name="_csrf" value="{{csrfToken}}" >`
....
....
`</form>`

I think this form doesn't work because it has enctype="multipart/form-data"
if i remove it, it works like a charm, but i can't because it is necessary for the uploading process.

Can any other developer confirm this??

Thanks.

**Comment by dougwilson** [comment]
What are you using to parse your `multipart/form-data`? Can you provide a code sample?

**Comment by NullArgument** [comment]
I'm using multiparty (https://github.com/andrewrk/node-multiparty/) to parse the data
I'll post a screenshot tomorrow that describes the problem better. I'm not on my Laptop right now.

And by the way, congratulations for this great anti-csrf middleware that you are developing, i'm very pleased with it.

**Comment by dougwilson** [comment]
Ah, ok. So until the module gets split up a little more, the problem is when you want to put the token within the body of the request (as a hidden `<input>`, say), then the body has to be parsed before getting to this middleware, which doesn't always work when using complex bodies like `multipart` :)

So a simple solution could be to put it in the query string (`<form action="/upload_avatar?_csrf={{csrfToken}}" method="post" enctype="multipart/form-data">`), but it's not the greatest solution long-term.

To actually get it working in the body, I can draw up an example for you :) Are you using `multiparty` with the callback-style API (`form.parse(req, function(err, fields, files) {` or the events API?

**Comment by NullArgument** [comment]
It seems that you don't need a screenshot. You understood the problem ;)
I'm using `multiparty` with the callback-style API i think. Not sure though...

I have a callback function that is used to upload the image and contains:

`form.on('file', function(name,file){`
....
`});`

and

`form.parse(req, function() {`
....
`});`

**Comment by alvarotrigo** [comment]
+1 Trying to use csurf with [multer](https://github.com/expressjs/multer) and having the same problem.

**Comment by dougwilson** [comment]
For `multer`, just `app.use` it above `csurf` for now. https://github.com/expressjs/csurf#simple-express-example shows you how to use it (just change `parseForm` to use `multer`).

**Comment by alvarotrigo** [comment]
@dougwilson still having troubles... it seems its because of the `enctype="multipart/form-data"`.

**Comment by alvarotrigo** [comment]
This is what I have at the moment:
```javascript
var express = require('express');
var router = express.Router();
var app = express();

var request = require('request');
var common = require('./common');

var csrf = require('csurf');
app.use(csrf());

//to upload files
var multer = require('multer');
app.use(multer({
    dest: './uploads/',

    rename: function (fieldname, filename) {
        return filename + Date.now();
    },

    onFileUploadData: function (file, data, req, res) {
        console.log(data.length + ' of ' + file.fieldname + ' arrived............................')
    },
    onFileUploadComplete: function (file, req, res) {
        console.log(file.fieldname + '........................... uploaded to  ' + file.path)
        done = true;
    }
}));
```

**Comment by dougwilson** [comment]
@alvarotrigo `app.use(multer` needs to be _above_ `app.use(csrf());`, or you need to use the pattern that is listed in the readme.

**Comment by alvarotrigo** [comment]
@dougwilson yeah, sorry I posted an old version. Same issue:

```javascript

var csrf = require('csurf');
var multer = require('multer');

app.use(multer({
	dest: './uploads/',

	rename: function (fieldname, filename) {
		return filename+Date.now();
	},

	onFileUploadData: function (file, data, req, res) {
		console.log(data.length + ' of ' + file.fieldname + ' arrived............................')
	},
	onFileUploadComplete: function (file, req, res) {
		console.log(file.fieldname + '........................... uploaded to  ' + file.path)
		done=true;
	}
}));

app.use(csrf());
```

**Comment by alvarotrigo** [comment]
> need to use the pattern that is listed in the readme.

Here's what I tried:

```javascript


var csrf = require('csurf');
var multer = require('multer');

var csrfProtection = csrf({ cookie: true });

var multerUploader = multer({
	dest: './uploads/',

	rename: function (fieldname, filename) {
		return filename+Date.now();
	},

	onFileUploadData: function (file, data, req, res) {
		console.log(data.length + ' of ' + file.fieldname + ' arrived............................')
	},
	onFileUploadComplete: function (file, req, res) {
		console.log(file.fieldname + '........................... uploaded to  ' + file.path)
		done=true;
	}
});

router.get('/add', csrfProtection, function (req, res) {
    var session = req.session;

    request.get('http://localhost:8181/Test/absences?action=add', function (error, response, body) {
        if (error || response.statusCode != 200) {
            console.log("error!");
            res.send({});
        } else {
            var data = JSON.parse(body);

            res.render('absences/add', {
                csrfToken: req.csrfToken()
            });
        }
    });
});


router.post('/add', multerUploader, csrfProtection,  function(req, res, next) {
     //...
});


//adding an absence
router.post('/add', multerUploader, csrfProtection,  function(req, res, next) {
// ...
});

**Comment by dougwilson** [comment]
@alvarotrigo your code is working fine for me. Unfortunately because CSRF requires a lot of moving parts, it's possible something else is wrong. It's hard for me to help more unless you provide an absolutely complete application I can run on my Windows machine and then provide full browser instructions on what to do to reproduce the issue.

**Comment by alvarotrigo** [comment]
@dougwilson thanks for your help. I will check if uploading to the latest version of csurf can help on this regard.

**Comment by dougwilson** [comment]
FWIW, I would have added `multer` to our test suite, but it doesn't support Node.js 0.8, so I cannot.

**Comment by alvarotrigo** [comment]
@dougwilson I'm using the latest version, but the problem stills there.
Just to verify the HTML resulting markup is correct. This is how my form looks like:

```html
<form action="" method="post" class="validateForm" enctype="multipart/form-data">
    <h1>Leave Application Form</h1>

    <input type="hidden" value="0" name="require_request" />
    <p id="sickLeaveUpload">Upload Sick Leave Form
        <input type="file" name="userPhoto" />
    </p>
    <p>
        <select name="duration" id="amPm" class="form-control">
            <option value="day" selected>Day</option>
            <option value="am">Half day AM</option>
            <option value="pm">Half day PM</option>
        </select>
    </p>
    <input type="hidden" name="_csrf" value="NeQIyjb3-D_xmUlSEHY6i4RIIy9N_IPZgcYc" />
    <input type="submit" value="Save" class="btn btn-lg btn-primary" id="submit" />
</form>
```

**Comment by dougwilson** [comment]
Yes that should be fine as long as `NeQIyjb3-D_xmUlSEHY6i4RIIy9N_IPZgcYc` is a valid token for the cookie you submit with the from. Do you see `req.body._csrf` in the POST on the server?

**Comment by alvarotrigo** [comment]
I can't access to `req.body`. The error jumps before I can get anything from `.post`

**Comment by dougwilson** [comment]
Hi @alvarotrigo , sorry for the delay. To "access" it, you can just add a temporary middleware between the `multer` middleware and the `csurf` middleware to just wring the contents:
```js
// multer middleware here
app.use(function (req, res, next) {
  console.dir(req.body)
  next()
})
// csurf middleware here
```

**Comment by alvarotrigo** [comment]
Excuse me for my lack of knowledge in this area, but, as I'm using the middleware in the function parameters, I'm not quite sure how I should do what you point out:

```javascript
router.post('/add', multerUploader, csrfProtection,  function(req, res, next) {
     //...
});
```

I tried:
```javascript

var tmp = function (req, res, next) {
  console.dir(req.body)
  next()
};

router.post('/add', tmp, multerUploader, csrfProtection,  function(req, res, next) {
     //...
});
```
But it doesn't seem to work at all.

**Comment by alvarotrigo** [comment]
Ok. thanks @dougwilson. I have it working now. I didn't realise I was using `app.use(csrf());` in `app.js` as well. 
I have it working now. Thanks for all.

**Comment by dougwilson** [comment]
Ooops! lol. I'm glad you got it working! And as far as your question, I can do the following (just for leaning :) ):
```js
function logBody(req, res, next) {
  console.dir(req.body)
  next()
}

// ...

router.post('/add', multerUploader, logBody, csrfProtection,  function(req, res, next) {
// ...
```

**Comment by shaond** [comment]
Just for anyone coming across this issue from Google, a quick workaround when using a multipart form us to append the CSRF token as a query string. Not ideal as this will get logged in nginx/apache logs etc. but does get around the issue.

So using the above example, 

```html
<form action="/api?_csrf=#{csrfToken}" method="post" class="validateForm" enctype="multipart/form-data">
    <h1>Leave Application Form</h1>
```

Where `csrfToken` is inserted by JADE, or whichever templating engine you are using.

**Comment by vipersec** [comment]
Thanks @shaond

**Comment by AlexSneedMiller** [comment]
Thank you!

I'm facing the same issue, but appending it to the query parameters fixed it for me. Any chance that this will get worked on going forward, or do you think this is more of an issue with multiparty?

**Comment by eloquence** [comment]
I ran into this issue as well. I don't like the query string solution because secret tokens really shouldn't be part of URLs that may end up in logs and such. And moving the CSRF middleware after multer had the consequence that CSRF errors were reported, but files were still stored. (If you're using that approach, you may want to double-check that you're not vulnerable to files being uploaded, even though the CSRF check correctly reports an error later on.)

The approach I'm using now is as follows. Appreciate any comments if you see problems with it. It seems to work as intended -- the CSRF check is performed, and files aren't uploaded if it fails.

I briefly ran into the issue with req.body not being populated yet in fileFilter, which I fixed by ensuring the CSRF key is positioned in the form above the file input.

```javascript
router.post('/upload', function(req, res, next) {

  let upload = multer({
    dest: path.join(__dirname, '../static/uploads'),
    fileFilter
  }).array('media');

  upload(req, res, function(error) {
    if (error) {
      if (error.code == 'EBADCSRFTOKEN')
        return res.send('csrf error');
        });
      else
        return next(error);
    }
    res.send('ok');
  });

  function fileFilter(req, file, done) {
    csrf()(req, res, error => {
      if (error) {
        // CSRF is incorrect
        done(error);
      } else {
        // CSRF is fine
        done(null, true);
      }
    });
  }

});
````

**Comment by pwright08** [comment]
@eloquence are the two brackets after `csrf` meant to be there?

`csrf()(req, res, error => {`

**Comment by chshouyu** [comment]
sorry, in my project, I still have the problem.
here is my code
```
const upload = require('multer')();
const csrfProtection = require('csurf')();

router.get('/add', csrfProtection, (req, res, next) => {
  res.render('add', {
    csrfToken: req.csrfToken() // 1
  });
});

router.post('/search', upload.array(), (req, res, next) => {
  // 2 got the req.body._csrf
  console.log(JSON.stringify(req.body, null, 2));
  next();
}, csrfProtection, (req, res, next) => {
  res.json({
    msg: 'ok'
  });
});
```

I use the native `fetch` and `FormData` to send a post request to `/search`
```
var formData = new FormData();
formData.append('_csrf', getCsrf());
fetch('/search', {
  method: 'post',
  body: formData
}).then(function(res) {
  return res.json();
}).then(function(json) {
  console.log(json.msg);
});
```
and the csrfToken in `1` and `2` are really equal, but I got the error `invalid csrf token at csrf`.
I have try so many ways, still not work.
hope anyone can help me, thanks.

**Comment by aashevchenko7** [comment]
Guys, thanks for yours answers. Use token in uri. It was hep for me. I have using middleware passport, so when i send a file on server i need to use uri like,  "form action="/upload_avatar?_csrf={{csrfToken}}" gl.

**Comment by geetayu** [comment]
Hi,

My formibale for.on method is not working can anyone help on this 


app.post('/api/product/create', function(req, res) {
 var filepathname;
 // var form = new formidable.IncomingForm();

   // form.parse(req);

	
	
   
   // form.on('fileBegin', function (name, file){
	  
       // file.path = __dirname + '/uploads/' + file.name;
// filepathname=file.path;
   // });

   // form.on('file', function (name, file){
       // console.log('Uploaded ' + file.name);
   // });

  // res.sendFile(__dirname + '/api/product/create');
	

 
   
    fs.readFile(PRODUCTS_FILE, function(err, data) {
        if (err) {
            console.error(err);
            process.exit(1);
        }
		
		 var form = new formidable.IncomingForm();

    form.parse(req);


	
    form.on('fileBegin', function (name, file){
        file.path = __dirname + '/uploads/' + file.name;
		filepathname= file.path;
		console.log("File path:->"+filepathname);
	});

    form.on('file', function (name, file){
        console.log('Uploaded ' + file.name);
    });
	


  //res.sendFile(__dirname + '/index.html');
		
        var products = JSON.parse(data);

        var newProduct = {
            id: Date.now(),
            name: req.body.name,
            price: req.body.price,
			desc:req.body.desc,
			upload:filepathname,
        };
        products.push(newProduct);
	console.log("newProduct"+newProduct.upload);
        fs.writeFile(PRODUCTS_FILE, JSON.stringify(products, null, 6), function(err) {
            if (err) {
                console.error(err);
                process.exit(1);
            }
            res.json(products);
        });
    });
});

**Comment by gregbown** [comment]
You can use csurf with multipart/form-data by [placing the token in the header and using ajax to post the file upload](https://gist.github.com/gregbown/040521b2ab6d549e8ab59184ef942a10)
No token in the url!

**Comment by Hongbo-Miao** [comment]
The new way using header to pass CSRF token is at https://github.com/expressjs/csurf#using-ajax
The document is using `fetch`.

Here I am providing the way using `axios`, hopefully it helps future people.

```js
axios.post(`/upload-file`, formData, {
  headers: {
    'CSRF-Token': csrfToken,
  },
});
```

**Comment by shafdo** [comment]
> You can use csurf with multipart/form-data by [placing the token in the header and using ajax to post the file upload](https://gist.github.com/gregbown/040521b2ab6d549e8ab59184ef942a10) No token in the url!

**Thanks @gregbown, as you mentioned adding the CSRF token in the HTTP headers of the AJAX request worked for me 👏.**
