### ISSUE TITLE
Disable it for API routes

### ISSUE THREAD

**Issue by razvanz** [expressjs/csurf#59]
My node application routes the requests in two main categories `/app`, `/api`. The application uses `csurf` as described in the examples.

How can I disable it for the `/api` routes since I'm using token authentication ([RFC 6750](http://tools.ietf.org/html/rfc6750)) and I don't want CSRF protection.

**Comment by dougwilson** [comment]
Rather than doing `app.use(csurf())`, you can do `app.use('/app', csurf())` so that it only applies to your `/app` routes.

**Comment by razvanz** [comment]
Thanks!
