### ISSUE TITLE
TypeError: Object #<IncomingMessage> has no method 'csrfToken'

### ISSUE THREAD

**Issue by mzarella** [expressjs/csurf#61]
`req.csrfToken()` is causing this error:
```
TypeError: Object #<IncomingMessage> has no method 'csrfToken'
```

Here's the snippet of code I have inserted:

```js
app.use( function (req, res, next) {
  debugger
  res.cookie('XSRF-TOKEN', req.csrfToken());
  next()
}
```

That snippet was taken from @cdmatta's blog:
 http://charandeepmatta.com/2014/06/04/csrfxsrf-protection-express-angular/ 

The debugger statement inserted so I could play around and figure out what's going on. I am really unsure how to debug this further. This is the first time I've touched CSRF, does anyone have suggestions

**Comment by dougwilson** [comment]
This error means you didn't have this above those lines you pasted:

```js
app.use(csurf())
```

**Comment by dougwilson** [comment]
In fact, even easier, simply change your code to this:
```js
var csurf = require('csurf');
app.use(csurf(), function (req, res, next) {
  debugger
  res.cookie('XSRF-TOKEN', req.csrfToken());
  next()
}
```

**Comment by mzarella** [comment]
@dougwilson I've been working on this too long if I missed that. Thank you very much!

**Comment by dougwilson** [comment]
It is no problem! :) I know how you feel :)
