### ISSUE TITLE
[feature request] Add ignore URL patterns (like options.ignoreMethods)

### ISSUE THREAD

**Issue by amurchick** [expressjs/csurf#64]
Scenario:
All my site forms protected by `csrf` - it is ok.
But url `/special` must receive `POST` request from other site (example, self-signed notification of payment) and there is no `csrf` available for this request.

Example:
```javascript
app.use(csurf({ignoreUrls: new RegExp('^/(special|nocsrf)')}));
```

And in library:

```javascript
    // verify the incoming token
    if (!ignoreMethod[req.method] && !req.url.match(ignoreUrls)) {
      verifytoken(req, tokens, secret, value(req))
    }
```

**Comment by dougwilson** [comment]
There has been many discussions about this. The answer is to simply wrap it yourself. The reason `ignoreMethods` exist is because wrapping doesn't allow you to reduce the restriction, only to add more.
```js
app.use(specificCsurf(/^/(special|nocsrf)/))

function specificCsurf(ignoreUrls) {
  var csrf = csurf()
  return function (req, res, next) {
    if (ignoreUrls.test(parseUrl(req).pathname)) return next()
    return csurf(req, res, next)
  }
}
```

**Comment by amurchick** [comment]
Thank you!

**Comment by db-s** [comment]
I also had same kind of requirement, fixed it by slightly changing the above code with the following.

`var csurf = require('csurf');
app.use(function(req, res, next) {
  if (/^\/(foo\/bar|special)/.test(req.path)) return next();
  csurf({cookie: true});
  next();
});`

**Comment by SOF3** [comment]
I want to use `req.csrfToken()` without checking mechanism, but the validation request is also a GET. The above method won't allow me to use the `req.csrfToken()` method.
