### ISSUE TITLE
csurf doesn't plays nice with cookie-parser and csrf

### ISSUE THREAD

**Issue by CTAPbIuMABP** [expressjs/csurf#68]
client code
```
$(document).ajaxSend(function (event, jqxhr, settings) {
	jqxhr.setRequestHeader("X-XSRF-TOKEN", readCookie("XSRF-TOKEN"));
});
```

server code, signed cookies
```js
app.use(cookieParser("keyboardcat"));
app.use(csrf({
    cookie: {
        key: "XSRF-TOKEN"
    }
}));
```

then cookie is signed by
https://github.com/expressjs/csurf/blob/master/index.js#L242
and looks like s:HASH

so this check fails
https://github.com/pillarjs/csrf/blob/master/index.js#L50

server code, unsigned cookies
```js
app.use(cookieParser());
app.use(csrf({
    cookie: {
        key: "XSRF-TOKEN"
    }
}));
```

then cookie is serialized (encodeURIComponent) by 
https://github.com/expressjs/csurf/blob/master/index.js#L211
and https://github.com/pillarjs/csrf/blob/master/index.js#L50 fails again

**Comment by dougwilson** [comment]
Hey! Thanks for the report. I'd be happy to look into this. Would you be willing to paste here a full app I can copy and paste into a file to run that demonstrates the issue? That would help speed up the fix :)

**Comment by dougwilson** [comment]
Nevermind, I see you are using Angular and using the wrong option. The cookie option is the secret, not the token, which is what you need Angular to read. A good tutorial is here: http://charandeepmatta.com/2014/06/04/csrfxsrf-protection-express-angular/

**Comment by CTAPbIuMABP** [comment]
i have end up with the same code
and don't understand why its not working out of the box

**Comment by dougwilson** [comment]
It's because you have to put the _CSRF token_ in the `XSRF-TOKEN` header for Angular; the `cookie` option for this module doesn't set the _token_ in that cookie, but the _secret_, which is different. The _token_ is only available from calling _req.csrfToken()_ in your code. You can of course use this to put the _token_ in a _cookie_, like that tutorial does for Angular.

**Comment by CTAPbIuMABP** [comment]
thx for explanations
