### ISSUE TITLE
Getting csrf token within a client-side framework?

### ISSUE THREAD

**Issue by canebat** [expressjs/csurf#70]
Hi, I just read [Understanding CSRF](https://github.com/pillarjs/understanding-csrf). At one point it states:

```
The last thing you want is an easy way for an attacker to get a CSRF token. Don't create a /csrf route just to grab a token.
```

How would this be avoided when using clientside framework like AngularJS? In a traditional server-side framework like Django, what happens is the csrf token is written into the HTML templates, and then those templates gets parsed by the templating engine with the final result getting sent and rendered on the client.

With Angularjs, I can have a registration form that is wholly generated on the clientside. The only information I would need from the server would be the csrf token.

So, I currently have a route that just sends back a csrf token:
```
router.get("/getCsrf", function(req, res) {
    res.json({"token": req.csrfToken()});
});
```

And wherever I need csrf in my forms, I just do this in the respective AngularJS controllers:
  
    $http.get("/getCsrf").success(function(csrf) {
        $scope.csrf = csrf["token"];
    });

Which will get sent back to the server after a form submission. But this seems exactly what the article said *NOT* to do. I'm not sure how else I should get the csrf token though, if everything is generated client-side.

Any thoughts?

**Comment by MikeBarnhardt** [comment]
I'm stuck on a similar issue. I'm using __Flux__ and __ReactJS__ for my client-side with __axios__ as my xhr library.

I send the csrf token in a meta tag like so:
```
<meta name="_csrf" content="{{csrfToken}}"/>
```

and then access it in my javascript with
```
let csrfToken = document.getElementsByTagName('meta').csrf.getAttribute('content');
```

However, if I manually delete the cookie and try to login a second time without refreshing the page I get an _invalid csrf token_ message. I don't know how else to solve this without a page refresh except for requesting a new token via ajax. It could be a simple solution, but some more perspective might help.

**Comment by gabeio** [comment]
Alternatively disable csrf *for routes you know are going to be submitted with things like flux & angular* and force the server to only accept local requests as per the article `CORS` (different per server) and some servers allow different `CORS` settings per route/area it all depends.

**Comment by dougwilson** [comment]
It's also important to note that if you restrict your routes to _never accept multipart/form-data or application/x-www-form-urlencoded_ (perhaps just _only_ accept JSON), then you don't even need CSRF tokens at all.

**Comment by gabeio** [comment]
great note @dougwilson hadn't thought of that!

**Comment by tcurdt** [comment]
@dougwilson Could you expand on that? I don't see how multipart/urlencode/json affects this.

**Comment by dougwilson** [comment]
@tcurdt my comment was to @gabeio not the original post.

As for the original post, idk why you cannot do what you're asking. If that other repo is confusing, please file the issue there rather than here, as it was written by the owner of that repo.
