### ISSUE TITLE
Moving csurf to individual routes instead of using it globally?

### ISSUE THREAD

**Issue by canebat** [expressjs/csurf#71]
I originally was using `body-parser` globally in my express app, but I moved it to the routes instead:
```js
// express app.js
...
var csrf = require('csurf');
var cookie = require("cookie-session");

// Not used globally anymore
// var bodyParser = require('body-parser');
// app.use(bodyParser.json());

app.use(cookie('secret));

// csurf 
app.use(csrf());
app.use(function(err, req, res, next) {
    if (err.code !== 'EBADCSRFTOKEN') return next(err);
    res.status(403).json({"error": "session has expired or tampered with"});
});

// routes
app.use('/', require('routes/root'));
app.use('/upload', require('routes/upload'));
...
```

```
// route/root.js
var bodyParser = require('body-parser');
var jsonParser = bodyParser.json();
...
route.post('/root', jsonParser, function(req, res) { ... });
```

```
// route/upload.js
var busboy = require('connect-busboy');
var busboyParser = busboy({
    limits: {
        fileSize: 10 * 1024 * 1024
    }
});
...
route.post("/files", busboy, function(req, res) {
  if (req.busboy) {
    req.busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        // handle uploaded files
    });
    req.pipe(req.busboy);
});
```

I'm not sure if I should similarly move `csurf` to the routes. I know that load order is important, but I've also noticed that `csurf` will still verify csrf tokens in all POST requests if I leave it globally as I have it. However, it will always fail verification in the case of the upload route (will throw 403 error). The upload route expects `multipart/form-data`.

Should I move `csurf` down to the routes? How would I use it? Would I have to declare it before `body-parser` or `busboy` in each route file? Something like:

```
// route/upload.js
var csurf = require('csurf');
app.use(function(err, req, res, next) {
    if (err.code !== 'EBADCSRFTOKEN') return next(err);
    res.status(403).json({"error": "session has expired or tampered with"});
});
var busboy = ....;

route.post("/files", csurf, busboy, function(req, res) { ..... });
```

```
// route/root.js
var csurf = require('csurf');
app.use(function(err, req, res, next) {
    if (err.code !== 'EBADCSRFTOKEN') return next(err);
    res.status(403).json({"error": "session has expired or tampered with"});
});
var bodyParser = ...;

route.post("/root", csurf, jsonParser, function(req, res) { ... });
```

**Comment by dougwilson** [comment]
I would recommend you move `csurf` into the routes as well. In fact, it's the way we suggest doing it in our readme: https://github.com/expressjs/csurf#simple-express-example

**Comment by canebat** [comment]
Would the `EBADCSRFTOKEN` error handler still live globally in app.js using `app.use(.. .);` or do they have to be defined again in each route? If left globally, would it have to be declared after I include my route, or before?

**Comment by dougwilson** [comment]
Just globally, though after your routes.
