### ISSUE TITLE
What wrong with this setup?

### ISSUE THREAD

**Issue by tcurdt** [expressjs/csurf#72]
Following the docs I setup the middleware

    app.use(cookieParser());
    app.use(csrf({ cookie: true }));

then on the client I do

    const csrf = Cookie.get('_csrf');
    console.log("submitting", csrf); => submitting f6u-JXBhkTLAj_MhghHJVlys
    fetch('/subscribe', {
      method:'post',
      headers: {
        'x-csrf-token': csrf || ""
      }
    }).then(function(response) {
      console.log(response.status);
    })

which eventually arrives here https://github.com/pillarjs/csrf/blob/master/index.js#L42 on the server with

    secret=f6u-JXBhkTLAj_MhghHJVlys token=f6u-JXBhkTLAj_MhghHJVlys

but following the code further until here https://github.com/pillarjs/csrf/blob/master/index.js#L59

    token=f6u-JXBhkTLAj_MhghHJVlys expected=f6u-EHZeCC1W8msTDvPpZ6paixHLUTY

and so the request gets rejected.

I must be missing something.

**Comment by dougwilson** [comment]
It's because the `_csrf` cookie is not the _token_, it's the _secret_. What you put in the header must come from `req.csrfToken()` function.

**Comment by tcurdt** [comment]
doh! thx!
