### ISSUE TITLE
Random 'misconfigured csrf' exception thrown

### ISSUE THREAD

**Issue by murdockcrc** [expressjs/csurf#73]
Hello,

Yesterday, our site started giving all users an http500 error, which we tracked back to csurf failing with the error message 'misconfigured csrf at getSecret'. The site had been up and running for weeks, and this error started getting reported out of the nowhere. Restarting the server brought the site back to normal.
Our site runs csurf 1.7.0, just wanted to file this issue and check if other users have been experiencing the same situation.
Unfortunately, I am not able to repro the issue.

**Comment by dougwilson** [comment]
Most likely occurred because your session store was down, as that will cause the error.

**Comment by dougwilson** [comment]
Closing due to lack of response; please let me know if the above doesn't answer your question, you have further concerns, etc.

**Comment by dougwilson** [comment]
Also, I believe this is essentially a duplicate of #60

**Comment by BirenGrooveHere** [comment]
I got the same error in redis server there is a port not open somehow it's not communicating with app server
