### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by pedrorw** [expressjs/csurf#76]
I have this odd behavior I get an error just the first time my page loads, basically is 'EBADCSRFTOKEN' I've been trying to figure it out why it happens. 

a snippet of the code (I'm  using MEANJS stack):

Express.js:
```javascript
app.use(busboy());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json({limit: '50mb'}));
app.enable('jsonp callback');
var cp = cookieParser;
app.use(cp());
app.use(csrf({cookie:true}));

app.use(function(err, req, res, next) {
    if (!err) return next();
        if(err.code === 'EBADCSRFTOKEN'){
            res.json(484, {data: 'invalid csrf token.'});
	    return;
    }
   // Error page
    res.status(500).render('500', {
        error: err.stack
    });
});

```

I get a cookie named _csrf, the issue is the token value is the same as the secret token, so when the library "converts" the secret token to be the expected token they don't match.

These are some example values:

Cookie BDir8-6hkdy-_YsXNb305IIx

Secret BDir8-6hkdy-_YsXNb305IIx

Token BDir8-6hkdy-_YsXNb305IIx

Expected BDir8-zbwt4-K_Uv8t1TtmxxctkfcMN1M

in the library the issue happens here:
```js
var index = token.indexOf('-') // obviusly there is no hypen in the token

  if (index === -1) {
    console.log('index not found not string');
    return false
  }
```
any advice?

**Comment by dougwilson** [comment]
Hi! The value in the `_csrf` cookie _is not the CSRF token for you to submit back to the app_.

If you need the CSRF token to be in a cookie for your client, then you can add the simple middleware in https://github.com/expressjs/csurf/issues/48#issuecomment-71872449 (and the rest of the issue explains a lot about what the difference between the tokens and the secret are, etc.).
