### ISSUE TITLE
Error which deals with disappeared '-' in token

### ISSUE THREAD

**Issue by SerjoPepper** [expressjs/csurf#83]
I am using csrf, with values stored in cookies.
Generated values do not contain '-' symbols, look at the screenshot
" verify Figq9QmqnHPNfErAFkuUFBTL Figq9QmqnHPNfErAFkuUFBTL { saltLength: 8, secretLength: 18 }"
![screenshot from 2015-09-17 15 38 44](https://cloud.githubusercontent.com/assets/191823/9933247/733b9854-5d52-11e5-8fe1-4e214bf2d644.png)
 
So csrf throws an error, deal with disappeared '-'

```
/**
 * Verify if a given token is valid for a given secret.
 *
 * @param {string} secret
 * @param {string} token
 * @public
 */

Tokens.prototype.verify = function verify(secret, token) {
  if (!secret || typeof secret !== 'string') {
    console.log('1')
    return false
  }

  if (!token || typeof token !== 'string') {
    console.log('2')
    return false
  }

  var index = token.indexOf('-')

  if (index === -1) {
    return false
  }

  var salt = token.substr(0, index)
  var expected = this._tokenize(secret, salt)

  return scmp(token, expected)
}
```
this code from https://github.com/pillarjs/csrf

**Comment by dougwilson** [comment]
Can you provide more information, a full, complete application I can reproduce with, a PR with a failing test or even a fix? I'm not able to reproduce the issue you are having, as all generated values are correctly including the `-` character for myself and our test suite here. There must be something else at play in your setup that is making the `-` disappear and I'd be glad to help, but need a lot more information.

**Comment by dougwilson** [comment]
Closing due to lack of response.

**Comment by cramatt** [comment]
Any updates here? @SerjoPepper how did you solve this? I'm seeing the same issue.

**Comment by gregmartyn** [comment]
This happens if you try to use the secret as the token. The token will have a `-` in it. _csrf is the secret, while `req.csrfToken()` uses `tokens.create(secret)` to generate a token.
