### ISSUE TITLE
Passing token value via jQuery Ajax ()

### ISSUE THREAD

**Issue by laraveling** [expressjs/csurf#86]
SOLVED : http://stackoverflow.com/questions/33628343/express-js-csrf-token-with-jquery-ajax/33637759#33637759

I am trying to implement csrf protection into my project but I can't make it work with jQuery Ajax.

* If I tamper the token using chrome dev tools before I send the form, I still see "data is being processed" text rather than "invalid csrf token" error.

* If I remove ajaxSetup, hidden input, add a meta tag, and add a _csrf: $('meta[name="_csrf"]').attr('content') to the ajax post, it works. But then I have to do it for every post. I want to define this once for all so it'll be applied to all ajax requests.

* If I remove the ajaxSetup part competely, I can't send the form at all, I get an error. (below)

###### POST http://localhost:3000/form 403 (Forbidden)

* If I comment out jQuery part, remove meta tag from head and add a hidden input to form (basically following the docs), it works as expected (if I tamper the token via chrome dev tools, I get an error).

What's missing here?

app.js

```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var csrf = require('csurf');
var bodyParser = require('body-parser');
var router = express.Router();
var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');
app.set('view options', {layout: false});

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
var csrfProtection = csrf({ cookie: true });
var parseForm = bodyParser.urlencoded({ extended: false });
app.use(cookieParser());

app.use(express.static(path.join(__dirname, 'public')));

app.get('/form', csrfProtection, function(req, res) {
    // pass the csrfToken to the view
    res.render('send', { csrfToken: req.csrfToken() });
});

app.post('/form', parseForm, csrfProtection, function(req, res) {
    res.send('data is being processed');
});

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use(function (err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}

// production error handler
// no stacktraces leaked to user
app.use(function (err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});

module.exports = app;
```

send.jade
```
html
    head
        meta(name='_csrf', content='#{csrfToken}')
    body
        form(action='/form', method='POST')
            |   Favorite color:
            input(type="hidden", name="_csrf", value="#{csrfToken}")
            input(type='text', class="favori", name='favoriteColor')
            button(type='submit') Submit
    script(src="javascripts/frontend/jquery/jquery-3.0.0-alpha1.js")
    script(src="javascripts/test.js")
```

test.js
```
$(document).ready(function () {

    $.ajaxSetup({
        headers: {'X-CSRF-Token': $('meta[name="_csrf"]').attr('content')}
    });

    $('button').click(function (e) {
        e.preventDefault();
        var text = $('.favori').val();
        alert(text);
        $.post(
            "/form",
            {
                text: text
            }, function (data) {
                console.log(data);
            });
    });
});
```

**Comment by laraveling** [comment]
The issue has been solved. Please refer to the stackoverflow question.

**Comment by dougwilson** [comment]
Hi @laraveling , sorry it took a bit for me to get to your issue. I'm glad you got it resolved! I see in your SO answer, you ended up putting it in the body instead of the header, but the reason your header is not working is because your `$.ajaxSetup` is called and saves the token prior to when you modify the HTML value, which is why you are not seeing the failure as you would expect. If you modify the HTML value and then re-run

    $.ajaxSetup({
        headers: {'X-CSRF-Token': $('meta[name="_csrf"]').attr('content')}
    });

In your web browser console, then it should fail as you expect, since the value will get picked back up from the HTML.

**Comment by laraveling** [comment]
@dougwilson 

Are you kidding? I got an answer in less than 24 hours, that's great!

Thank you for your answer, I appreciated.
