### ISSUE TITLE
Use HttpOnly and Secure flags on Cookies by default

### ISSUE THREAD

**Issue by wamoyo** [expressjs/csurf#90]
It would be nice if the library set HttpOnly and Secure flags on cookies by default. If not, then perhaps an option for this?

**Comment by dougwilson** [comment]
Yes, this can be added in the next major version. For now, you just have to set those yourself, using the `cookie` option (https://github.com/expressjs/csurf#cookie):
```js
app.use(csrf({cookie: {
  httpOnly: true,
  secure: true
}}))
```

**Comment by wamoyo** [comment]
Oh, that's super simple, thanks!

**Comment by idangozlan** [comment]
Hi @dougwilson , why are these options marked as false by default? isn't it defeat the purpose to keep a non httpOnly cookie for CSRF secret?

**Comment by dougwilson** [comment]
> why are these options marked as false by default?

Not all deployments are under HTTPS, especially local development.

>  isn't it defeat the purpose to keep a non httpOnly cookie for CSRF secret?

No.
