### ISSUE TITLE
feature request: automatically attach csrf tokens to requests from client side.

### ISSUE THREAD

**Issue by mebjas** [expressjs/csurf#95]
Currently we have to attach the tokens in forms manually 
```html
<input type="hidden" name="_csrf" value="{{csrfToken}}">
```
While we can take advantage of JavaScript to pick the token from cookies and attach it with every request {or all POST requests & certain GET request, as per configuration by user} automatically. This will support normal `HTML Form submissions`, `XHR requests`, `normal GET requests` and even `ActiveXObject` based requests. And not having to explicitly attach the token in the forms will make developers task easier, and application more secure. And same origin policy of cookies will ensure only scripts running on that page can access the cookies.

This has been implemented in `OWASP CSRF Protector Project`, check this out:  https://github.com/mebjas/CSRF-Protector-PHP/blob/master/js/csrfprotector.js

Also this is based on a research paper: [A server and browser transparent CSRF Defence for web 2.0 applications](https://www.acsac.org/2011/openconf/modules/request.php?module=oc_program&action=view.php&a=&id=72&type=2)

**Comment by dougwilson** [comment]
Hi! I really have no idea what the request is asking, in particular we are only a utility that gives tokens and validates them; we have no idea if people are using HTML forms or anything else, or even what templating language they are choosing to use.

Can you please make a pull request to implement the feature you desire?
