### ISSUE TITLE
Getting a 'ForbiddenError: invalid csrf token' when I'm sure the token is valid

### ISSUE THREAD

**Issue by GBcrazy** [expressjs/csurf#96]
Hello there, first time playing around with csurf. So, what happens is: I enter at localhost:3000 and get the _csrf cookie as expected. So I open chrome's console and get the _csrf token through document.cookie. After that, I try to make a simple post request with jquery, passing the param _csrf. Like this:

`$.post("login", {_csrf: "A1LocgwvosSbEbyM4pCr44bO"});  // token that I got from document.cookie`

But I get a 403 response and the error I put on the title. Maybe there's something I'm not seeing? I even put a middleware to check if req.body._csrf === req.cookies._csrf and it prints true. Here's the code:

```js
var express = require('express');
var bodyParser = require('body-parser');
var cookieParser = require('cookie-parser');
var csrf = require('csurf');
var app = express();

// middlewares
app.use(bodyParser.urlencoded({extended: false}));
app.use(cookieParser());
app.use(function(req, res, next){
    console.log(req.cookies._csrf === req.body._csrf);
    next();
})
app.use(csrf({cookie: true}));


app.post('/login', function(req, res){
    console.log("SUCCESS!");
});

app.get('/', function(req, res){
    res.sendFile(__dirname + '/views/login.html');
})

app.listen(3000);
```

Thanks in advance

**Comment by gabeio** [comment]
I believe you actually are not getting the csrf token which to need to validate the one with the cookie... you have to use `req.csrfToken()` to get the token with which this csrf module sends a cookie which together will validate the request.

**Comment by GBcrazy** [comment]
Hmm ok so I probably misunderstood how this protection works. I thought just using the middleware `app.use(csrf({cookie: true}))` would do this. Everytime I enter the page, the _csrf cookie changes, so I thought to validate it simply needed to be passed in as form data as well, so it guarantees it is being accessed by the domain. Can you explain me in more details how it's supposed to work?

**Comment by gabeio** [comment]
the csrf validation requires (in this case) 2 parts (cooke & form) they are both unique. when put together this library can tell if they are valid together. since the cookie is signed (hopefully) there is a very unlikely chance that the "attacker" will be able to guess or get a hold of the key which it was signed with so the cookie is usually the static element. Now since sometimes you want to have csrf in-front of a GET request (maybe one which hits a database so no one from other domains is using your data) you can pass the form part in the `_csrf` query. Alternatively if you are using something like xhr (javascript requests) you might be able and want to pass the csrf token back using a header. But one of those methods must be passed the second part of the token which is created by the function `req.csrfToken()`.

**Comment by GBcrazy** [comment]
Hmm, I think I got it. I was thinking the check was simply to see if both were equal, I didn't know that what was needed was to check their combination. That settles it for me. Thank you so much for your time gabeio.

**Comment by gabeio** [comment]
You are very welcome 👍

**Comment by GBcrazy** [comment]
Also, just one last thing. What is the best way/practice to pass the req.csrfToken() ? I'm asking this because I'm not using a template engine like jade. Is there a way to pass the data directly to the js I want? I was thinking about sending it as cookie but well I guess it would kinda screw the whole idea lol

**Comment by gabeio** [comment]
well there are 2 ways that I can think of js getting the token from `req.csrfToken()`...
 - 1 you literally make a little js template (think very small) which you can embed the token directly in the right spot and when served it will have the correct token.
 - 2 place it inside your template in a way that you can grab it in javascript either with a hidden form and get the `document.elementId("something").value`

**Comment by allanesquina** [comment]
Hey guys, nice topic, please, can you help me?
I wonder to know how can I pass the second part of token `req.csrfToken()` to my template to prevent GET requests? I mean, if I do not ignore the GET method, I can't access my template, so I'm not able to get the token to send it back. Split the validation from creation would solve this problem?

The code below doesn't work cos `csrf` already validates the token:

```javascript
// setup route middlewares
var csrfProtection = csrf({ignoreMethods: ['HEAD', 'OPTIONS']})
app.get('/', csrfProtection, function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})
```
I don't know, but I'm thinking something like that:
```javascript
// setup route middlewares
var csrfObj = csrf({ignoreMethods: ['HEAD', 'OPTIONS']})

// set the csrfToken function on req obj
app.use(csrfObj.configToken)

app.get('/', function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})

app.get('/secret', csrfObj.validate, function(req, res) {
  // pass the csrfToken to the view
  res.render('send', { csrfToken: req.csrfToken() })
})
```
I can check within error handler function like the example below, but is there a nice way to handle this?
```javascript
app.use(function (err, req, res, next) {
  if (err.code !== 'EBADCSRFTOKEN') return next(err)

  if (req.path.indexOf('/myrouter') !== -1) {
    // send the right response
    return;
  }

  res.status(403)
  res.send('form tampered with')
})
```
Thanks guys :+1:

**Comment by gabeio** [comment]
@allanesquina hi please open a separate issue. I will be glad to assist if I can.

Thanks

**Comment by miqmago** [comment]
Does it make sense to create a service to obtain `req.csrfToken()`? I'm thinking in angularjs with a provider that set's the token:

```js
angular.module('hbCSRF', [])

    .provider('csrf', function () {
        var headerName = 'xsrf-token';
        var cookieName = '_csrf';
        var allowedMethods = ['GET', 'HEAD', 'OPTIONS'];

        this.setHeaderName = function (n) {
            headerName = n;
        }
        this.setCookieName = function (n) {
            cookieName = n;
        }
        this.setAllowedMethods = function (n) {
            allowedMethods = n;
        }
        this.$get = function ($cookies) {
            return {
                'request': function (config) {
                    if (allowedMethods.indexOf(config.method) === -1) {
                        // HERE I WOULD GET THE TOKEN WHEN NEEDED, have to think how to do it sync...
                        config.headers[headerName] = $cookies.get(cookieName);
                    }
                    return config;
                }
            }
        };
    });
```

And in server:

```js
router.get('/token', (req, res) => {
    res.send(req.csrfToken());
});
```

**Comment by waybetterdeveloper** [comment]
@miqmago I believe adding such a route allows the malicious party to guess your token and use it.  See [this](https://github.com/pillarjs/understanding-csrf) for reference.

**Comment by twelve17** [comment]
@miqmago I believe adding such a route allows the malicious party to guess your token and use it. See [this](https://github.com/pillarjs/understanding-csrf) for reference.

**Comment by miqmago** [comment]
But the token is regenerated in each call, isn't it?

**Comment by twelve17** [comment]
@miqmago I did not write that document, but the way I interpret it is that the malicious party could make the request and then use the value before another request is made (and another token generated).

**Comment by dougwilson** [comment]
The original issue for this issue was finished, so I don't want to leave this issue open indefinitely, getting new posts. If you're having issues, please open a new issue to discuss your particular issue.
