### ISSUE TITLE
Angularjs set header, the old csrf token still be valid(should be invalid)

### ISSUE THREAD

**Issue by yvesshen** [expressjs/csurf#99]
Hi,

I use this midddleware for my expressjs+ Angularjs app.

Here is my config:
```js
var csrf = require('csurf');
app.use(cookieParser());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(csrf({ cookie: true }));
app.use(function(req, res, next) {
  res.cookie('XSRF-TOKEN', req.csrfToken());
  next();
});
```
following is router.
...

**But when I use burp suite to re-post my data like bellow:**

```
POST /reports/comment HTTP/1.1
Host: www.test.com:3002
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=utf-8
**X-XSRF-TOKEN: b7SGyDPD-hiWUlMY5EIbYJKoC_qD6RzsgmDk**
Referer: http://www.test.com:3002/reports
Content-Length: 38
Cookie: _csrf=KN1USSmU9h3oRrDcjrz5PwN5; XSRF-TOKEN=b7SGyDPD-hiWUlMY5EIbYJKoC_qD6RzsgmDk; connect.sid=s%3At4OKZwYjuzVArRKnQNUxCEnWMKGL61P0.BMAhrCGqL7ETrv4iAeAtmEZL3mK%2FMF%2FBm9pMvcqgC2w
Connection: keep-alive

{"comment":"123123123","report_id":22}
```

I can post the data for many times, because the old X-XSRF-TOKEN is NOT be invalid?

Could you tell me how to fix this?

**Comment by yvesshen** [comment]
Here is my response.
```
HTTP/1.1 200 OK
X-Powered-By: Express
Set-Cookie: XSRF-TOKEN=6lHVrwoo-DU8NvBan3rmnDLMaT-d8f-k6w-w; Path=/
Content-Type: text/html; charset=utf-8
Content-Length: 12
ETag: W/"c-fSzwxmSSWvPqa3rkxiCAmQ"
Date: Wed, 24 Aug 2016 08:54:02 GMT
Connection: keep-alive
Success!
```

**Comment by dougwilson** [comment]
Hi @yvesshen, I'm not sure why you would expect the token to be invalid. Can you point to where in our documentation that is stated? I'd be happy to fix the docs!

**Comment by yvesshen** [comment]
Hi. I am a security engineer. And it would be a best practise to always make csrf token be valid for once. Or hacker would reuse the token and post many same data. I use nodejs just now, so sorry , cannot review your code. That's why I would like to seek help from u.

**Comment by yvesshen** [comment]
In response , the token become 61HV... And only if your token is 61HV, can u post data. But the old token b7SG still be valid. That's my question . Thanks.

**Comment by dougwilson** [comment]
Yes, expiring after a single use is a better practice than continuing to accept, but it does not break CSRF prevention by allowing re-use. This is an entry-level module, using a stateless mechanism for code generation so that it does not need an infinitely-growing database to keep track of the use of every issued token. You may want to use a different module if you need that level of protection.

**Comment by yvesshen** [comment]
May I ask do you have any suggested modules?

**Comment by dougwilson** [comment]
I haven't had any use for the security offered beyond this module, so I'm not familiar with any others and what they may be. You're of course always welcome to offer up a pull request to add the extra functionality to this module if you desire as well :)!

**Comment by yvesshen** [comment]
Another thing is As I have set up the X-XSRF-TOKEN header in my request header. Do I still need to render _csrf-token in my post body?
Sth like this:
```
{"comment":"123123123","report_id":22,"_csrf":"xxxxxxxxx"}
```

**Comment by dougwilson** [comment]
By default the module will read from all the locations specified in the README. It only needs to find a token in one of those locations, so you do not need to put it more than once. You can also define your own custom `value` function to make the module read _only_ from the one place you want it, if that is desired :)

**Comment by yvesshen** [comment]
Ok. Thank you very much for your help!
